export type NavItem = {
  path: string
  label: string
}

export const topNavItems: NavItem[] = [
  { path: '/components/button', label: 'Components' },
  { path: '/docs/getting-started', label: 'Docs' },
]

export const sideNavGroups: Record<string, NavItem[]> = {
  components: [
    { path: '/components/affix', label: 'Affix' },
    { path: '/components/alert', label: 'Alert' },
    { path: '/components/anchor', label: 'Anchor' },
    { path: '/components/auto-complete', label: 'Auto Complete' },
    { path: '/components/avatar', label: 'Avatar' },
    { path: '/components/badge', label: 'Badge' },
    { path: '/components/border-beam', label: 'Border Beam' },
    { path: '/components/breadcrumb', label: 'Breadcrumb' },
    { path: '/components/button', label: 'Button' },
    { path: '/components/calendar', label: 'Calendar' },
    { path: '/components/card', label: 'Card' },
    { path: '/components/carousel', label: 'Carousel' },
    { path: '/components/cascader', label: 'Cascader' },
    { path: '/components/checkbox', label: 'Checkbox' },
    { path: '/components/collapse', label: 'Collapse' },
    { path: '/components/color-picker', label: 'Color Picker' },
    { path: '/components/config-provider', label: 'Config Provider' },
    { path: '/components/date-picker', label: 'Date Picker' },
    { path: '/components/descriptions', label: 'Descriptions' },
    { path: '/components/divider', label: 'Divider' },
    { path: '/components/drawer', label: 'Drawer' },
    { path: '/components/dropdown', label: 'Dropdown' },
    { path: '/components/empty', label: 'Empty' },
    { path: '/components/flex', label: 'Flex' },
    { path: '/components/float-button', label: 'Float Button' },
    { path: '/components/form', label: 'Form' },
    { path: '/components/grid', label: 'Grid' },
    { path: '/components/icon', label: 'Icon' },
    { path: '/components/image', label: 'Image' },
    { path: '/components/input', label: 'Input' },
    { path: '/components/input-number', label: 'Input Number' },
    { path: '/components/layout', label: 'Layout' },
    { path: '/components/list', label: 'List' },
    { path: '/components/masonry', label: 'Masonry' },
    { path: '/components/mentions', label: 'Mentions' },
    { path: '/components/menu', label: 'Menu' },
    { path: '/components/message', label: 'Message' },
    { path: '/components/modal', label: 'Modal' },
    { path: '/components/notification', label: 'Notification' },
    { path: '/components/pagination', label: 'Pagination' },
    { path: '/components/popconfirm', label: 'Popconfirm' },
    { path: '/components/popover', label: 'Popover' },
    { path: '/components/progress', label: 'Progress' },
    { path: '/components/qrcode', label: 'QRCode' },
    { path: '/components/radio', label: 'Radio' },
    { path: '/components/rate', label: 'Rate' },
    { path: '/components/result', label: 'Result' },
    { path: '/components/segmented', label: 'Segmented' },
    { path: '/components/select', label: 'Select' },
    { path: '/components/skeleton', label: 'Skeleton' },
    { path: '/components/slider', label: 'Slider' },
    { path: '/components/space', label: 'Space' },
    { path: '/components/spin', label: 'Spin' },
    { path: '/components/splitter', label: 'Splitter' },
    { path: '/components/statistic', label: 'Statistic' },
    { path: '/components/steps', label: 'Steps' },
    { path: '/components/switch', label: 'Switch' },
    { path: '/components/table', label: 'Table' },
    { path: '/components/tabs', label: 'Tabs' },
    { path: '/components/tag', label: 'Tag' },
    { path: '/components/time-picker', label: 'Time Picker' },
    { path: '/components/timeline', label: 'Timeline' },
    { path: '/components/tooltip', label: 'Tooltip' },
    { path: '/components/tour', label: 'Tour' },
    { path: '/components/transfer', label: 'Transfer' },
    { path: '/components/tree', label: 'Tree' },
    { path: '/components/tree-select', label: 'Tree Select' },
    { path: '/components/typography', label: 'Typography' },
    { path: '/components/upload', label: 'Upload' },
    { path: '/components/watermark', label: 'Watermark' },
  ],
  docs: [
    { path: '/docs/getting-started', label: 'Getting Started' },
    { path: '/docs/theming', label: 'Theming' },
  ],
}
