import type { DefaultThemeConfig } from '@kobalte/solidbase/default-theme'

export const docsThemeConfig = {
  nav: [
    { text: 'Components', link: '/components/button' },
    { text: 'Docs', link: '/docs/getting-started' },
  ],
  sidebar: {
    '/components': [
      { title: 'Affix', link: '/affix' },
      { title: 'Alert', link: '/alert' },
      { title: 'Anchor', link: '/anchor' },
      { title: 'Auto Complete', link: '/auto-complete' },
      { title: 'Avatar', link: '/avatar' },
      { title: 'Badge', link: '/badge' },
      { title: 'Border Beam', link: '/border-beam' },
      { title: 'Breadcrumb', link: '/breadcrumb' },
      { title: 'Button', link: '/button' },
      { title: 'Calendar', link: '/calendar' },
      { title: 'Card', link: '/card' },
      { title: 'Carousel', link: '/carousel' },
      { title: 'Cascader', link: '/cascader' },
      { title: 'Checkbox', link: '/checkbox' },
      { title: 'Collapse', link: '/collapse' },
      { title: 'Color Picker', link: '/color-picker' },
      { title: 'Config Provider', link: '/config-provider' },
      { title: 'Date Picker', link: '/date-picker' },
      { title: 'Descriptions', link: '/descriptions' },
      { title: 'Divider', link: '/divider' },
      { title: 'Drawer', link: '/drawer' },
      { title: 'Dropdown', link: '/dropdown' },
      { title: 'Empty', link: '/empty' },
      { title: 'Flex', link: '/flex' },
      { title: 'Float Button', link: '/float-button' },
      { title: 'Form', link: '/form' },
      { title: 'Grid', link: '/grid' },
      { title: 'Icon', link: '/icon' },
      { title: 'Image', link: '/image' },
      { title: 'Input', link: '/input' },
      { title: 'Input Number', link: '/input-number' },
      { title: 'Layout', link: '/layout' },
      { title: 'List', link: '/list' },
      { title: 'Masonry', link: '/masonry' },
      { title: 'Mentions', link: '/mentions' },
      { title: 'Menu', link: '/menu' },
      { title: 'Message', link: '/message' },
      { title: 'Modal', link: '/modal' },
      { title: 'Notification', link: '/notification' },
      { title: 'Pagination', link: '/pagination' },
      { title: 'Popconfirm', link: '/popconfirm' },
      { title: 'Popover', link: '/popover' },
      { title: 'Progress', link: '/progress' },
      { title: 'QRCode', link: '/qrcode' },
      { title: 'Radio', link: '/radio' },
      { title: 'Rate', link: '/rate' },
      { title: 'Result', link: '/result' },
      { title: 'Segmented', link: '/segmented' },
      { title: 'Select', link: '/select' },
      { title: 'Skeleton', link: '/skeleton' },
      { title: 'Slider', link: '/slider' },
      { title: 'Space', link: '/space' },
      { title: 'Spin', link: '/spin' },
      { title: 'Splitter', link: '/splitter' },
      { title: 'Statistic', link: '/statistic' },
      { title: 'Steps', link: '/steps' },
      { title: 'Switch', link: '/switch' },
      { title: 'Table', link: '/table' },
      { title: 'Tabs', link: '/tabs' },
      { title: 'Tag', link: '/tag' },
      { title: 'Time Picker', link: '/time-picker' },
      { title: 'Timeline', link: '/timeline' },
      { title: 'Tooltip', link: '/tooltip' },
      { title: 'Tour', link: '/tour' },
      { title: 'Transfer', link: '/transfer' },
      { title: 'Tree', link: '/tree' },
      { title: 'Tree Select', link: '/tree-select' },
      { title: 'Typography', link: '/typography' },
      { title: 'Upload', link: '/upload' },
      { title: 'Watermark', link: '/watermark' },
    ],
    '/docs': [
      { title: 'Getting Started', link: '/getting-started' },
      { title: 'Theming', link: '/theming' },
    ],
  },
} satisfies DefaultThemeConfig
