import { useStyleRegister } from '@ant-design-solid/cssinjs'
import { useToken } from '../config-provider'
import { loadingIconRotateKeyframes, loadingIconRotateStyle } from '../shared/loading-icon-style'

export function useSelectStyle(prefixCls: string) {
  const token = useToken()
  return useStyleRegister({ theme: 'default', token: token(), path: ['Select', prefixCls] }, () => {
    const t = token()
    return {
      ...loadingIconRotateKeyframes,
      [`.${prefixCls}`]: {
        position: 'relative',
        display: 'inline-block',
        width: 160,
        color: t.colorText,
        'font-size': `${t.fontSize}px`,
        'font-family': t.fontFamily,
        'line-height': `${t.controlHeight}px`,
      },
      [`.${prefixCls}-selector`]: {
        position: 'relative',
        display: 'flex',
        'align-items': 'center',
        gap: 4,
        width: '100%',
        height: t.controlHeight,
        'min-height': t.controlHeight,
        padding: `0 ${t.paddingSM}px`,
        border: `${t.lineWidth}px solid ${t.colorBorder}`,
        'border-radius': t.borderRadius,
        background: t.colorBgContainer,
        cursor: 'pointer',
        'box-sizing': 'border-box',
        overflow: 'hidden',
      },
      [`.${prefixCls}-large .${prefixCls}-selector`]: {
        height: t.controlHeightLG,
        'min-height': t.controlHeightLG,
        'font-size': `${t.fontSize + 2}px`,
        'line-height': `${t.controlHeightLG}px`,
      },
      [`.${prefixCls}-small .${prefixCls}-selector`]: {
        height: t.controlHeightSM,
        'min-height': t.controlHeightSM,
        'font-size': `${Math.max(t.fontSize - 2, 12)}px`,
        'line-height': `${t.controlHeightSM}px`,
      },
      [`.${prefixCls}-multiple .${prefixCls}-selector`]: {
        height: 'auto',
        'min-height': t.controlHeight,
        overflow: 'visible',
      },
      [`.${prefixCls}-multiple.${prefixCls}-large .${prefixCls}-selector`]: {
        height: 'auto',
        'min-height': t.controlHeightLG,
      },
      [`.${prefixCls}-multiple.${prefixCls}-small .${prefixCls}-selector`]: {
        height: 'auto',
        'min-height': t.controlHeightSM,
      },
      [`.${prefixCls}-filled .${prefixCls}-selector`]: { background: t.colorFillAlter },
      [`.${prefixCls}-borderless .${prefixCls}-selector`]: { border: '0' },
      [`.${prefixCls}-underlined .${prefixCls}-selector`]: {
        'border-top': 0,
        'border-left': 0,
        'border-right': 0,
        'border-radius': 0,
      },
      [`.${prefixCls}-status-error .${prefixCls}-selector`]: { borderColor: t.colorError },
      [`.${prefixCls}-status-warning .${prefixCls}-selector`]: { borderColor: t.colorWarning },
      [`.${prefixCls}-disabled .${prefixCls}-selector`]: {
        color: t.colorTextDisabled,
        background: t.colorFillAlter,
        cursor: 'not-allowed',
      },
      [`.${prefixCls}-selection-item`]: {
        flex: 1,
        'min-width': 0,
        height: '100%',
        'line-height': 'inherit',
        'text-align': 'left',
        overflow: 'hidden',
        'text-overflow': 'ellipsis',
        'white-space': 'nowrap',
      },
      [`.${prefixCls}-selection-overflow`]: {
        display: 'flex',
        'align-items': 'center',
        gap: 4,
        flex: 1,
        'min-width': 0,
        'flex-wrap': 'wrap',
        padding: '2px 0',
      },
      [`.${prefixCls}-tag`]: {
        display: 'inline-flex',
        'align-items': 'center',
        gap: 4,
        flex: 'none',
        padding: `0 ${t.paddingXS}px`,
        background: t.colorFillAlter,
        'border-radius': t.borderRadius,
        height: 22,
        'line-height': '20px',
      },
      [`.${prefixCls}-tag-close`]: {
        border: 0,
        padding: 0,
        width: 14,
        height: 14,
        background: 'transparent',
        color: t.colorTextSecondary,
        cursor: 'pointer',
        display: 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        'font-size': 10,
        'line-height': 1,
      },
      [`.${prefixCls}-tag-close svg`]: {
        width: '0.7em',
        height: '0.7em',
      },
      [`.${prefixCls}-prefix, .${prefixCls}-arrow`]: {
        display: 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        flex: 'none',
        color: t.colorTextSecondary,
        'line-height': 1,
      },
      [`.${prefixCls}-arrow`]: {
        width: 16,
        height: 16,
        transition: 'transform 0.2s ease',
      },
      [`.${prefixCls}-arrow-open`]: {
        transform: 'rotate(180deg)',
      },
      ...loadingIconRotateStyle(`.${prefixCls}-arrow-loading svg`),
      [`.${prefixCls}-selection-search`]: {
        flex: 1,
        'min-width': 0,
        display: 'inline-flex',
        'align-items': 'center',
        height: '100%',
      },
      [`.${prefixCls}-search-input`]: {
        flex: 1,
        'min-width': 24,
        height: '100%',
        border: 0,
        outline: 0,
        background: 'transparent',
        color: 'inherit',
        'font-size': 'inherit',
        'line-height': 'inherit',
        padding: 0,
      },
      [`.${prefixCls}-selection-search-multiple`]: {
        flex: '0 1 120px',
        height: 22,
        'line-height': '20px',
      },
      [`.${prefixCls}-search-input::placeholder`]: {
        color: t.colorTextDisabled,
      },
      [`.${prefixCls}-placeholder`]: {
        flex: 1,
        'min-width': 0,
        height: '100%',
        'line-height': 'inherit',
        'text-align': 'left',
        color: t.colorTextDisabled,
        overflow: 'hidden',
        'text-overflow': 'ellipsis',
        'white-space': 'nowrap',
      },
      [`.${prefixCls}-clear`]: {
        position: 'absolute',
        top: '50%',
        right: t.paddingSM,
        transform: 'translateY(-50%)',
        'z-index': 1,
        border: 0,
        padding: 0,
        width: 16,
        height: 16,
        background: 'inherit',
        color: t.colorTextDisabled,
        cursor: 'pointer',
        display: 'inline-flex',
        'align-items': 'center',
        'justify-content': 'center',
        flex: 'none',
        'font-size': 12,
        'line-height': 1,
        opacity: 0,
        'pointer-events': 'none',
        transition: 'opacity 0.2s ease',
      },
      [`.${prefixCls}:not(.${prefixCls}-disabled):hover .${prefixCls}-clear`]: {
        opacity: 1,
        'pointer-events': 'auto',
      },
      [`.${prefixCls}-clear svg`]: {
        width: '1em',
        height: '1em',
      },
      [`.${prefixCls}-dropdown`]: {
        marginTop: 4,
        padding: `${t.paddingXS}px 0`,
        border: `${t.lineWidth}px solid ${t.colorBorder}`,
        'border-radius': t.borderRadius,
        background: t.colorBgContainer,
        'box-shadow': '0 6px 16px rgba(0, 0, 0, 0.08)',
        overflow: 'auto',
      },
      [`.${prefixCls}-item`]: { padding: `${t.paddingXS}px ${t.paddingSM}px`, cursor: 'pointer' },
      [`.${prefixCls}-item`]: {
        display: 'flex',
        'align-items': 'center',
        'justify-content': 'space-between',
        padding: `${t.paddingXS}px ${t.paddingSM}px`,
        cursor: 'pointer',
      },
      [`.${prefixCls}-item-group`]: {
        padding: `${t.paddingXS}px ${t.paddingSM}px`,
        color: t.colorTextSecondary,
        'font-size': `${Math.max(t.fontSize - 2, 12)}px`,
      },
      [`.${prefixCls}-item-option-selected`]: {
        color: t.colorPrimary,
        background: t.colorFillAlter,
      },
      [`.${prefixCls}-item-option-disabled`]: { color: t.colorTextDisabled, cursor: 'not-allowed' },
      [`.${prefixCls}-empty`]: {
        padding: `${t.paddingSM}px`,
        color: t.colorTextDisabled,
        'text-align': 'center',
      },
    }
  })
}
