import type { AliasToken, ComponentTokenMap, ThemeConfig } from './types'

const overrideStore = new WeakMap<AliasToken, ThemeConfig['components']>()

function isDarkToken(token: AliasToken) {
  return token.colorBgContainer !== '#ffffff'
}

function selectedBg(token: AliasToken) {
  return isDarkToken(token) ? 'rgba(22, 119, 255, 0.2)' : '#e6f4ff'
}

export function attachComponentOverrides(
  token: AliasToken,
  components: ThemeConfig['components'] = {},
): AliasToken {
  overrideStore.set(token, components)
  return token
}

export function getComponentToken<K extends keyof ComponentTokenMap>(
  componentName: K,
  token: AliasToken,
): ComponentTokenMap[K] {
  const defaults: ComponentTokenMap = {
    Button: {
      borderRadius: token.borderRadius,
      fontWeight: 400,
      primaryColor: '#fff',
      defaultBorderColor: token.colorBorder,
      paddingInline: token.padding,
    },
    Input: {
      activeBorderColor: token.colorPrimary,
      hoverBorderColor: token.colorPrimaryHover,
      clearIconColor: token.colorTextDisabled,
      paddingInline: token.paddingSM,
    },
    InputNumber: {
      activeBorderColor: token.colorPrimary,
      activeShadow: `0 0 0 2px ${token.colorFillAlter}`,
      addonBg: token.colorFillAlter,
      filledHandleBg: token.colorBgContainer,
      handleActiveBg: token.colorFillAlter,
      handleBg: token.colorBgContainer,
      handleBorderColor: token.colorBorderSecondary,
      handleFontSize: 10,
      handleHoverColor: token.colorPrimary,
      handleVisible: true,
      handleWidth: 22,
      hoverBorderColor: token.colorPrimaryHover,
      inputFontSize: token.fontSize,
      inputFontSizeLG: token.fontSizeLG,
      inputFontSizeSM: Math.max(token.fontSizeSM, 12),
      paddingBlock: token.paddingXS,
      paddingBlockLG: token.paddingXS,
      paddingBlockSM: 1,
      paddingInline: token.paddingSM,
      paddingInlineLG: token.paddingSM,
      paddingInlineSM: token.paddingXS,
    },
    Space: { gapSmall: token.marginXS, gapMiddle: token.marginSM, gapLarge: token.margin },
    Typography: {
      titleMarginBottom: token.marginSM,
      titleFontWeight: 600,
      paragraphMarginBottom: token.margin,
    },
    Grid: { columns: 24 },
    Form: {
      labelColor: token.colorText,
      labelRequiredMarkColor: token.colorError,
      itemMarginBottom: token.marginLG,
      verticalLabelPadding: token.paddingXS,
      explainColor: token.colorError,
    },
    Select: {
      optionHeight: token.controlHeight,
      optionPadding: token.paddingSM,
      optionSelectedBg: selectedBg(token),
      optionActiveBg: token.colorFillAlter,
      clearIconColor: token.colorTextDisabled,
    },
    Checkbox: {
      size: 16,
      borderRadius: token.borderRadius / 2,
      checkColor: '#ffffff',
    },
    Radio: {
      size: 16,
      dotSize: 8,
    },
    Switch: {
      trackHeight: 22,
      trackMinWidth: 44,
      handleSize: 18,
    },
    Alert: {
      padding: token.paddingSM,
      borderRadius: token.borderRadius,
      withDescriptionPadding: token.padding,
      iconSize: 16,
      successBg: isDarkToken(token) ? 'rgba(82, 196, 26, 0.12)' : '#f6ffed',
      successBorderColor: isDarkToken(token) ? 'rgba(82, 196, 26, 0.35)' : '#b7eb8f',
      infoBg: isDarkToken(token) ? 'rgba(22, 119, 255, 0.12)' : '#e6f4ff',
      infoBorderColor: isDarkToken(token) ? 'rgba(22, 119, 255, 0.35)' : '#91caff',
      warningBg: isDarkToken(token) ? 'rgba(250, 173, 20, 0.12)' : '#fffbe6',
      warningBorderColor: isDarkToken(token) ? 'rgba(250, 173, 20, 0.35)' : '#ffe58f',
      errorBg: isDarkToken(token) ? 'rgba(255, 77, 79, 0.12)' : '#fff2f0',
      errorBorderColor: isDarkToken(token) ? 'rgba(255, 77, 79, 0.35)' : '#ffccc7',
    },
    Message: {
      noticePadding: token.paddingSM,
      noticeBorderRadius: token.borderRadius,
      contentBg: token.colorBgElevated,
      contentShadow: token.boxShadow,
    },
    Notification: {
      width: 384,
      padding: token.padding,
      borderRadius: token.borderRadius,
      bg: token.colorBgElevated,
      boxShadow: token.boxShadow,
    },
    Modal: {
      contentBg: token.colorBgElevated,
      headerBg: token.colorBgElevated,
      titleColor: token.colorText,
      titleFontSize: token.fontSize + 2,
      borderRadius: token.borderRadius,
      boxShadow: token.boxShadow,
      maskBg: 'rgba(0, 0, 0, 0.45)',
    },
    Popconfirm: {
      width: 280,
      padding: token.padding,
      borderRadius: token.borderRadius,
      bg: token.colorBgElevated,
      boxShadow: token.boxShadow,
    },
    Table: {
      headerBg: token.colorFillAlter,
      headerColor: token.colorText,
      rowHoverBg: token.colorFillAlter,
      borderColor: token.colorBorderSecondary,
      cellPadding: token.padding,
      cellPaddingSm: token.paddingSM,
      cellPaddingLg: token.paddingLG,
      borderRadius: token.borderRadius,
      emptyColor: token.colorTextSecondary,
    },
    Tag: {
      defaultBg: token.colorFillAlter,
      defaultColor: token.colorText,
      borderColor: token.colorBorder,
      borderRadius: token.borderRadius / 2,
      paddingInline: token.paddingXS,
      fontSize: token.fontSize,
      lineHeight: token.lineHeight,
      closeIconColor: token.colorTextSecondary,
      successBg: isDarkToken(token) ? 'rgba(82, 196, 26, 0.12)' : '#f6ffed',
      successBorderColor: isDarkToken(token) ? 'rgba(82, 196, 26, 0.35)' : '#b7eb8f',
      warningBg: isDarkToken(token) ? 'rgba(250, 173, 20, 0.12)' : '#fffbe6',
      warningBorderColor: isDarkToken(token) ? 'rgba(250, 173, 20, 0.35)' : '#ffe58f',
      errorBg: isDarkToken(token) ? 'rgba(255, 77, 79, 0.12)' : '#fff2f0',
      errorBorderColor: isDarkToken(token) ? 'rgba(255, 77, 79, 0.35)' : '#ffccc7',
      processingBg: isDarkToken(token) ? 'rgba(22, 119, 255, 0.12)' : '#e6f4ff',
      processingBorderColor: isDarkToken(token) ? 'rgba(22, 119, 255, 0.35)' : '#91caff',
    },
    Badge: {
      overflowIndicatorHeight: 20,
      overflowIndicatorHeightSm: 14,
      dotSize: 6,
      textFontSize: 12,
      textFontSizeSm: 10,
      colorBg: token.colorError,
      colorText: '#ffffff',
      statusSize: 6,
    },
    Tabs: {
      itemColor: token.colorText,
      itemSelectedColor: token.colorPrimary,
      itemHoverColor: token.colorPrimaryHover,
      itemDisabledColor: token.colorTextDisabled,
      inkBarColor: token.colorPrimary,
      cardBg: token.colorFillAlter,
      cardBorderColor: token.colorBorderSecondary,
      horizontalItemPadding: token.padding,
      horizontalItemPaddingSm: token.paddingSM,
      horizontalItemPaddingLg: token.paddingLG,
    },
    Card: {
      headerBg: 'transparent',
      headerFontSize: token.fontSizeLG,
      headerFontSizeSM: token.fontSize,
      headerHeight: token.controlHeightLG + token.padding,
      headerHeightSM: token.controlHeight,
      actionsBg: token.colorBgContainer,
      actionsLiMargin: token.paddingSM,
      tabsMarginBottom: -token.paddingLG - 1,
      extraColor: token.colorText,
      bodyPadding: token.paddingLG,
      bodyPaddingSM: token.paddingSM,
      headerPadding: token.paddingLG,
      headerPaddingSM: token.paddingSM,
      headerBorderBottom: token.colorBorderSecondary,
    },
    Popover: {
      bg: token.colorBgElevated,
      borderRadius: token.borderRadius,
      boxShadow: token.boxShadow,
      minWidth: 177,
      maxWidth: 276,
      paddingBlock: token.paddingSM,
      paddingInline: token.padding,
    },
    Tooltip: {
      bg: 'rgba(0, 0, 0, 0.85)',
      color: '#ffffff',
      borderRadius: token.borderRadius,
      paddingBlock: token.paddingXS,
      paddingInline: token.paddingSM,
      boxShadow: token.boxShadow,
      maxWidth: 250,
    },
    Tree: {
      nodeSelectedBg: selectedBg(token),
    },
    Dropdown: {
      bg: token.colorBgElevated,
      boxShadow: token.boxShadow,
      borderRadius: token.borderRadius,
      itemColor: token.colorText,
      itemHoverBg: token.colorFillAlter,
      itemDisabledColor: token.colorTextDisabled,
      itemPaddingBlock: token.paddingXS,
      itemPaddingInline: token.paddingSM,
      minWidth: 120,
    },
    Tour: {
      width: 320,
      padding: token.padding,
      borderRadius: token.borderRadius,
      bg: token.colorBgElevated,
      boxShadow: token.boxShadow,
      maskBg: 'rgba(0, 0, 0, 0.45)',
      targetBorderRadius: token.borderRadius,
      zIndex: 1070,
    },
    Layout: {
      bodyBg: token.colorBgLayout,
      headerBg: '#001529',
      headerColor: token.colorTextLightSolid,
      headerHeight: 64,
      headerPadding: `0 ${token.paddingLG}px`,
      footerBg: token.colorBgLayout,
      footerPadding: `${token.padding}px ${token.paddingLG}px`,
      lightSiderBg: token.colorBgContainer,
      lightTriggerBg: token.colorBgContainer,
      lightTriggerColor: token.colorText,
      siderBg: '#001529',
      triggerBg: '#002140',
      triggerColor: token.colorTextLightSolid,
      triggerHeight: 48,
      zeroTriggerWidth: 40,
      zeroTriggerHeight: 40,
    },
  }
  const overrides = overrideStore.get(token)?.[componentName] ?? {}
  return { ...defaults[componentName], ...overrides } as ComponentTokenMap[K]
}
