import type { AliasToken, ComponentTokenMap, ThemeConfig } from './types'

const overrideStore = new WeakMap<AliasToken, ThemeConfig['components']>()

function isDarkToken(token: AliasToken) {
  return token.colorBgContainer !== '#ffffff'
}

function selectedBg(token: AliasToken) {
  return isDarkToken(token) ? 'rgba(22, 119, 255, 0.2)' : '#e6f4ff'
}

export function attachComponentOverrides(
  token: AliasToken,
  components: ThemeConfig['components'] = {},
): AliasToken {
  overrideStore.set(token, components)
  return token
}

export function getComponentToken<K extends keyof ComponentTokenMap>(
  componentName: K,
  token: AliasToken,
): NonNullable<ComponentTokenMap[K]> {
  const defaults: ComponentTokenMap = {
    Button: {
      borderRadius: token.borderRadius,
      fontWeight: 400,
      iconGap: token.marginXS,
      defaultShadow: `0 ${token.controlOutlineWidth}px 0 ${token.controlTmpOutline}`,
      primaryShadow: `0 ${token.controlOutlineWidth}px 0 ${token.controlOutline}`,
      dangerShadow: `0 ${token.controlOutlineWidth}px 0 ${token.colorErrorOutline}`,
      primaryColor: token.colorTextLightSolid,
      dangerColor: token.colorTextLightSolid,
      solidTextColor: token.colorTextLightSolid,
      defaultColor: token.colorText,
      defaultBg: token.colorBgContainer,
      defaultBorderColor: token.colorBorder,
      defaultHoverBg: token.colorBgContainer,
      defaultHoverColor: token.colorPrimaryHover,
      defaultHoverBorderColor: token.colorPrimaryHover,
      defaultActiveBg: token.colorBgContainer,
      defaultActiveColor: token.colorPrimaryActive,
      defaultActiveBorderColor: token.colorPrimaryActive,
      borderColorDisabled: token.colorBorderDisabled,
      defaultGhostColor: token.colorBgContainer,
      ghostBg: 'transparent',
      defaultGhostBorderColor: token.colorBgContainer,
      textTextColor: token.colorText,
      textTextHoverColor: token.colorText,
      textTextActiveColor: token.colorText,
      textHoverBg: token.colorFillTertiary,
      linkHoverBg: 'transparent',
      paddingInline: token.paddingContentHorizontal - token.lineWidth,
      paddingInlineLG: token.paddingContentHorizontalLG - token.lineWidth,
      paddingInlineSM: token.paddingContentHorizontalSM - token.lineWidth,
      paddingBlock: 0,
      paddingBlockLG: 0,
      paddingBlockSM: 0,
      contentFontSize: token.fontSize,
      contentFontSizeLG: token.fontSizeLG,
      contentFontSizeSM: token.fontSize,
      contentLineHeight: token.lineHeight,
      contentLineHeightLG: token.lineHeightLG,
      contentLineHeightSM: token.lineHeight,
      defaultBgDisabled: token.colorBgContainerDisabled,
      dashedBgDisabled: token.colorBgContainerDisabled,
    },
    Breadcrumb: {
      itemColor: token.colorTextDescription,
      lastItemColor: token.colorText,
      iconFontSize: token.fontSize,
      linkColor: token.colorTextDescription,
      linkHoverColor: token.colorText,
      separatorColor: token.colorTextDescription,
      separatorMargin: token.marginXS,
    },
    BorderBeam: {},
    Carousel: {
      arrowSize: 16,
      arrowOffset: token.marginXS,
      dotWidth: 16,
      dotHeight: 3,
      dotGap: token.marginXXS,
      dotOffset: 12,
      dotWidthActive: 24,
      dotActiveWidth: 24,
    },
    Input: {
      paddingBlock: Math.max(
        Math.round(((token.controlHeight - token.fontSize * token.lineHeight) / 2) * 10) / 10 -
          token.lineWidth,
        0,
      ),
      paddingBlockSM: Math.max(
        Math.round(((token.controlHeightSM - token.fontSize * token.lineHeight) / 2) * 10) / 10 -
          token.lineWidth,
        0,
      ),
      paddingBlockLG: Math.max(
        Math.ceil(((token.controlHeightLG - token.fontSizeLG * token.lineHeightLG) / 2) * 10) / 10 -
          token.lineWidth,
        0,
      ),
      paddingInline: token.paddingSM - token.lineWidth,
      paddingInlineSM: token.controlPaddingHorizontalSM - token.lineWidth,
      paddingInlineLG: token.controlPaddingHorizontal - token.lineWidth,
      activeBorderColor: token.colorPrimary,
      activeBg: token.colorBgContainer,
      activeShadow: `0 0 0 ${token.controlOutlineWidth}px ${token.controlOutline}`,
      addonBg: token.colorFillAlter,
      clearBg: token.colorFillQuaternary,
      errorActiveShadow: `0 0 0 ${token.controlOutlineWidth}px ${token.colorErrorOutline}`,
      hoverBorderColor: token.colorPrimaryHover,
      hoverBg: token.colorBgContainer,
      clearIconColor: token.colorTextDisabled,
      inputFontSize: token.fontSize,
      inputFontSizeLG: token.fontSizeLG,
      inputFontSizeSM: token.fontSize,
      warningActiveShadow: `0 0 0 ${token.controlOutlineWidth}px ${token.colorWarningOutline}`,
    },
    InputNumber: {
      activeBorderColor: token.colorPrimary,
      activeShadow: `0 0 0 2px ${token.colorFillAlter}`,
      addonBg: token.colorFillAlter,
      filledHandleBg: token.colorBgContainer,
      handleActiveBg: token.colorFillAlter,
      handleBg: token.colorBgContainer,
      handleBorderColor: token.colorBorderSecondary,
      handleFontSize: 10,
      handleHoverColor: token.colorPrimary,
      handleVisible: true,
      handleWidth: 22,
      hoverBorderColor: token.colorPrimaryHover,
      inputFontSize: token.fontSize,
      inputFontSizeLG: token.fontSizeLG,
      inputFontSizeSM: Math.max(token.fontSizeSM, 12),
      paddingBlock: token.paddingXS,
      paddingBlockLG: token.paddingXS,
      paddingBlockSM: 1,
      paddingInline: token.paddingSM,
      paddingInlineLG: token.paddingSM,
      paddingInlineSM: token.paddingXS,
    },
    DatePicker: {
      activeBg: token.colorBgContainer,
      activeBorderColor: token.colorPrimary,
      activeShadow: `0 0 0 ${token.controlOutlineWidth}px ${token.controlOutline}`,
      addonBg: token.colorFillAlter,
      cellActiveWithRangeBg: token.colorPrimaryBg,
      cellBgDisabled: token.colorBgContainerDisabled,
      cellHoverBg: token.controlItemBgHover,
      cellHoverWithRangeBg: token.colorPrimaryBgHover,
      cellRangeBorderColor: token.colorPrimary,
      cellHeight: 24,
      cellWidth: 36,
      hoverBg: token.colorBgContainer,
      hoverBorderColor: token.colorPrimaryHover,
      inputFontSize: token.fontSize,
      inputFontSizeLG: token.fontSizeLG,
      inputFontSizeSM: token.fontSize,
      multipleItemBg: token.colorFillAlter,
      multipleItemBorderColor: token.colorBorderSecondary,
      multipleItemHeight: 20,
      multipleItemHeightLG: 24,
      multipleItemHeightSM: 16,
      paddingBlock: token.paddingXXS,
      paddingBlockLG: token.paddingXS,
      paddingBlockSM: 0,
      paddingInline: token.paddingSM,
      paddingInlineLG: token.paddingSM,
      paddingInlineSM: token.paddingXS,
      presetsWidth: 120,
      textHeight: token.controlHeight,
      timeColumnHeight: 224,
      timeColumnWidth: 56,
      withoutTimeCellHeight: 66,
    },
    Calendar: {
      fullBg: token.colorBgContainer,
      fullPanelBg: token.colorBgContainer,
      itemActiveBg: token.colorPrimaryBg,
      miniContentHeight: 256,
      monthControlWidth: 70,
      yearControlWidth: 80,
    },
    ColorPicker: {
      colorPickerWidth: 234,
      colorPickerHandlerSize: 16,
      colorPickerHandlerSizeSM: 12,
      colorPickerAlphaInputWidth: 44,
      colorPickerInputNumberHandleWidth: 16,
      colorPickerPresetColorSize: 24,
      colorPickerInsetShadow: `inset 0 0 1px 0 ${token.colorTextQuaternary}`,
      colorPickerSliderHeight: 8,
      colorPickerPreviewSize: 24,
    },
    Space: { gapSmall: token.marginXS, gapMiddle: token.marginSM, gapLarge: token.margin },
    Flex: { flexGapSM: token.paddingXS, flexGap: token.padding, flexGapLG: token.paddingLG },
    Typography: {
      titleMarginBottom: token.marginSM,
      titleFontWeight: 600,
      paragraphMarginBottom: token.margin,
    },
    Grid: { columns: 24 },
    Descriptions: {
      labelBg: token.colorFillAlter,
      titleMarginBottom: token.marginSM,
      itemPaddingBottom: token.padding,
      colonMarginInlineStart: token.marginXXS / 2,
      colonMarginInlineEnd: token.marginXS,
      contentColor: token.colorText,
      labelColor: token.colorTextTertiary,
      extraColor: token.colorText,
      cellPaddingBlock: token.paddingSM,
      cellPaddingInline: token.padding,
      cellPaddingBlockMD: token.paddingXS,
      cellPaddingInlineMD: token.paddingSM,
      cellPaddingBlockSM: Math.max(2, Math.floor(token.paddingXS / 2)),
      cellPaddingInlineSM: token.paddingXS,
    },
    Form: {
      labelRequiredMarkColor: token.colorError,
      labelColor: token.colorTextHeading,
      labelFontSize: token.fontSize,
      labelHeight: token.controlHeight,
      labelColonMarginInlineStart: token.marginXXS / 2,
      labelColonMarginInlineEnd: token.marginXS,
      itemMarginBottom: token.marginLG,
      inlineItemMarginBottom: 0,
      verticalLabelPadding: token.paddingXS,
      verticalLabelMargin: 0,
      explainColor: token.colorError,
      extraColor: token.colorTextDescription,
      feedbackIconSize: token.fontSize,
      feedbackIconMarginInlineStart: token.marginXS,
    },
    Select: {
      optionHeight: token.controlHeight,
      optionPadding: token.paddingSM,
      optionSelectedBg: selectedBg(token),
      optionActiveBg: token.colorFillAlter,
      clearIconColor: token.colorTextDisabled,
    },
    Cascader: {
      optionHeight: token.controlHeight,
      optionPadding: token.paddingSM,
      optionSelectedBg: selectedBg(token),
      optionActiveBg: token.colorFillAlter,
      optionSelectedColor: token.colorPrimary,
      dropdownHeight: 180,
      controlWidth: 184,
      menuWidth: 120,
      multipleItemBg: token.colorFillAlter,
      multipleItemBorderColor: token.colorBorderSecondary,
      multipleItemHeight: 22,
      activeBorderColor: token.colorPrimary,
      activeShadow: `0 0 0 ${token.controlOutlineWidth}px ${token.controlOutline}`,
      hoverBorderColor: token.colorPrimaryHover,
      clearIconColor: token.colorTextDisabled,
    },
    Checkbox: {
      size: 16,
      borderRadius: token.borderRadius / 2,
      checkColor: '#ffffff',
    },
    Radio: {
      size: 16,
      dotSize: 8,
    },
    Switch: {
      trackHeight: 22,
      trackMinWidth: 44,
      handleSize: 18,
    },
    Alert: {
      padding: token.paddingSM,
      borderRadius: token.borderRadius,
      withDescriptionPadding: token.padding,
      iconSize: 16,
      successBg: isDarkToken(token) ? 'rgba(82, 196, 26, 0.12)' : '#f6ffed',
      successBorderColor: isDarkToken(token) ? 'rgba(82, 196, 26, 0.35)' : '#b7eb8f',
      infoBg: isDarkToken(token) ? 'rgba(22, 119, 255, 0.12)' : '#e6f4ff',
      infoBorderColor: isDarkToken(token) ? 'rgba(22, 119, 255, 0.35)' : '#91caff',
      warningBg: isDarkToken(token) ? 'rgba(250, 173, 20, 0.12)' : '#fffbe6',
      warningBorderColor: isDarkToken(token) ? 'rgba(250, 173, 20, 0.35)' : '#ffe58f',
      errorBg: isDarkToken(token) ? 'rgba(255, 77, 79, 0.12)' : '#fff2f0',
      errorBorderColor: isDarkToken(token) ? 'rgba(255, 77, 79, 0.35)' : '#ffccc7',
    },
    Message: {
      noticePadding: token.paddingSM,
      noticeBorderRadius: token.borderRadius,
      contentBg: token.colorBgElevated,
      contentShadow: token.boxShadow,
    },
    Notification: {
      width: 384,
      padding: token.padding,
      borderRadius: token.borderRadius,
      bg: token.colorBgElevated,
      boxShadow: token.boxShadow,
    },
    Modal: {
      contentBg: token.colorBgElevated,
      headerBg: token.colorBgElevated,
      titleColor: token.colorText,
      titleFontSize: token.fontSize + 2,
      borderRadius: token.borderRadius,
      boxShadow: token.boxShadow,
      maskBg: 'rgba(0, 0, 0, 0.45)',
    },
    Drawer: {
      zIndexPopup: 1000,
      footerPaddingBlock: token.paddingSM,
      footerPaddingInline: token.paddingLG,
      draggerSize: 6,
    },
    Divider: {
      textPaddingInline: '1em',
      orientationMargin: 0.05,
      verticalMarginInline: `${token.marginXS}px`,
    },
    Popconfirm: {
      width: 280,
      padding: token.padding,
      borderRadius: token.borderRadius,
      bg: token.colorBgElevated,
      boxShadow: token.boxShadow,
    },
    Table: {
      headerBg: token.colorFillAlter,
      headerColor: token.colorText,
      rowHoverBg: token.colorFillAlter,
      borderColor: token.colorBorderSecondary,
      cellPadding: token.padding,
      cellPaddingSm: token.paddingSM,
      cellPaddingLg: token.paddingLG,
      borderRadius: token.borderRadius,
      emptyColor: token.colorTextSecondary,
    },
    Tag: {
      defaultBg: token.colorFillAlter,
      defaultColor: token.colorText,
      borderColor: token.colorBorder,
      borderRadius: token.borderRadius / 2,
      paddingInline: token.paddingXS,
      fontSize: token.fontSize,
      lineHeight: token.lineHeight,
      closeIconColor: token.colorTextSecondary,
      successBg: isDarkToken(token) ? 'rgba(82, 196, 26, 0.12)' : '#f6ffed',
      successBorderColor: isDarkToken(token) ? 'rgba(82, 196, 26, 0.35)' : '#b7eb8f',
      warningBg: isDarkToken(token) ? 'rgba(250, 173, 20, 0.12)' : '#fffbe6',
      warningBorderColor: isDarkToken(token) ? 'rgba(250, 173, 20, 0.35)' : '#ffe58f',
      errorBg: isDarkToken(token) ? 'rgba(255, 77, 79, 0.12)' : '#fff2f0',
      errorBorderColor: isDarkToken(token) ? 'rgba(255, 77, 79, 0.35)' : '#ffccc7',
      processingBg: isDarkToken(token) ? 'rgba(22, 119, 255, 0.12)' : '#e6f4ff',
      processingBorderColor: isDarkToken(token) ? 'rgba(22, 119, 255, 0.35)' : '#91caff',
    },
    Badge: {
      overflowIndicatorHeight: 20,
      overflowIndicatorHeightSm: 14,
      dotSize: 6,
      textFontSize: 12,
      textFontSizeSm: 10,
      colorBg: token.colorError,
      colorText: '#ffffff',
      statusSize: 6,
    },
    FloatButton: {
      size: token.controlHeightLG,
      iconSize: token.fontSizeIcon * 1.5,
      insetBlockEnd: token.marginXXL,
      insetInlineEnd: token.marginLG,
    },
    Tabs: {
      itemColor: token.colorText,
      itemSelectedColor: token.colorPrimary,
      itemHoverColor: token.colorPrimaryHover,
      itemDisabledColor: token.colorTextDisabled,
      inkBarColor: token.colorPrimary,
      cardBg: token.colorFillAlter,
      cardBorderColor: token.colorBorderSecondary,
      horizontalItemPadding: token.padding,
      horizontalItemPaddingSm: token.paddingSM,
      horizontalItemPaddingLg: token.paddingLG,
    },
    Card: {
      headerBg: 'transparent',
      headerFontSize: token.fontSizeLG,
      headerFontSizeSM: token.fontSize,
      headerHeight: token.controlHeightLG + token.padding,
      headerHeightSM: token.controlHeight,
      actionsBg: token.colorBgContainer,
      actionsLiMargin: token.paddingSM,
      tabsMarginBottom: -token.paddingLG - 1,
      extraColor: token.colorText,
      bodyPadding: token.paddingLG,
      bodyPaddingSM: token.paddingSM,
      headerPadding: token.paddingLG,
      headerPaddingSM: token.paddingSM,
      headerBorderBottom: token.colorBorderSecondary,
    },
    Collapse: {
      headerBg: 'transparent',
      headerPadding: `${token.paddingSM}px ${token.padding}px`,
      headerPaddingSM: `${token.paddingXS}px ${token.paddingSM}px`,
      contentPadding: `${token.padding}px`,
      contentBg: token.colorBgContainer,
    },
    Popover: {
      bg: token.colorBgElevated,
      borderRadius: token.borderRadius,
      boxShadow: token.boxShadow,
      minWidth: 177,
      maxWidth: 276,
      paddingBlock: token.paddingSM,
      paddingInline: token.padding,
    },
    Tooltip: {
      bg: 'rgba(0, 0, 0, 0.85)',
      color: '#ffffff',
      borderRadius: token.borderRadius,
      paddingBlock: token.paddingXS,
      paddingInline: token.paddingSM,
      boxShadow: token.boxShadow,
      maxWidth: 250,
    },
    Tree: {
      nodeSelectedBg: selectedBg(token),
    },
    Dropdown: {
      bg: token.colorBgElevated,
      boxShadow: token.boxShadowSecondary,
      borderRadius: token.borderRadiusLG,
      itemColor: token.colorText,
      itemHoverBg: token.colorFillAlter,
      itemDisabledColor: token.colorTextDisabled,
      paddingBlock: (token.controlHeight - token.fontSize * token.lineHeight) / 2,
      dropdownArrowDistance: token.sizePopupArrow / 2 + token.marginXXS,
      dropdownEdgeChildPadding: token.paddingXXS,
      minWidth: 120,
      zIndexPopup: token.zIndexPopupBase + 50,
      itemPaddingBlock: (token.controlHeight - token.fontSize * token.lineHeight) / 2,
      itemPaddingInline: token.paddingSM,
    },
    Menu: {
      itemBg: token.colorBgContainer,
      itemColor: token.colorText,
      itemHoverBg: token.colorBgTextHover,
      itemHoverColor: token.colorPrimary,
      itemSelectedBg: token.colorPrimaryBg,
      itemSelectedColor: token.colorPrimary,
      itemDisabledColor: token.colorTextDisabled,
      groupTitleColor: token.colorTextSecondary,
      popupBg: token.colorBgElevated,
      subMenuItemBg: token.colorFillAlter,
      darkItemBg: '#001529',
      darkPopupBg: '#001529',
      darkSubMenuItemBg: '#000c17',
      darkItemColor: 'rgba(255,255,255,0.65)',
      darkItemHoverColor: token.colorTextLightSolid,
      darkItemSelectedBg: token.colorPrimary,
      darkItemSelectedColor: token.colorTextLightSolid,
      darkItemDisabledColor: 'rgba(255,255,255,0.25)',
      darkGroupTitleColor: 'rgba(255,255,255,0.45)',
      darkItemDividerBg: 'rgba(255,255,255,0.18)',
    },
    Tour: {
      width: 320,
      padding: token.padding,
      borderRadius: token.borderRadius,
      bg: token.colorBgElevated,
      boxShadow: token.boxShadow,
      maskBg: 'rgba(0, 0, 0, 0.45)',
      targetBorderRadius: token.borderRadius,
      zIndex: 1070,
    },
    Layout: {
      bodyBg: token.colorBgLayout,
      headerBg: '#001529',
      headerColor: token.colorTextLightSolid,
      headerHeight: 64,
      headerPadding: `0 ${token.paddingLG}px`,
      footerBg: token.colorBgLayout,
      footerPadding: `${token.padding}px ${token.paddingLG}px`,
      lightSiderBg: token.colorBgContainer,
      lightTriggerBg: token.colorBgContainer,
      lightTriggerColor: token.colorText,
      siderBg: '#001529',
      triggerBg: '#002140',
      triggerColor: token.colorTextLightSolid,
      triggerHeight: 48,
      zeroTriggerWidth: 40,
      zeroTriggerHeight: 40,
    },
  }
  const overrides = overrideStore.get(token)?.[componentName] ?? {}
  return { ...defaults[componentName], ...overrides } as NonNullable<ComponentTokenMap[K]>
}
