export const filesThatShouldUseIconComponents = [
  'auto-complete/auto-complete.tsx',
  'cascader/cascader.tsx',
  'date-picker/date-picker.tsx',
  'drawer/drawer.tsx',
  'image/image.tsx',
  'mentions/mentions.tsx',
  'message/holder.tsx',
  'modal/modal.tsx',
  'notification/holder.tsx',
  'progress/progress.tsx',
  'result/result.tsx',
  'select/select.tsx',
  'steps/steps.tsx',
  'tag/tag.tsx',
  'time-picker/time-picker.tsx',
  'tour/tour.tsx',
  'tree-select/tree-select.tsx',
  'upload/upload.tsx',
] as const
