import { readdir, rm, writeFile } from 'node:fs/promises'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const scriptDir = dirname(fileURLToPath(import.meta.url))
const packageDir = join(scriptDir, '..')
const iconsDir = join(packageDir, 'src', 'icons')
const indexFile = join(packageDir, 'src', 'index.tsx')
const asnDir = join(packageDir, 'node_modules', '@ant-design', 'icons-svg', 'es', 'asn')

const generatedHeader =
  '// This file is generated by scripts/generate-icons.mjs. Do not edit manually.\n'

function toKebabCase(iconName) {
  return iconName
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .toLowerCase()
}

function toIconName(fileName) {
  return fileName.replace(/\.js$/, '')
}

function generatedIconSource(iconName) {
  return `${generatedHeader}import ${iconName}Svg from '@ant-design/icons-svg/es/asn/${iconName}'
import { Icon, type IconProps } from '../components/icon'

export function ${iconName}(props: IconProps) {
  return <Icon icon={${iconName}Svg} {...props} />
}
`
}

function generatedIndexSource(icons) {
  const exports = icons
    .map(
      ({ fileName, iconName }) =>
        `export { ${iconName} } from './icons/${fileName.replace(/\.tsx$/, '')}'`,
    )
    .join('\n')

  return `${generatedHeader}export { Icon } from './components/icon'
export type { IconProps, TwoToneColor } from './components/icon'
${exports}
`
}

const asnFiles = await readdir(asnDir)
const icons = asnFiles
  .filter((fileName) => fileName.endsWith('.js'))
  .map((fileName) => {
    const iconName = toIconName(fileName)

    return {
      iconName,
      fileName: `${toKebabCase(iconName)}.tsx`,
    }
  })
  .sort((first, second) => first.iconName.localeCompare(second.iconName))

const existingFiles = await readdir(iconsDir, { withFileTypes: true })
await Promise.all(
  existingFiles
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .filter((fileName) => fileName.endsWith('.tsx') && !fileName.endsWith('.test.tsx'))
    .map((fileName) => rm(join(iconsDir, fileName))),
)

await Promise.all(
  icons.map(({ iconName, fileName }) =>
    writeFile(join(iconsDir, fileName), generatedIconSource(iconName)),
  ),
)
await writeFile(indexFile, generatedIndexSource(icons))

console.log(`Generated ${icons.length} icons in ${relative(process.cwd(), iconsDir)}`)
