import { useStyleRegister } from '@ant-design-solid/cssinjs'
import { getComponentToken } from '@ant-design-solid/theme'
import { useToken } from '../config-provider'

export function useCascaderStyle(prefixCls: string) {
  const token = useToken()
  return useStyleRegister(
    { theme: 'default', token: token(), path: ['Cascader', prefixCls] },
    () => {
      const t = token()
      const cascader = getComponentToken('Cascader', t)
      return {
        [`.${prefixCls}`]: {
          position: 'relative',
          display: 'inline-block',
          width: `${cascader.controlWidth}px`,
          color: t.colorText,
          'font-size': `${t.fontSize}px`,
          'font-family': t.fontFamily,
        },
        [`.${prefixCls}-selector`]: {
          position: 'relative',
          display: 'inline-flex',
          'align-items': 'center',
          'justify-content': 'space-between',
          gap: `${t.paddingXS}px`,
          width: '100%',
          height: `${t.controlHeight}px`,
          padding: `0 ${t.paddingSM}px`,
          border: `${t.lineWidth}px solid ${t.colorBorder}`,
          'border-radius': `${t.borderRadius}px`,
          background: t.colorBgContainer,
          cursor: 'pointer',
          'box-sizing': 'border-box',
        },
        [`.${prefixCls}-open .${prefixCls}-selector`]: {
          'border-color': t.colorPrimary,
          'box-shadow': cascader.activeShadow,
        },
        [`.${prefixCls}:not(.${prefixCls}-disabled):hover .${prefixCls}-selector`]: {
          'border-color': cascader.hoverBorderColor,
        },
        [`.${prefixCls}-disabled .${prefixCls}-selector`]: {
          color: t.colorTextDisabled,
          background: t.colorFillAlter,
          cursor: 'not-allowed',
        },

        [`.${prefixCls}-large .${prefixCls}-selector`]: { height: `${t.controlHeightLG}px` },
        [`.${prefixCls}-small .${prefixCls}-selector`]: { height: `${t.controlHeightSM}px` },
        [`.${prefixCls}-borderless .${prefixCls}-selector`]: { border: '0' },
        [`.${prefixCls}-filled .${prefixCls}-selector`]: { background: t.colorFillAlter },
        [`.${prefixCls}-underlined .${prefixCls}-selector`]: {
          'border-width': `0 0 ${t.lineWidth}px`,
          'border-radius': '0',
        },
        [`.${prefixCls}-status-error .${prefixCls}-selector`]: { 'border-color': t.colorError },
        [`.${prefixCls}-status-warning .${prefixCls}-selector`]: { 'border-color': t.colorWarning },
        [`.${prefixCls}-prefix`]: {
          display: 'inline-flex',
          'align-items': 'center',
          color: t.colorText,
        },
        [`.${prefixCls}-selection-overflow`]: {
          display: 'inline-flex',
          'align-items': 'center',
          gap: `${t.marginXS}px`,
          flex: '1',
          'min-width': '0',
          'flex-wrap': 'wrap',
        },
        [`.${prefixCls}-tag`]: {
          display: 'inline-flex',
          'align-items': 'center',
          gap: `${t.marginXS}px`,
          padding: `0 ${t.paddingXS}px`,
          background: cascader.multipleItemBg,
          border: `${t.lineWidth}px solid ${cascader.multipleItemBorderColor}`,
          'border-radius': `${t.borderRadius}px`,
          height: `${cascader.multipleItemHeight}px`,
          'line-height': `${cascader.multipleItemHeight - 2}px`,
        },
        [`.${prefixCls}-tag-close`]: {
          border: '0',
          padding: '0',
          background: 'transparent',
          color: t.colorTextDisabled,
          cursor: 'pointer',
        },
        [`.${prefixCls}-search-input`]: {
          flex: '1',
          'min-width': '32px',
          border: '0',
          outline: '0',
          background: 'transparent',
          color: t.colorText,
          'font-size': 'inherit',
        },
        [`.${prefixCls}-search`]: {
          display: 'inline-flex',
          'align-items': 'center',
          gap: `${t.marginXS}px`,
          flex: '1',
          'min-width': '0',
        },
        [`.${prefixCls}-search-icon`]: {
          display: 'inline-flex',
          color: t.colorTextSecondary,
        },
        [`.${prefixCls}-search-list`]: {
          minWidth: '160px',
          margin: '0',
          padding: `${t.paddingXS}px 0`,
          'list-style': 'none',
        },
        [`.${prefixCls}-search-item`]: {
          padding: `${t.paddingXS}px ${cascader.optionPadding}px`,
          cursor: 'pointer',
          'white-space': 'nowrap',
        },
        [`.${prefixCls}-search-item:hover`]: { background: cascader.optionActiveBg },
        [`.${prefixCls}-checkbox`]: {
          display: 'inline-flex',
          'align-items': 'center',
          'justify-content': 'center',
          width: '14px',
          height: '14px',
          border: `${t.lineWidth}px solid ${t.colorBorder}`,
          'border-radius': `${t.borderRadius}px`,
          'font-size': '10px',
        },
        [`.${prefixCls}-loading-icon`]: { color: t.colorTextDisabled },
        [`.${prefixCls}-placeholder`]: { color: t.colorTextDisabled },
        [`.${prefixCls}-selection-item`]: {
          overflow: 'hidden',
          'text-overflow': 'ellipsis',
          'white-space': 'nowrap',
        },
        [`.${prefixCls}-clear`]: {
          position: 'absolute',
          top: '50%',
          'inset-inline-end': `${t.paddingSM}px`,
          transform: 'translateY(-50%)',
          'z-index': 1,
          border: '0',
          padding: '0',
          width: '16px',
          height: '16px',
          background: 'inherit',
          color: cascader.clearIconColor,
          cursor: 'pointer',
          display: 'inline-flex',
          'align-items': 'center',
          'justify-content': 'center',
          'font-size': `${t.fontSize}px`,
          'line-height': '1',
          opacity: 0,
          'pointer-events': 'none',
          transition: 'opacity 0.2s ease',
        },
        [`.${prefixCls}:not(.${prefixCls}-disabled):hover .${prefixCls}-clear`]: {
          opacity: 1,
          'pointer-events': 'auto',
        },
        [`.${prefixCls}:not(.${prefixCls}-disabled):focus-within .${prefixCls}-clear`]: {
          opacity: 1,
          'pointer-events': 'auto',
        },
        [`.${prefixCls}-clear:hover`]: { color: t.colorText },
        [`.${prefixCls}-dropdown`]: {
          display: 'inline-flex',
          marginTop: `${t.marginXS}px`,
          border: `${t.lineWidth}px solid ${t.colorBorder}`,
          'border-radius': `${t.borderRadius}px`,
          background: t.colorBgContainer,
          'box-shadow': t.boxShadow,
        },
        [`.${prefixCls}-panel`]: {
          position: 'relative',
          display: 'inline-flex',
          marginTop: '0',
        },
        [`.${prefixCls}-menu`]: {
          minWidth: `${cascader.menuWidth}px`,
          minHeight: `${cascader.dropdownHeight}px`,
          margin: '0',
          padding: `${t.paddingXS}px 0`,
          'list-style': 'none',
          'border-inline-end': `${t.lineWidth}px solid ${t.colorBorder}`,
        },
        [`.${prefixCls}-menu:last-child`]: { 'border-inline-end': '0' },
        [`.${prefixCls}-menu-item`]: {
          display: 'flex',
          'align-items': 'center',
          'justify-content': 'space-between',
          gap: `${t.paddingSM}px`,
          minHeight: `${cascader.optionHeight}px`,
          padding: `${t.paddingXS}px ${cascader.optionPadding}px`,
          cursor: 'pointer',
          'white-space': 'nowrap',
        },
        [`.${prefixCls}-menu-item:hover`]: { background: cascader.optionActiveBg },
        [`.${prefixCls}-menu-item-selected`]: {
          color: cascader.optionSelectedColor,
          background: cascader.optionSelectedBg,
        },
        [`.${prefixCls}-menu-item-active`]: { background: cascader.optionActiveBg },
        [`.${prefixCls}-menu-item-disabled`]: {
          color: t.colorTextDisabled,
          cursor: 'not-allowed',
        },
        [`.${prefixCls}-menu-item-disabled:hover`]: { background: 'transparent' },
        [`.${prefixCls}-menu-item-expand-icon`]: {
          color: t.colorTextDisabled,
          'font-size': `${t.fontSize}px`,
        },
        [`.${prefixCls}-suffix`]: {
          display: 'inline-flex',
          'align-items': 'center',
          color: t.colorTextSecondary,
          'line-height': 1,
        },
        [`.${prefixCls}-empty`]: {
          minWidth: `${cascader.menuWidth}px`,
          padding: `${t.paddingSM}px`,
          color: t.colorTextDisabled,
          'text-align': 'center',
        },
      }
    },
  )
}
