export const navItems = [
  { path: '/', label: 'Home' },
  { path: '/docs/getting-started', label: 'Getting Started' },
  { path: '/docs/theming', label: 'Theming' },
  { path: '/components/config-provider', label: 'ConfigProvider' },
  { path: '/components/input', label: 'Input' },
  { path: '/components/form', label: 'Form' },
  { path: '/components/select', label: 'Select' },
  { path: '/components/checkbox', label: 'Checkbox' },
  { path: '/components/radio', label: 'Radio' },
  { path: '/components/switch', label: 'Switch' },
  { path: '/components/table', label: 'Table' },
  { path: '/components/tag', label: 'Tag' },
  { path: '/components/badge', label: 'Badge' },
  { path: '/components/tabs', label: 'Tabs' },
  { path: '/components/tooltip', label: 'Tooltip' },
  { path: '/components/dropdown', label: 'Dropdown' },
  { path: '/components/alert', label: 'Alert' },
  { path: '/components/message', label: 'Message' },
  { path: '/components/notification', label: 'Notification' },
  { path: '/components/modal', label: 'Modal' },
  { path: '/components/popconfirm', label: 'Popconfirm' },
  { path: '/components/button', label: 'Button' },
  { path: '/components/divider', label: 'Divider' },
  { path: '/components/card', label: 'Card' },
  { path: '/components/space', label: 'Space' },
  { path: '/components/typography', label: 'Typography' },
  { path: '/components/grid', label: 'Grid' },
]
