export const navItems = [
  { path: '/', label: 'Home' },
  { path: '/docs/getting-started', label: 'Getting Started' },
  { path: '/docs/theming', label: 'Theming' },
  { path: '/components/config-provider', label: 'ConfigProvider' },
  { path: '/components/input', label: 'Input' },
  { path: '/components/form', label: 'Form' },
  { path: '/components/select', label: 'Select' },
  { path: '/components/checkbox', label: 'Checkbox' },
  { path: '/components/radio', label: 'Radio' },
  { path: '/components/switch', label: 'Switch' },
  { path: '/components/button', label: 'Button' },
  { path: '/components/space', label: 'Space' },
  { path: '/components/typography', label: 'Typography' },
  { path: '/components/grid', label: 'Grid' },
]
