// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AccountBookFilledSvg from '@ant-design/icons-svg/es/asn/AccountBookFilled'
import { Icon, type IconProps } from '../components/icon'

export function AccountBookFilled(props: IconProps) {
  return <Icon icon={AccountBookFilledSvg} {...props} />
}
