// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AccountBookOutlinedSvg from '@ant-design/icons-svg/es/asn/AccountBookOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AccountBookOutlined(props: IconProps) {
  return <Icon icon={AccountBookOutlinedSvg} {...props} />
}
