// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AimOutlinedSvg from '@ant-design/icons-svg/es/asn/AimOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AimOutlined(props: IconProps) {
  return <Icon icon={AimOutlinedSvg} {...props} />
}
