// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AlertOutlinedSvg from '@ant-design/icons-svg/es/asn/AlertOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AlertOutlined(props: IconProps) {
  return <Icon icon={AlertOutlinedSvg} {...props} />
}
