// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AlertFilledSvg from '@ant-design/icons-svg/es/asn/AlertFilled'
import { Icon, type IconProps } from '../components/icon'

export function AlertFilled(props: IconProps) {
  return <Icon icon={AlertFilledSvg} {...props} />
}
