// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AlertTwoToneSvg from '@ant-design/icons-svg/es/asn/AlertTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function AlertTwoTone(props: IconProps) {
  return <Icon icon={AlertTwoToneSvg} {...props} />
}
