// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AlibabaOutlinedSvg from '@ant-design/icons-svg/es/asn/AlibabaOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AlibabaOutlined(props: IconProps) {
  return <Icon icon={AlibabaOutlinedSvg} {...props} />
}
