// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AlignLeftOutlinedSvg from '@ant-design/icons-svg/es/asn/AlignLeftOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AlignLeftOutlined(props: IconProps) {
  return <Icon icon={AlignLeftOutlinedSvg} {...props} />
}
