// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AlignRightOutlinedSvg from '@ant-design/icons-svg/es/asn/AlignRightOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AlignRightOutlined(props: IconProps) {
  return <Icon icon={AlignRightOutlinedSvg} {...props} />
}
