// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AlignCenterOutlinedSvg from '@ant-design/icons-svg/es/asn/AlignCenterOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AlignCenterOutlined(props: IconProps) {
  return <Icon icon={AlignCenterOutlinedSvg} {...props} />
}
