// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AlipaySquareFilledSvg from '@ant-design/icons-svg/es/asn/AlipaySquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function AlipaySquareFilled(props: IconProps) {
  return <Icon icon={AlipaySquareFilledSvg} {...props} />
}
