// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AlipayOutlinedSvg from '@ant-design/icons-svg/es/asn/AlipayOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AlipayOutlined(props: IconProps) {
  return <Icon icon={AlipayOutlinedSvg} {...props} />
}
