// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AlipayCircleFilledSvg from '@ant-design/icons-svg/es/asn/AlipayCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function AlipayCircleFilled(props: IconProps) {
  return <Icon icon={AlipayCircleFilledSvg} {...props} />
}
