// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AliwangwangFilledSvg from '@ant-design/icons-svg/es/asn/AliwangwangFilled'
import { Icon, type IconProps } from '../components/icon'

export function AliwangwangFilled(props: IconProps) {
  return <Icon icon={AliwangwangFilledSvg} {...props} />
}
