// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AliwangwangOutlinedSvg from '@ant-design/icons-svg/es/asn/AliwangwangOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AliwangwangOutlined(props: IconProps) {
  return <Icon icon={AliwangwangOutlinedSvg} {...props} />
}
