// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AliyunOutlinedSvg from '@ant-design/icons-svg/es/asn/AliyunOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AliyunOutlined(props: IconProps) {
  return <Icon icon={AliyunOutlinedSvg} {...props} />
}
