// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AmazonSquareFilledSvg from '@ant-design/icons-svg/es/asn/AmazonSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function AmazonSquareFilled(props: IconProps) {
  return <Icon icon={AmazonSquareFilledSvg} {...props} />
}
