// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AmazonOutlinedSvg from '@ant-design/icons-svg/es/asn/AmazonOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AmazonOutlined(props: IconProps) {
  return <Icon icon={AmazonOutlinedSvg} {...props} />
}
