// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AmazonCircleFilledSvg from '@ant-design/icons-svg/es/asn/AmazonCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function AmazonCircleFilled(props: IconProps) {
  return <Icon icon={AmazonCircleFilledSvg} {...props} />
}
