// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AndroidFilledSvg from '@ant-design/icons-svg/es/asn/AndroidFilled'
import { Icon, type IconProps } from '../components/icon'

export function AndroidFilled(props: IconProps) {
  return <Icon icon={AndroidFilledSvg} {...props} />
}
