// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AndroidOutlinedSvg from '@ant-design/icons-svg/es/asn/AndroidOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AndroidOutlined(props: IconProps) {
  return <Icon icon={AndroidOutlinedSvg} {...props} />
}
