// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AntCloudOutlinedSvg from '@ant-design/icons-svg/es/asn/AntCloudOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AntCloudOutlined(props: IconProps) {
  return <Icon icon={AntCloudOutlinedSvg} {...props} />
}
