// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AntDesignOutlinedSvg from '@ant-design/icons-svg/es/asn/AntDesignOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AntDesignOutlined(props: IconProps) {
  return <Icon icon={AntDesignOutlinedSvg} {...props} />
}
