// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ApartmentOutlinedSvg from '@ant-design/icons-svg/es/asn/ApartmentOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ApartmentOutlined(props: IconProps) {
  return <Icon icon={ApartmentOutlinedSvg} {...props} />
}
