// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ApiFilledSvg from '@ant-design/icons-svg/es/asn/ApiFilled'
import { Icon, type IconProps } from '../components/icon'

export function ApiFilled(props: IconProps) {
  return <Icon icon={ApiFilledSvg} {...props} />
}
