// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ApiTwoToneSvg from '@ant-design/icons-svg/es/asn/ApiTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function ApiTwoTone(props: IconProps) {
  return <Icon icon={ApiTwoToneSvg} {...props} />
}
