// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ApiOutlinedSvg from '@ant-design/icons-svg/es/asn/ApiOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ApiOutlined(props: IconProps) {
  return <Icon icon={ApiOutlinedSvg} {...props} />
}
