// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AppleFilledSvg from '@ant-design/icons-svg/es/asn/AppleFilled'
import { Icon, type IconProps } from '../components/icon'

export function AppleFilled(props: IconProps) {
  return <Icon icon={AppleFilledSvg} {...props} />
}
