// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AppleOutlinedSvg from '@ant-design/icons-svg/es/asn/AppleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AppleOutlined(props: IconProps) {
  return <Icon icon={AppleOutlinedSvg} {...props} />
}
