// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AppstoreOutlinedSvg from '@ant-design/icons-svg/es/asn/AppstoreOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AppstoreOutlined(props: IconProps) {
  return <Icon icon={AppstoreOutlinedSvg} {...props} />
}
