// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AppstoreFilledSvg from '@ant-design/icons-svg/es/asn/AppstoreFilled'
import { Icon, type IconProps } from '../components/icon'

export function AppstoreFilled(props: IconProps) {
  return <Icon icon={AppstoreFilledSvg} {...props} />
}
