// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AppstoreTwoToneSvg from '@ant-design/icons-svg/es/asn/AppstoreTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function AppstoreTwoTone(props: IconProps) {
  return <Icon icon={AppstoreTwoToneSvg} {...props} />
}
