// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AppstoreAddOutlinedSvg from '@ant-design/icons-svg/es/asn/AppstoreAddOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AppstoreAddOutlined(props: IconProps) {
  return <Icon icon={AppstoreAddOutlinedSvg} {...props} />
}
