// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AreaChartOutlinedSvg from '@ant-design/icons-svg/es/asn/AreaChartOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AreaChartOutlined(props: IconProps) {
  return <Icon icon={AreaChartOutlinedSvg} {...props} />
}
