// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ArrowsAltOutlinedSvg from '@ant-design/icons-svg/es/asn/ArrowsAltOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ArrowsAltOutlined(props: IconProps) {
  return <Icon icon={ArrowsAltOutlinedSvg} {...props} />
}
