// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ArrowRightOutlinedSvg from '@ant-design/icons-svg/es/asn/ArrowRightOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ArrowRightOutlined(props: IconProps) {
  return <Icon icon={ArrowRightOutlinedSvg} {...props} />
}
