// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ArrowUpOutlinedSvg from '@ant-design/icons-svg/es/asn/ArrowUpOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ArrowUpOutlined(props: IconProps) {
  return <Icon icon={ArrowUpOutlinedSvg} {...props} />
}
