// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ArrowDownOutlinedSvg from '@ant-design/icons-svg/es/asn/ArrowDownOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ArrowDownOutlined(props: IconProps) {
  return <Icon icon={ArrowDownOutlinedSvg} {...props} />
}
