// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ArrowLeftOutlinedSvg from '@ant-design/icons-svg/es/asn/ArrowLeftOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ArrowLeftOutlined(props: IconProps) {
  return <Icon icon={ArrowLeftOutlinedSvg} {...props} />
}
