// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AudioMutedOutlinedSvg from '@ant-design/icons-svg/es/asn/AudioMutedOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AudioMutedOutlined(props: IconProps) {
  return <Icon icon={AudioMutedOutlinedSvg} {...props} />
}
