// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AuditOutlinedSvg from '@ant-design/icons-svg/es/asn/AuditOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AuditOutlined(props: IconProps) {
  return <Icon icon={AuditOutlinedSvg} {...props} />
}
