// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AudioFilledSvg from '@ant-design/icons-svg/es/asn/AudioFilled'
import { Icon, type IconProps } from '../components/icon'

export function AudioFilled(props: IconProps) {
  return <Icon icon={AudioFilledSvg} {...props} />
}
