// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AudioTwoToneSvg from '@ant-design/icons-svg/es/asn/AudioTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function AudioTwoTone(props: IconProps) {
  return <Icon icon={AudioTwoToneSvg} {...props} />
}
