// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import AudioOutlinedSvg from '@ant-design/icons-svg/es/asn/AudioOutlined'
import { Icon, type IconProps } from '../components/icon'

export function AudioOutlined(props: IconProps) {
  return <Icon icon={AudioOutlinedSvg} {...props} />
}
