// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BackwardFilledSvg from '@ant-design/icons-svg/es/asn/BackwardFilled'
import { Icon, type IconProps } from '../components/icon'

export function BackwardFilled(props: IconProps) {
  return <Icon icon={BackwardFilledSvg} {...props} />
}
