// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BackwardOutlinedSvg from '@ant-design/icons-svg/es/asn/BackwardOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BackwardOutlined(props: IconProps) {
  return <Icon icon={BackwardOutlinedSvg} {...props} />
}
