// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BaiduOutlinedSvg from '@ant-design/icons-svg/es/asn/BaiduOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BaiduOutlined(props: IconProps) {
  return <Icon icon={BaiduOutlinedSvg} {...props} />
}
