// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BankFilledSvg from '@ant-design/icons-svg/es/asn/BankFilled'
import { Icon, type IconProps } from '../components/icon'

export function BankFilled(props: IconProps) {
  return <Icon icon={BankFilledSvg} {...props} />
}
