// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BankTwoToneSvg from '@ant-design/icons-svg/es/asn/BankTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function BankTwoTone(props: IconProps) {
  return <Icon icon={BankTwoToneSvg} {...props} />
}
