// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BankOutlinedSvg from '@ant-design/icons-svg/es/asn/BankOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BankOutlined(props: IconProps) {
  return <Icon icon={BankOutlinedSvg} {...props} />
}
