// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BarChartOutlinedSvg from '@ant-design/icons-svg/es/asn/BarChartOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BarChartOutlined(props: IconProps) {
  return <Icon icon={BarChartOutlinedSvg} {...props} />
}
