// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BarcodeOutlinedSvg from '@ant-design/icons-svg/es/asn/BarcodeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BarcodeOutlined(props: IconProps) {
  return <Icon icon={BarcodeOutlinedSvg} {...props} />
}
