// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BarsOutlinedSvg from '@ant-design/icons-svg/es/asn/BarsOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BarsOutlined(props: IconProps) {
  return <Icon icon={BarsOutlinedSvg} {...props} />
}
