// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BehanceSquareFilledSvg from '@ant-design/icons-svg/es/asn/BehanceSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function BehanceSquareFilled(props: IconProps) {
  return <Icon icon={BehanceSquareFilledSvg} {...props} />
}
