// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BehanceOutlinedSvg from '@ant-design/icons-svg/es/asn/BehanceOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BehanceOutlined(props: IconProps) {
  return <Icon icon={BehanceOutlinedSvg} {...props} />
}
