// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BehanceCircleFilledSvg from '@ant-design/icons-svg/es/asn/BehanceCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function BehanceCircleFilled(props: IconProps) {
  return <Icon icon={BehanceCircleFilledSvg} {...props} />
}
