// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BehanceSquareOutlinedSvg from '@ant-design/icons-svg/es/asn/BehanceSquareOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BehanceSquareOutlined(props: IconProps) {
  return <Icon icon={BehanceSquareOutlinedSvg} {...props} />
}
