// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BellFilledSvg from '@ant-design/icons-svg/es/asn/BellFilled'
import { Icon, type IconProps } from '../components/icon'

export function BellFilled(props: IconProps) {
  return <Icon icon={BellFilledSvg} {...props} />
}
