// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BellTwoToneSvg from '@ant-design/icons-svg/es/asn/BellTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function BellTwoTone(props: IconProps) {
  return <Icon icon={BellTwoToneSvg} {...props} />
}
