// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BellOutlinedSvg from '@ant-design/icons-svg/es/asn/BellOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BellOutlined(props: IconProps) {
  return <Icon icon={BellOutlinedSvg} {...props} />
}
