// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BgColorsOutlinedSvg from '@ant-design/icons-svg/es/asn/BgColorsOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BgColorsOutlined(props: IconProps) {
  return <Icon icon={BgColorsOutlinedSvg} {...props} />
}
