// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BilibiliOutlinedSvg from '@ant-design/icons-svg/es/asn/BilibiliOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BilibiliOutlined(props: IconProps) {
  return <Icon icon={BilibiliOutlinedSvg} {...props} />
}
