// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BilibiliFilledSvg from '@ant-design/icons-svg/es/asn/BilibiliFilled'
import { Icon, type IconProps } from '../components/icon'

export function BilibiliFilled(props: IconProps) {
  return <Icon icon={BilibiliFilledSvg} {...props} />
}
