// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BlockOutlinedSvg from '@ant-design/icons-svg/es/asn/BlockOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BlockOutlined(props: IconProps) {
  return <Icon icon={BlockOutlinedSvg} {...props} />
}
