// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BoldOutlinedSvg from '@ant-design/icons-svg/es/asn/BoldOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BoldOutlined(props: IconProps) {
  return <Icon icon={BoldOutlinedSvg} {...props} />
}
