// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BookTwoToneSvg from '@ant-design/icons-svg/es/asn/BookTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function BookTwoTone(props: IconProps) {
  return <Icon icon={BookTwoToneSvg} {...props} />
}
