// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BookFilledSvg from '@ant-design/icons-svg/es/asn/BookFilled'
import { Icon, type IconProps } from '../components/icon'

export function BookFilled(props: IconProps) {
  return <Icon icon={BookFilledSvg} {...props} />
}
