// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BookOutlinedSvg from '@ant-design/icons-svg/es/asn/BookOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BookOutlined(props: IconProps) {
  return <Icon icon={BookOutlinedSvg} {...props} />
}
