// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BorderVerticleOutlinedSvg from '@ant-design/icons-svg/es/asn/BorderVerticleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BorderVerticleOutlined(props: IconProps) {
  return <Icon icon={BorderVerticleOutlinedSvg} {...props} />
}
