// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BorderlessTableOutlinedSvg from '@ant-design/icons-svg/es/asn/BorderlessTableOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BorderlessTableOutlined(props: IconProps) {
  return <Icon icon={BorderlessTableOutlinedSvg} {...props} />
}
