// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BorderOuterOutlinedSvg from '@ant-design/icons-svg/es/asn/BorderOuterOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BorderOuterOutlined(props: IconProps) {
  return <Icon icon={BorderOuterOutlinedSvg} {...props} />
}
