// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BorderLeftOutlinedSvg from '@ant-design/icons-svg/es/asn/BorderLeftOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BorderLeftOutlined(props: IconProps) {
  return <Icon icon={BorderLeftOutlinedSvg} {...props} />
}
