// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BorderBottomOutlinedSvg from '@ant-design/icons-svg/es/asn/BorderBottomOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BorderBottomOutlined(props: IconProps) {
  return <Icon icon={BorderBottomOutlinedSvg} {...props} />
}
