// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BorderTopOutlinedSvg from '@ant-design/icons-svg/es/asn/BorderTopOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BorderTopOutlined(props: IconProps) {
  return <Icon icon={BorderTopOutlinedSvg} {...props} />
}
