// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BorderInnerOutlinedSvg from '@ant-design/icons-svg/es/asn/BorderInnerOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BorderInnerOutlined(props: IconProps) {
  return <Icon icon={BorderInnerOutlinedSvg} {...props} />
}
