// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BorderOutlinedSvg from '@ant-design/icons-svg/es/asn/BorderOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BorderOutlined(props: IconProps) {
  return <Icon icon={BorderOutlinedSvg} {...props} />
}
