// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BorderHorizontalOutlinedSvg from '@ant-design/icons-svg/es/asn/BorderHorizontalOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BorderHorizontalOutlined(props: IconProps) {
  return <Icon icon={BorderHorizontalOutlinedSvg} {...props} />
}
