// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BorderRightOutlinedSvg from '@ant-design/icons-svg/es/asn/BorderRightOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BorderRightOutlined(props: IconProps) {
  return <Icon icon={BorderRightOutlinedSvg} {...props} />
}
