// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BoxPlotFilledSvg from '@ant-design/icons-svg/es/asn/BoxPlotFilled'
import { Icon, type IconProps } from '../components/icon'

export function BoxPlotFilled(props: IconProps) {
  return <Icon icon={BoxPlotFilledSvg} {...props} />
}
