// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BoxPlotOutlinedSvg from '@ant-design/icons-svg/es/asn/BoxPlotOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BoxPlotOutlined(props: IconProps) {
  return <Icon icon={BoxPlotOutlinedSvg} {...props} />
}
