// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BoxPlotTwoToneSvg from '@ant-design/icons-svg/es/asn/BoxPlotTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function BoxPlotTwoTone(props: IconProps) {
  return <Icon icon={BoxPlotTwoToneSvg} {...props} />
}
