// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BranchesOutlinedSvg from '@ant-design/icons-svg/es/asn/BranchesOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BranchesOutlined(props: IconProps) {
  return <Icon icon={BranchesOutlinedSvg} {...props} />
}
