// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BugFilledSvg from '@ant-design/icons-svg/es/asn/BugFilled'
import { Icon, type IconProps } from '../components/icon'

export function BugFilled(props: IconProps) {
  return <Icon icon={BugFilledSvg} {...props} />
}
