// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BugOutlinedSvg from '@ant-design/icons-svg/es/asn/BugOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BugOutlined(props: IconProps) {
  return <Icon icon={BugOutlinedSvg} {...props} />
}
