// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BugTwoToneSvg from '@ant-design/icons-svg/es/asn/BugTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function BugTwoTone(props: IconProps) {
  return <Icon icon={BugTwoToneSvg} {...props} />
}
