// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BuildFilledSvg from '@ant-design/icons-svg/es/asn/BuildFilled'
import { Icon, type IconProps } from '../components/icon'

export function BuildFilled(props: IconProps) {
  return <Icon icon={BuildFilledSvg} {...props} />
}
