// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BuildOutlinedSvg from '@ant-design/icons-svg/es/asn/BuildOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BuildOutlined(props: IconProps) {
  return <Icon icon={BuildOutlinedSvg} {...props} />
}
