// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BuildTwoToneSvg from '@ant-design/icons-svg/es/asn/BuildTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function BuildTwoTone(props: IconProps) {
  return <Icon icon={BuildTwoToneSvg} {...props} />
}
