// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BulbTwoToneSvg from '@ant-design/icons-svg/es/asn/BulbTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function BulbTwoTone(props: IconProps) {
  return <Icon icon={BulbTwoToneSvg} {...props} />
}
