// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BulbOutlinedSvg from '@ant-design/icons-svg/es/asn/BulbOutlined'
import { Icon, type IconProps } from '../components/icon'

export function BulbOutlined(props: IconProps) {
  return <Icon icon={BulbOutlinedSvg} {...props} />
}
