// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import BulbFilledSvg from '@ant-design/icons-svg/es/asn/BulbFilled'
import { Icon, type IconProps } from '../components/icon'

export function BulbFilled(props: IconProps) {
  return <Icon icon={BulbFilledSvg} {...props} />
}
