// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CalculatorOutlinedSvg from '@ant-design/icons-svg/es/asn/CalculatorOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CalculatorOutlined(props: IconProps) {
  return <Icon icon={CalculatorOutlinedSvg} {...props} />
}
