// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CalculatorFilledSvg from '@ant-design/icons-svg/es/asn/CalculatorFilled'
import { Icon, type IconProps } from '../components/icon'

export function CalculatorFilled(props: IconProps) {
  return <Icon icon={CalculatorFilledSvg} {...props} />
}
