// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CalendarTwoToneSvg from '@ant-design/icons-svg/es/asn/CalendarTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CalendarTwoTone(props: IconProps) {
  return <Icon icon={CalendarTwoToneSvg} {...props} />
}
