// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CalendarFilledSvg from '@ant-design/icons-svg/es/asn/CalendarFilled'
import { Icon, type IconProps } from '../components/icon'

export function CalendarFilled(props: IconProps) {
  return <Icon icon={CalendarFilledSvg} {...props} />
}
