// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CalendarOutlinedSvg from '@ant-design/icons-svg/es/asn/CalendarOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CalendarOutlined(props: IconProps) {
  return <Icon icon={CalendarOutlinedSvg} {...props} />
}
