// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CameraOutlinedSvg from '@ant-design/icons-svg/es/asn/CameraOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CameraOutlined(props: IconProps) {
  return <Icon icon={CameraOutlinedSvg} {...props} />
}
