// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CameraTwoToneSvg from '@ant-design/icons-svg/es/asn/CameraTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CameraTwoTone(props: IconProps) {
  return <Icon icon={CameraTwoToneSvg} {...props} />
}
