// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CarOutlinedSvg from '@ant-design/icons-svg/es/asn/CarOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CarOutlined(props: IconProps) {
  return <Icon icon={CarOutlinedSvg} {...props} />
}
