// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CarTwoToneSvg from '@ant-design/icons-svg/es/asn/CarTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CarTwoTone(props: IconProps) {
  return <Icon icon={CarTwoToneSvg} {...props} />
}
