// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CarFilledSvg from '@ant-design/icons-svg/es/asn/CarFilled'
import { Icon, type IconProps } from '../components/icon'

export function CarFilled(props: IconProps) {
  return <Icon icon={CarFilledSvg} {...props} />
}
