// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CaretRightOutlinedSvg from '@ant-design/icons-svg/es/asn/CaretRightOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CaretRightOutlined(props: IconProps) {
  return <Icon icon={CaretRightOutlinedSvg} {...props} />
}
