// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CaretDownOutlinedSvg from '@ant-design/icons-svg/es/asn/CaretDownOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CaretDownOutlined(props: IconProps) {
  return <Icon icon={CaretDownOutlinedSvg} {...props} />
}
