// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CaretUpFilledSvg from '@ant-design/icons-svg/es/asn/CaretUpFilled'
import { Icon, type IconProps } from '../components/icon'

export function CaretUpFilled(props: IconProps) {
  return <Icon icon={CaretUpFilledSvg} {...props} />
}
