// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CaretUpOutlinedSvg from '@ant-design/icons-svg/es/asn/CaretUpOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CaretUpOutlined(props: IconProps) {
  return <Icon icon={CaretUpOutlinedSvg} {...props} />
}
