// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CaretLeftFilledSvg from '@ant-design/icons-svg/es/asn/CaretLeftFilled'
import { Icon, type IconProps } from '../components/icon'

export function CaretLeftFilled(props: IconProps) {
  return <Icon icon={CaretLeftFilledSvg} {...props} />
}
