// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CaretRightFilledSvg from '@ant-design/icons-svg/es/asn/CaretRightFilled'
import { Icon, type IconProps } from '../components/icon'

export function CaretRightFilled(props: IconProps) {
  return <Icon icon={CaretRightFilledSvg} {...props} />
}
