// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CaretDownFilledSvg from '@ant-design/icons-svg/es/asn/CaretDownFilled'
import { Icon, type IconProps } from '../components/icon'

export function CaretDownFilled(props: IconProps) {
  return <Icon icon={CaretDownFilledSvg} {...props} />
}
