// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CaretLeftOutlinedSvg from '@ant-design/icons-svg/es/asn/CaretLeftOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CaretLeftOutlined(props: IconProps) {
  return <Icon icon={CaretLeftOutlinedSvg} {...props} />
}
