// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CarryOutTwoToneSvg from '@ant-design/icons-svg/es/asn/CarryOutTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CarryOutTwoTone(props: IconProps) {
  return <Icon icon={CarryOutTwoToneSvg} {...props} />
}
