// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CarryOutOutlinedSvg from '@ant-design/icons-svg/es/asn/CarryOutOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CarryOutOutlined(props: IconProps) {
  return <Icon icon={CarryOutOutlinedSvg} {...props} />
}
