// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CarryOutFilledSvg from '@ant-design/icons-svg/es/asn/CarryOutFilled'
import { Icon, type IconProps } from '../components/icon'

export function CarryOutFilled(props: IconProps) {
  return <Icon icon={CarryOutFilledSvg} {...props} />
}
