// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CheckSquareTwoToneSvg from '@ant-design/icons-svg/es/asn/CheckSquareTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CheckSquareTwoTone(props: IconProps) {
  return <Icon icon={CheckSquareTwoToneSvg} {...props} />
}
