// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CheckCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/CheckCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CheckCircleOutlined(props: IconProps) {
  return <Icon icon={CheckCircleOutlinedSvg} {...props} />
}
