// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CheckSquareOutlinedSvg from '@ant-design/icons-svg/es/asn/CheckSquareOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CheckSquareOutlined(props: IconProps) {
  return <Icon icon={CheckSquareOutlinedSvg} {...props} />
}
