// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CheckCircleFilledSvg from '@ant-design/icons-svg/es/asn/CheckCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function CheckCircleFilled(props: IconProps) {
  return <Icon icon={CheckCircleFilledSvg} {...props} />
}
