// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CheckCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/CheckCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CheckCircleTwoTone(props: IconProps) {
  return <Icon icon={CheckCircleTwoToneSvg} {...props} />
}
