// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CheckOutlinedSvg from '@ant-design/icons-svg/es/asn/CheckOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CheckOutlined(props: IconProps) {
  return <Icon icon={CheckOutlinedSvg} {...props} />
}
