// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CheckSquareFilledSvg from '@ant-design/icons-svg/es/asn/CheckSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function CheckSquareFilled(props: IconProps) {
  return <Icon icon={CheckSquareFilledSvg} {...props} />
}
