// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ChromeFilledSvg from '@ant-design/icons-svg/es/asn/ChromeFilled'
import { Icon, type IconProps } from '../components/icon'

export function ChromeFilled(props: IconProps) {
  return <Icon icon={ChromeFilledSvg} {...props} />
}
