// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ChromeOutlinedSvg from '@ant-design/icons-svg/es/asn/ChromeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ChromeOutlined(props: IconProps) {
  return <Icon icon={ChromeOutlinedSvg} {...props} />
}
