// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CiCircleFilledSvg from '@ant-design/icons-svg/es/asn/CiCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function CiCircleFilled(props: IconProps) {
  return <Icon icon={CiCircleFilledSvg} {...props} />
}
