// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CiCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/CiCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CiCircleTwoTone(props: IconProps) {
  return <Icon icon={CiCircleTwoToneSvg} {...props} />
}
