// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CiCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/CiCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CiCircleOutlined(props: IconProps) {
  return <Icon icon={CiCircleOutlinedSvg} {...props} />
}
