// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CiOutlinedSvg from '@ant-design/icons-svg/es/asn/CiOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CiOutlined(props: IconProps) {
  return <Icon icon={CiOutlinedSvg} {...props} />
}
