// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CiTwoToneSvg from '@ant-design/icons-svg/es/asn/CiTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CiTwoTone(props: IconProps) {
  return <Icon icon={CiTwoToneSvg} {...props} />
}
