// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ClearOutlinedSvg from '@ant-design/icons-svg/es/asn/ClearOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ClearOutlined(props: IconProps) {
  return <Icon icon={ClearOutlinedSvg} {...props} />
}
