// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ClockCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/ClockCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ClockCircleOutlined(props: IconProps) {
  return <Icon icon={ClockCircleOutlinedSvg} {...props} />
}
