// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ClockCircleFilledSvg from '@ant-design/icons-svg/es/asn/ClockCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function ClockCircleFilled(props: IconProps) {
  return <Icon icon={ClockCircleFilledSvg} {...props} />
}
