// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CloseSquareOutlinedSvg from '@ant-design/icons-svg/es/asn/CloseSquareOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CloseSquareOutlined(props: IconProps) {
  return <Icon icon={CloseSquareOutlinedSvg} {...props} />
}
