// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CloseSquareTwoToneSvg from '@ant-design/icons-svg/es/asn/CloseSquareTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CloseSquareTwoTone(props: IconProps) {
  return <Icon icon={CloseSquareTwoToneSvg} {...props} />
}
