// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CloseCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/CloseCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CloseCircleTwoTone(props: IconProps) {
  return <Icon icon={CloseCircleTwoToneSvg} {...props} />
}
