// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CloseCircleFilledSvg from '@ant-design/icons-svg/es/asn/CloseCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function CloseCircleFilled(props: IconProps) {
  return <Icon icon={CloseCircleFilledSvg} {...props} />
}
