// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CloseOutlinedSvg from '@ant-design/icons-svg/es/asn/CloseOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CloseOutlined(props: IconProps) {
  return <Icon icon={CloseOutlinedSvg} {...props} />
}
