// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CloseSquareFilledSvg from '@ant-design/icons-svg/es/asn/CloseSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function CloseSquareFilled(props: IconProps) {
  return <Icon icon={CloseSquareFilledSvg} {...props} />
}
