// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CloseCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/CloseCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CloseCircleOutlined(props: IconProps) {
  return <Icon icon={CloseCircleOutlinedSvg} {...props} />
}
