// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CloudOutlinedSvg from '@ant-design/icons-svg/es/asn/CloudOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CloudOutlined(props: IconProps) {
  return <Icon icon={CloudOutlinedSvg} {...props} />
}
