// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CloudTwoToneSvg from '@ant-design/icons-svg/es/asn/CloudTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CloudTwoTone(props: IconProps) {
  return <Icon icon={CloudTwoToneSvg} {...props} />
}
