// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CloudUploadOutlinedSvg from '@ant-design/icons-svg/es/asn/CloudUploadOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CloudUploadOutlined(props: IconProps) {
  return <Icon icon={CloudUploadOutlinedSvg} {...props} />
}
