// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CloudSyncOutlinedSvg from '@ant-design/icons-svg/es/asn/CloudSyncOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CloudSyncOutlined(props: IconProps) {
  return <Icon icon={CloudSyncOutlinedSvg} {...props} />
}
