// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CloudServerOutlinedSvg from '@ant-design/icons-svg/es/asn/CloudServerOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CloudServerOutlined(props: IconProps) {
  return <Icon icon={CloudServerOutlinedSvg} {...props} />
}
