// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CloudDownloadOutlinedSvg from '@ant-design/icons-svg/es/asn/CloudDownloadOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CloudDownloadOutlined(props: IconProps) {
  return <Icon icon={CloudDownloadOutlinedSvg} {...props} />
}
