// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CloudFilledSvg from '@ant-design/icons-svg/es/asn/CloudFilled'
import { Icon, type IconProps } from '../components/icon'

export function CloudFilled(props: IconProps) {
  return <Icon icon={CloudFilledSvg} {...props} />
}
