// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ClusterOutlinedSvg from '@ant-design/icons-svg/es/asn/ClusterOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ClusterOutlined(props: IconProps) {
  return <Icon icon={ClusterOutlinedSvg} {...props} />
}
