// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CodeTwoToneSvg from '@ant-design/icons-svg/es/asn/CodeTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CodeTwoTone(props: IconProps) {
  return <Icon icon={CodeTwoToneSvg} {...props} />
}
