// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CodepenCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/CodepenCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CodepenCircleOutlined(props: IconProps) {
  return <Icon icon={CodepenCircleOutlinedSvg} {...props} />
}
