// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CodeSandboxCircleFilledSvg from '@ant-design/icons-svg/es/asn/CodeSandboxCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function CodeSandboxCircleFilled(props: IconProps) {
  return <Icon icon={CodeSandboxCircleFilledSvg} {...props} />
}
