// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CodeOutlinedSvg from '@ant-design/icons-svg/es/asn/CodeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CodeOutlined(props: IconProps) {
  return <Icon icon={CodeOutlinedSvg} {...props} />
}
