// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CodepenCircleFilledSvg from '@ant-design/icons-svg/es/asn/CodepenCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function CodepenCircleFilled(props: IconProps) {
  return <Icon icon={CodepenCircleFilledSvg} {...props} />
}
