// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CodeSandboxOutlinedSvg from '@ant-design/icons-svg/es/asn/CodeSandboxOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CodeSandboxOutlined(props: IconProps) {
  return <Icon icon={CodeSandboxOutlinedSvg} {...props} />
}
