// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CodepenSquareFilledSvg from '@ant-design/icons-svg/es/asn/CodepenSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function CodepenSquareFilled(props: IconProps) {
  return <Icon icon={CodepenSquareFilledSvg} {...props} />
}
