// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CodepenOutlinedSvg from '@ant-design/icons-svg/es/asn/CodepenOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CodepenOutlined(props: IconProps) {
  return <Icon icon={CodepenOutlinedSvg} {...props} />
}
