// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CodeSandboxSquareFilledSvg from '@ant-design/icons-svg/es/asn/CodeSandboxSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function CodeSandboxSquareFilled(props: IconProps) {
  return <Icon icon={CodeSandboxSquareFilledSvg} {...props} />
}
