// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CoffeeOutlinedSvg from '@ant-design/icons-svg/es/asn/CoffeeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CoffeeOutlined(props: IconProps) {
  return <Icon icon={CoffeeOutlinedSvg} {...props} />
}
