// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ColumnWidthOutlinedSvg from '@ant-design/icons-svg/es/asn/ColumnWidthOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ColumnWidthOutlined(props: IconProps) {
  return <Icon icon={ColumnWidthOutlinedSvg} {...props} />
}
