// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ColumnHeightOutlinedSvg from '@ant-design/icons-svg/es/asn/ColumnHeightOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ColumnHeightOutlined(props: IconProps) {
  return <Icon icon={ColumnHeightOutlinedSvg} {...props} />
}
