// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CommentOutlinedSvg from '@ant-design/icons-svg/es/asn/CommentOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CommentOutlined(props: IconProps) {
  return <Icon icon={CommentOutlinedSvg} {...props} />
}
