// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CompressOutlinedSvg from '@ant-design/icons-svg/es/asn/CompressOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CompressOutlined(props: IconProps) {
  return <Icon icon={CompressOutlinedSvg} {...props} />
}
