// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CompassTwoToneSvg from '@ant-design/icons-svg/es/asn/CompassTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CompassTwoTone(props: IconProps) {
  return <Icon icon={CompassTwoToneSvg} {...props} />
}
