// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CompassOutlinedSvg from '@ant-design/icons-svg/es/asn/CompassOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CompassOutlined(props: IconProps) {
  return <Icon icon={CompassOutlinedSvg} {...props} />
}
