// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CompassFilledSvg from '@ant-design/icons-svg/es/asn/CompassFilled'
import { Icon, type IconProps } from '../components/icon'

export function CompassFilled(props: IconProps) {
  return <Icon icon={CompassFilledSvg} {...props} />
}
