// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ConsoleSqlOutlinedSvg from '@ant-design/icons-svg/es/asn/ConsoleSqlOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ConsoleSqlOutlined(props: IconProps) {
  return <Icon icon={ConsoleSqlOutlinedSvg} {...props} />
}
