// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ContactsFilledSvg from '@ant-design/icons-svg/es/asn/ContactsFilled'
import { Icon, type IconProps } from '../components/icon'

export function ContactsFilled(props: IconProps) {
  return <Icon icon={ContactsFilledSvg} {...props} />
}
