// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ContainerOutlinedSvg from '@ant-design/icons-svg/es/asn/ContainerOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ContainerOutlined(props: IconProps) {
  return <Icon icon={ContainerOutlinedSvg} {...props} />
}
