// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ContainerFilledSvg from '@ant-design/icons-svg/es/asn/ContainerFilled'
import { Icon, type IconProps } from '../components/icon'

export function ContainerFilled(props: IconProps) {
  return <Icon icon={ContainerFilledSvg} {...props} />
}
