// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ControlFilledSvg from '@ant-design/icons-svg/es/asn/ControlFilled'
import { Icon, type IconProps } from '../components/icon'

export function ControlFilled(props: IconProps) {
  return <Icon icon={ControlFilledSvg} {...props} />
}
