// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ControlOutlinedSvg from '@ant-design/icons-svg/es/asn/ControlOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ControlOutlined(props: IconProps) {
  return <Icon icon={ControlOutlinedSvg} {...props} />
}
