// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ControlTwoToneSvg from '@ant-design/icons-svg/es/asn/ControlTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function ControlTwoTone(props: IconProps) {
  return <Icon icon={ControlTwoToneSvg} {...props} />
}
