// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ContainerTwoToneSvg from '@ant-design/icons-svg/es/asn/ContainerTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function ContainerTwoTone(props: IconProps) {
  return <Icon icon={ContainerTwoToneSvg} {...props} />
}
