// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ContactsOutlinedSvg from '@ant-design/icons-svg/es/asn/ContactsOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ContactsOutlined(props: IconProps) {
  return <Icon icon={ContactsOutlinedSvg} {...props} />
}
