// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ContactsTwoToneSvg from '@ant-design/icons-svg/es/asn/ContactsTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function ContactsTwoTone(props: IconProps) {
  return <Icon icon={ContactsTwoToneSvg} {...props} />
}
