// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CopyOutlinedSvg from '@ant-design/icons-svg/es/asn/CopyOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CopyOutlined(props: IconProps) {
  return <Icon icon={CopyOutlinedSvg} {...props} />
}
