// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CopyrightCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/CopyrightCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CopyrightCircleOutlined(props: IconProps) {
  return <Icon icon={CopyrightCircleOutlinedSvg} {...props} />
}
