// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CopyrightTwoToneSvg from '@ant-design/icons-svg/es/asn/CopyrightTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CopyrightTwoTone(props: IconProps) {
  return <Icon icon={CopyrightTwoToneSvg} {...props} />
}
