// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CopyrightCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/CopyrightCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CopyrightCircleTwoTone(props: IconProps) {
  return <Icon icon={CopyrightCircleTwoToneSvg} {...props} />
}
