// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CopyFilledSvg from '@ant-design/icons-svg/es/asn/CopyFilled'
import { Icon, type IconProps } from '../components/icon'

export function CopyFilled(props: IconProps) {
  return <Icon icon={CopyFilledSvg} {...props} />
}
