// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CopyrightCircleFilledSvg from '@ant-design/icons-svg/es/asn/CopyrightCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function CopyrightCircleFilled(props: IconProps) {
  return <Icon icon={CopyrightCircleFilledSvg} {...props} />
}
