// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CopyTwoToneSvg from '@ant-design/icons-svg/es/asn/CopyTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CopyTwoTone(props: IconProps) {
  return <Icon icon={CopyTwoToneSvg} {...props} />
}
