// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CreditCardTwoToneSvg from '@ant-design/icons-svg/es/asn/CreditCardTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CreditCardTwoTone(props: IconProps) {
  return <Icon icon={CreditCardTwoToneSvg} {...props} />
}
