// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CreditCardFilledSvg from '@ant-design/icons-svg/es/asn/CreditCardFilled'
import { Icon, type IconProps } from '../components/icon'

export function CreditCardFilled(props: IconProps) {
  return <Icon icon={CreditCardFilledSvg} {...props} />
}
