// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CreditCardOutlinedSvg from '@ant-design/icons-svg/es/asn/CreditCardOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CreditCardOutlined(props: IconProps) {
  return <Icon icon={CreditCardOutlinedSvg} {...props} />
}
