// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CrownOutlinedSvg from '@ant-design/icons-svg/es/asn/CrownOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CrownOutlined(props: IconProps) {
  return <Icon icon={CrownOutlinedSvg} {...props} />
}
