// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CrownTwoToneSvg from '@ant-design/icons-svg/es/asn/CrownTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CrownTwoTone(props: IconProps) {
  return <Icon icon={CrownTwoToneSvg} {...props} />
}
