// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CrownFilledSvg from '@ant-design/icons-svg/es/asn/CrownFilled'
import { Icon, type IconProps } from '../components/icon'

export function CrownFilled(props: IconProps) {
  return <Icon icon={CrownFilledSvg} {...props} />
}
