// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CustomerServiceFilledSvg from '@ant-design/icons-svg/es/asn/CustomerServiceFilled'
import { Icon, type IconProps } from '../components/icon'

export function CustomerServiceFilled(props: IconProps) {
  return <Icon icon={CustomerServiceFilledSvg} {...props} />
}
