// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CustomerServiceOutlinedSvg from '@ant-design/icons-svg/es/asn/CustomerServiceOutlined'
import { Icon, type IconProps } from '../components/icon'

export function CustomerServiceOutlined(props: IconProps) {
  return <Icon icon={CustomerServiceOutlinedSvg} {...props} />
}
