// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import CustomerServiceTwoToneSvg from '@ant-design/icons-svg/es/asn/CustomerServiceTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function CustomerServiceTwoTone(props: IconProps) {
  return <Icon icon={CustomerServiceTwoToneSvg} {...props} />
}
