// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DashboardFilledSvg from '@ant-design/icons-svg/es/asn/DashboardFilled'
import { Icon, type IconProps } from '../components/icon'

export function DashboardFilled(props: IconProps) {
  return <Icon icon={DashboardFilledSvg} {...props} />
}
