// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DashboardOutlinedSvg from '@ant-design/icons-svg/es/asn/DashboardOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DashboardOutlined(props: IconProps) {
  return <Icon icon={DashboardOutlinedSvg} {...props} />
}
