// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DashOutlinedSvg from '@ant-design/icons-svg/es/asn/DashOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DashOutlined(props: IconProps) {
  return <Icon icon={DashOutlinedSvg} {...props} />
}
