// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DatabaseTwoToneSvg from '@ant-design/icons-svg/es/asn/DatabaseTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function DatabaseTwoTone(props: IconProps) {
  return <Icon icon={DatabaseTwoToneSvg} {...props} />
}
