// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DatabaseOutlinedSvg from '@ant-design/icons-svg/es/asn/DatabaseOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DatabaseOutlined(props: IconProps) {
  return <Icon icon={DatabaseOutlinedSvg} {...props} />
}
