// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DatabaseFilledSvg from '@ant-design/icons-svg/es/asn/DatabaseFilled'
import { Icon, type IconProps } from '../components/icon'

export function DatabaseFilled(props: IconProps) {
  return <Icon icon={DatabaseFilledSvg} {...props} />
}
