// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DeleteTwoToneSvg from '@ant-design/icons-svg/es/asn/DeleteTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function DeleteTwoTone(props: IconProps) {
  return <Icon icon={DeleteTwoToneSvg} {...props} />
}
