// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DeleteColumnOutlinedSvg from '@ant-design/icons-svg/es/asn/DeleteColumnOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DeleteColumnOutlined(props: IconProps) {
  return <Icon icon={DeleteColumnOutlinedSvg} {...props} />
}
