// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DeleteFilledSvg from '@ant-design/icons-svg/es/asn/DeleteFilled'
import { Icon, type IconProps } from '../components/icon'

export function DeleteFilled(props: IconProps) {
  return <Icon icon={DeleteFilledSvg} {...props} />
}
