// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DeleteRowOutlinedSvg from '@ant-design/icons-svg/es/asn/DeleteRowOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DeleteRowOutlined(props: IconProps) {
  return <Icon icon={DeleteRowOutlinedSvg} {...props} />
}
