// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DeleteOutlinedSvg from '@ant-design/icons-svg/es/asn/DeleteOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DeleteOutlined(props: IconProps) {
  return <Icon icon={DeleteOutlinedSvg} {...props} />
}
