// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DeliveredProcedureOutlinedSvg from '@ant-design/icons-svg/es/asn/DeliveredProcedureOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DeliveredProcedureOutlined(props: IconProps) {
  return <Icon icon={DeliveredProcedureOutlinedSvg} {...props} />
}
