// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DeploymentUnitOutlinedSvg from '@ant-design/icons-svg/es/asn/DeploymentUnitOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DeploymentUnitOutlined(props: IconProps) {
  return <Icon icon={DeploymentUnitOutlinedSvg} {...props} />
}
