// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DesktopOutlinedSvg from '@ant-design/icons-svg/es/asn/DesktopOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DesktopOutlined(props: IconProps) {
  return <Icon icon={DesktopOutlinedSvg} {...props} />
}
