// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DiffOutlinedSvg from '@ant-design/icons-svg/es/asn/DiffOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DiffOutlined(props: IconProps) {
  return <Icon icon={DiffOutlinedSvg} {...props} />
}
