// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DiffFilledSvg from '@ant-design/icons-svg/es/asn/DiffFilled'
import { Icon, type IconProps } from '../components/icon'

export function DiffFilled(props: IconProps) {
  return <Icon icon={DiffFilledSvg} {...props} />
}
