// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DiffTwoToneSvg from '@ant-design/icons-svg/es/asn/DiffTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function DiffTwoTone(props: IconProps) {
  return <Icon icon={DiffTwoToneSvg} {...props} />
}
