// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DingtalkSquareFilledSvg from '@ant-design/icons-svg/es/asn/DingtalkSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function DingtalkSquareFilled(props: IconProps) {
  return <Icon icon={DingtalkSquareFilledSvg} {...props} />
}
