// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DingtalkCircleFilledSvg from '@ant-design/icons-svg/es/asn/DingtalkCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function DingtalkCircleFilled(props: IconProps) {
  return <Icon icon={DingtalkCircleFilledSvg} {...props} />
}
