// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DingtalkOutlinedSvg from '@ant-design/icons-svg/es/asn/DingtalkOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DingtalkOutlined(props: IconProps) {
  return <Icon icon={DingtalkOutlinedSvg} {...props} />
}
