// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DingdingOutlinedSvg from '@ant-design/icons-svg/es/asn/DingdingOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DingdingOutlined(props: IconProps) {
  return <Icon icon={DingdingOutlinedSvg} {...props} />
}
