// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DiscordOutlinedSvg from '@ant-design/icons-svg/es/asn/DiscordOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DiscordOutlined(props: IconProps) {
  return <Icon icon={DiscordOutlinedSvg} {...props} />
}
