// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DiscordFilledSvg from '@ant-design/icons-svg/es/asn/DiscordFilled'
import { Icon, type IconProps } from '../components/icon'

export function DiscordFilled(props: IconProps) {
  return <Icon icon={DiscordFilledSvg} {...props} />
}
