// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DisconnectOutlinedSvg from '@ant-design/icons-svg/es/asn/DisconnectOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DisconnectOutlined(props: IconProps) {
  return <Icon icon={DisconnectOutlinedSvg} {...props} />
}
