// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DislikeFilledSvg from '@ant-design/icons-svg/es/asn/DislikeFilled'
import { Icon, type IconProps } from '../components/icon'

export function DislikeFilled(props: IconProps) {
  return <Icon icon={DislikeFilledSvg} {...props} />
}
