// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DislikeTwoToneSvg from '@ant-design/icons-svg/es/asn/DislikeTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function DislikeTwoTone(props: IconProps) {
  return <Icon icon={DislikeTwoToneSvg} {...props} />
}
