// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DislikeOutlinedSvg from '@ant-design/icons-svg/es/asn/DislikeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DislikeOutlined(props: IconProps) {
  return <Icon icon={DislikeOutlinedSvg} {...props} />
}
