// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DockerOutlinedSvg from '@ant-design/icons-svg/es/asn/DockerOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DockerOutlined(props: IconProps) {
  return <Icon icon={DockerOutlinedSvg} {...props} />
}
