// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DollarCircleFilledSvg from '@ant-design/icons-svg/es/asn/DollarCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function DollarCircleFilled(props: IconProps) {
  return <Icon icon={DollarCircleFilledSvg} {...props} />
}
