// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DollarCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/DollarCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DollarCircleOutlined(props: IconProps) {
  return <Icon icon={DollarCircleOutlinedSvg} {...props} />
}
