// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DollarTwoToneSvg from '@ant-design/icons-svg/es/asn/DollarTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function DollarTwoTone(props: IconProps) {
  return <Icon icon={DollarTwoToneSvg} {...props} />
}
