// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DollarOutlinedSvg from '@ant-design/icons-svg/es/asn/DollarOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DollarOutlined(props: IconProps) {
  return <Icon icon={DollarOutlinedSvg} {...props} />
}
