// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DollarCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/DollarCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function DollarCircleTwoTone(props: IconProps) {
  return <Icon icon={DollarCircleTwoToneSvg} {...props} />
}
