// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DotChartOutlinedSvg from '@ant-design/icons-svg/es/asn/DotChartOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DotChartOutlined(props: IconProps) {
  return <Icon icon={DotChartOutlinedSvg} {...props} />
}
