// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DotNetOutlinedSvg from '@ant-design/icons-svg/es/asn/DotNetOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DotNetOutlined(props: IconProps) {
  return <Icon icon={DotNetOutlinedSvg} {...props} />
}
