// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DoubleRightOutlinedSvg from '@ant-design/icons-svg/es/asn/DoubleRightOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DoubleRightOutlined(props: IconProps) {
  return <Icon icon={DoubleRightOutlinedSvg} {...props} />
}
