// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DoubleLeftOutlinedSvg from '@ant-design/icons-svg/es/asn/DoubleLeftOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DoubleLeftOutlined(props: IconProps) {
  return <Icon icon={DoubleLeftOutlinedSvg} {...props} />
}
