// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DownOutlinedSvg from '@ant-design/icons-svg/es/asn/DownOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DownOutlined(props: IconProps) {
  return <Icon icon={DownOutlinedSvg} {...props} />
}
