// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DownSquareTwoToneSvg from '@ant-design/icons-svg/es/asn/DownSquareTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function DownSquareTwoTone(props: IconProps) {
  return <Icon icon={DownSquareTwoToneSvg} {...props} />
}
