// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DownloadOutlinedSvg from '@ant-design/icons-svg/es/asn/DownloadOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DownloadOutlined(props: IconProps) {
  return <Icon icon={DownloadOutlinedSvg} {...props} />
}
