// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DownCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/DownCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DownCircleOutlined(props: IconProps) {
  return <Icon icon={DownCircleOutlinedSvg} {...props} />
}
