// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DownCircleFilledSvg from '@ant-design/icons-svg/es/asn/DownCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function DownCircleFilled(props: IconProps) {
  return <Icon icon={DownCircleFilledSvg} {...props} />
}
