// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DownCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/DownCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function DownCircleTwoTone(props: IconProps) {
  return <Icon icon={DownCircleTwoToneSvg} {...props} />
}
