// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DownSquareFilledSvg from '@ant-design/icons-svg/es/asn/DownSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function DownSquareFilled(props: IconProps) {
  return <Icon icon={DownSquareFilledSvg} {...props} />
}
