// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DownSquareOutlinedSvg from '@ant-design/icons-svg/es/asn/DownSquareOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DownSquareOutlined(props: IconProps) {
  return <Icon icon={DownSquareOutlinedSvg} {...props} />
}
