// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DragOutlinedSvg from '@ant-design/icons-svg/es/asn/DragOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DragOutlined(props: IconProps) {
  return <Icon icon={DragOutlinedSvg} {...props} />
}
