// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DribbbleSquareFilledSvg from '@ant-design/icons-svg/es/asn/DribbbleSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function DribbbleSquareFilled(props: IconProps) {
  return <Icon icon={DribbbleSquareFilledSvg} {...props} />
}
