// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DribbbleSquareOutlinedSvg from '@ant-design/icons-svg/es/asn/DribbbleSquareOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DribbbleSquareOutlined(props: IconProps) {
  return <Icon icon={DribbbleSquareOutlinedSvg} {...props} />
}
