// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DribbbleCircleFilledSvg from '@ant-design/icons-svg/es/asn/DribbbleCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function DribbbleCircleFilled(props: IconProps) {
  return <Icon icon={DribbbleCircleFilledSvg} {...props} />
}
