// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DribbbleOutlinedSvg from '@ant-design/icons-svg/es/asn/DribbbleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DribbbleOutlined(props: IconProps) {
  return <Icon icon={DribbbleOutlinedSvg} {...props} />
}
