// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DropboxCircleFilledSvg from '@ant-design/icons-svg/es/asn/DropboxCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function DropboxCircleFilled(props: IconProps) {
  return <Icon icon={DropboxCircleFilledSvg} {...props} />
}
