// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DropboxSquareFilledSvg from '@ant-design/icons-svg/es/asn/DropboxSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function DropboxSquareFilled(props: IconProps) {
  return <Icon icon={DropboxSquareFilledSvg} {...props} />
}
