// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import DropboxOutlinedSvg from '@ant-design/icons-svg/es/asn/DropboxOutlined'
import { Icon, type IconProps } from '../components/icon'

export function DropboxOutlined(props: IconProps) {
  return <Icon icon={DropboxOutlinedSvg} {...props} />
}
