// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EditFilledSvg from '@ant-design/icons-svg/es/asn/EditFilled'
import { Icon, type IconProps } from '../components/icon'

export function EditFilled(props: IconProps) {
  return <Icon icon={EditFilledSvg} {...props} />
}
