// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EditOutlinedSvg from '@ant-design/icons-svg/es/asn/EditOutlined'
import { Icon, type IconProps } from '../components/icon'

export function EditOutlined(props: IconProps) {
  return <Icon icon={EditOutlinedSvg} {...props} />
}
