// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EditTwoToneSvg from '@ant-design/icons-svg/es/asn/EditTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function EditTwoTone(props: IconProps) {
  return <Icon icon={EditTwoToneSvg} {...props} />
}
