// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EllipsisOutlinedSvg from '@ant-design/icons-svg/es/asn/EllipsisOutlined'
import { Icon, type IconProps } from '../components/icon'

export function EllipsisOutlined(props: IconProps) {
  return <Icon icon={EllipsisOutlinedSvg} {...props} />
}
