// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EnterOutlinedSvg from '@ant-design/icons-svg/es/asn/EnterOutlined'
import { Icon, type IconProps } from '../components/icon'

export function EnterOutlined(props: IconProps) {
  return <Icon icon={EnterOutlinedSvg} {...props} />
}
