// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EnvironmentOutlinedSvg from '@ant-design/icons-svg/es/asn/EnvironmentOutlined'
import { Icon, type IconProps } from '../components/icon'

export function EnvironmentOutlined(props: IconProps) {
  return <Icon icon={EnvironmentOutlinedSvg} {...props} />
}
