// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EnvironmentFilledSvg from '@ant-design/icons-svg/es/asn/EnvironmentFilled'
import { Icon, type IconProps } from '../components/icon'

export function EnvironmentFilled(props: IconProps) {
  return <Icon icon={EnvironmentFilledSvg} {...props} />
}
