// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EnvironmentTwoToneSvg from '@ant-design/icons-svg/es/asn/EnvironmentTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function EnvironmentTwoTone(props: IconProps) {
  return <Icon icon={EnvironmentTwoToneSvg} {...props} />
}
