// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EuroCircleFilledSvg from '@ant-design/icons-svg/es/asn/EuroCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function EuroCircleFilled(props: IconProps) {
  return <Icon icon={EuroCircleFilledSvg} {...props} />
}
