// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EuroCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/EuroCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function EuroCircleTwoTone(props: IconProps) {
  return <Icon icon={EuroCircleTwoToneSvg} {...props} />
}
