// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EuroCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/EuroCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function EuroCircleOutlined(props: IconProps) {
  return <Icon icon={EuroCircleOutlinedSvg} {...props} />
}
