// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EuroTwoToneSvg from '@ant-design/icons-svg/es/asn/EuroTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function EuroTwoTone(props: IconProps) {
  return <Icon icon={EuroTwoToneSvg} {...props} />
}
