// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EuroOutlinedSvg from '@ant-design/icons-svg/es/asn/EuroOutlined'
import { Icon, type IconProps } from '../components/icon'

export function EuroOutlined(props: IconProps) {
  return <Icon icon={EuroOutlinedSvg} {...props} />
}
