// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ExceptionOutlinedSvg from '@ant-design/icons-svg/es/asn/ExceptionOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ExceptionOutlined(props: IconProps) {
  return <Icon icon={ExceptionOutlinedSvg} {...props} />
}
