// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ExclamationCircleFilledSvg from '@ant-design/icons-svg/es/asn/ExclamationCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function ExclamationCircleFilled(props: IconProps) {
  return <Icon icon={ExclamationCircleFilledSvg} {...props} />
}
