// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ExclamationOutlinedSvg from '@ant-design/icons-svg/es/asn/ExclamationOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ExclamationOutlined(props: IconProps) {
  return <Icon icon={ExclamationOutlinedSvg} {...props} />
}
