// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ExclamationCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/ExclamationCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function ExclamationCircleTwoTone(props: IconProps) {
  return <Icon icon={ExclamationCircleTwoToneSvg} {...props} />
}
