// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ExclamationCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/ExclamationCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ExclamationCircleOutlined(props: IconProps) {
  return <Icon icon={ExclamationCircleOutlinedSvg} {...props} />
}
