// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ExpandOutlinedSvg from '@ant-design/icons-svg/es/asn/ExpandOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ExpandOutlined(props: IconProps) {
  return <Icon icon={ExpandOutlinedSvg} {...props} />
}
