// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ExpandAltOutlinedSvg from '@ant-design/icons-svg/es/asn/ExpandAltOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ExpandAltOutlined(props: IconProps) {
  return <Icon icon={ExpandAltOutlinedSvg} {...props} />
}
