// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ExportOutlinedSvg from '@ant-design/icons-svg/es/asn/ExportOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ExportOutlined(props: IconProps) {
  return <Icon icon={ExportOutlinedSvg} {...props} />
}
