// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EyeInvisibleFilledSvg from '@ant-design/icons-svg/es/asn/EyeInvisibleFilled'
import { Icon, type IconProps } from '../components/icon'

export function EyeInvisibleFilled(props: IconProps) {
  return <Icon icon={EyeInvisibleFilledSvg} {...props} />
}
