// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EyeInvisibleTwoToneSvg from '@ant-design/icons-svg/es/asn/EyeInvisibleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function EyeInvisibleTwoTone(props: IconProps) {
  return <Icon icon={EyeInvisibleTwoToneSvg} {...props} />
}
