// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EyeTwoToneSvg from '@ant-design/icons-svg/es/asn/EyeTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function EyeTwoTone(props: IconProps) {
  return <Icon icon={EyeTwoToneSvg} {...props} />
}
