// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EyeFilledSvg from '@ant-design/icons-svg/es/asn/EyeFilled'
import { Icon, type IconProps } from '../components/icon'

export function EyeFilled(props: IconProps) {
  return <Icon icon={EyeFilledSvg} {...props} />
}
