// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EyeOutlinedSvg from '@ant-design/icons-svg/es/asn/EyeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function EyeOutlined(props: IconProps) {
  return <Icon icon={EyeOutlinedSvg} {...props} />
}
