// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import EyeInvisibleOutlinedSvg from '@ant-design/icons-svg/es/asn/EyeInvisibleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function EyeInvisibleOutlined(props: IconProps) {
  return <Icon icon={EyeInvisibleOutlinedSvg} {...props} />
}
