// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FacebookFilledSvg from '@ant-design/icons-svg/es/asn/FacebookFilled'
import { Icon, type IconProps } from '../components/icon'

export function FacebookFilled(props: IconProps) {
  return <Icon icon={FacebookFilledSvg} {...props} />
}
