// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FacebookOutlinedSvg from '@ant-design/icons-svg/es/asn/FacebookOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FacebookOutlined(props: IconProps) {
  return <Icon icon={FacebookOutlinedSvg} {...props} />
}
