// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FallOutlinedSvg from '@ant-design/icons-svg/es/asn/FallOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FallOutlined(props: IconProps) {
  return <Icon icon={FallOutlinedSvg} {...props} />
}
