// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FastBackwardOutlinedSvg from '@ant-design/icons-svg/es/asn/FastBackwardOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FastBackwardOutlined(props: IconProps) {
  return <Icon icon={FastBackwardOutlinedSvg} {...props} />
}
