// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FastForwardFilledSvg from '@ant-design/icons-svg/es/asn/FastForwardFilled'
import { Icon, type IconProps } from '../components/icon'

export function FastForwardFilled(props: IconProps) {
  return <Icon icon={FastForwardFilledSvg} {...props} />
}
