// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FastBackwardFilledSvg from '@ant-design/icons-svg/es/asn/FastBackwardFilled'
import { Icon, type IconProps } from '../components/icon'

export function FastBackwardFilled(props: IconProps) {
  return <Icon icon={FastBackwardFilledSvg} {...props} />
}
