// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FastForwardOutlinedSvg from '@ant-design/icons-svg/es/asn/FastForwardOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FastForwardOutlined(props: IconProps) {
  return <Icon icon={FastForwardOutlinedSvg} {...props} />
}
