// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FieldStringOutlinedSvg from '@ant-design/icons-svg/es/asn/FieldStringOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FieldStringOutlined(props: IconProps) {
  return <Icon icon={FieldStringOutlinedSvg} {...props} />
}
