// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FieldBinaryOutlinedSvg from '@ant-design/icons-svg/es/asn/FieldBinaryOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FieldBinaryOutlined(props: IconProps) {
  return <Icon icon={FieldBinaryOutlinedSvg} {...props} />
}
