// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FieldNumberOutlinedSvg from '@ant-design/icons-svg/es/asn/FieldNumberOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FieldNumberOutlined(props: IconProps) {
  return <Icon icon={FieldNumberOutlinedSvg} {...props} />
}
