// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FieldTimeOutlinedSvg from '@ant-design/icons-svg/es/asn/FieldTimeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FieldTimeOutlined(props: IconProps) {
  return <Icon icon={FieldTimeOutlinedSvg} {...props} />
}
