// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FilePptTwoToneSvg from '@ant-design/icons-svg/es/asn/FilePptTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FilePptTwoTone(props: IconProps) {
  return <Icon icon={FilePptTwoToneSvg} {...props} />
}
