// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileWordFilledSvg from '@ant-design/icons-svg/es/asn/FileWordFilled'
import { Icon, type IconProps } from '../components/icon'

export function FileWordFilled(props: IconProps) {
  return <Icon icon={FileWordFilledSvg} {...props} />
}
