// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileExcelOutlinedSvg from '@ant-design/icons-svg/es/asn/FileExcelOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FileExcelOutlined(props: IconProps) {
  return <Icon icon={FileExcelOutlinedSvg} {...props} />
}
