// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileSyncOutlinedSvg from '@ant-design/icons-svg/es/asn/FileSyncOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FileSyncOutlined(props: IconProps) {
  return <Icon icon={FileSyncOutlinedSvg} {...props} />
}
