// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileImageTwoToneSvg from '@ant-design/icons-svg/es/asn/FileImageTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FileImageTwoTone(props: IconProps) {
  return <Icon icon={FileImageTwoToneSvg} {...props} />
}
