// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileTextTwoToneSvg from '@ant-design/icons-svg/es/asn/FileTextTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FileTextTwoTone(props: IconProps) {
  return <Icon icon={FileTextTwoToneSvg} {...props} />
}
