// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileExcelTwoToneSvg from '@ant-design/icons-svg/es/asn/FileExcelTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FileExcelTwoTone(props: IconProps) {
  return <Icon icon={FileExcelTwoToneSvg} {...props} />
}
