// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileMarkdownFilledSvg from '@ant-design/icons-svg/es/asn/FileMarkdownFilled'
import { Icon, type IconProps } from '../components/icon'

export function FileMarkdownFilled(props: IconProps) {
  return <Icon icon={FileMarkdownFilledSvg} {...props} />
}
