// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileImageFilledSvg from '@ant-design/icons-svg/es/asn/FileImageFilled'
import { Icon, type IconProps } from '../components/icon'

export function FileImageFilled(props: IconProps) {
  return <Icon icon={FileImageFilledSvg} {...props} />
}
