// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileZipFilledSvg from '@ant-design/icons-svg/es/asn/FileZipFilled'
import { Icon, type IconProps } from '../components/icon'

export function FileZipFilled(props: IconProps) {
  return <Icon icon={FileZipFilledSvg} {...props} />
}
