// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileExcelFilledSvg from '@ant-design/icons-svg/es/asn/FileExcelFilled'
import { Icon, type IconProps } from '../components/icon'

export function FileExcelFilled(props: IconProps) {
  return <Icon icon={FileExcelFilledSvg} {...props} />
}
