// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FilePptOutlinedSvg from '@ant-design/icons-svg/es/asn/FilePptOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FilePptOutlined(props: IconProps) {
  return <Icon icon={FilePptOutlinedSvg} {...props} />
}
