// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileFilledSvg from '@ant-design/icons-svg/es/asn/FileFilled'
import { Icon, type IconProps } from '../components/icon'

export function FileFilled(props: IconProps) {
  return <Icon icon={FileFilledSvg} {...props} />
}
