// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileGifOutlinedSvg from '@ant-design/icons-svg/es/asn/FileGifOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FileGifOutlined(props: IconProps) {
  return <Icon icon={FileGifOutlinedSvg} {...props} />
}
