// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileWordOutlinedSvg from '@ant-design/icons-svg/es/asn/FileWordOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FileWordOutlined(props: IconProps) {
  return <Icon icon={FileWordOutlinedSvg} {...props} />
}
