// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileTextOutlinedSvg from '@ant-design/icons-svg/es/asn/FileTextOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FileTextOutlined(props: IconProps) {
  return <Icon icon={FileTextOutlinedSvg} {...props} />
}
