// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileMarkdownTwoToneSvg from '@ant-design/icons-svg/es/asn/FileMarkdownTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FileMarkdownTwoTone(props: IconProps) {
  return <Icon icon={FileMarkdownTwoToneSvg} {...props} />
}
