// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileJpgOutlinedSvg from '@ant-design/icons-svg/es/asn/FileJpgOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FileJpgOutlined(props: IconProps) {
  return <Icon icon={FileJpgOutlinedSvg} {...props} />
}
