// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileUnknownFilledSvg from '@ant-design/icons-svg/es/asn/FileUnknownFilled'
import { Icon, type IconProps } from '../components/icon'

export function FileUnknownFilled(props: IconProps) {
  return <Icon icon={FileUnknownFilledSvg} {...props} />
}
