// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileWordTwoToneSvg from '@ant-design/icons-svg/es/asn/FileWordTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FileWordTwoTone(props: IconProps) {
  return <Icon icon={FileWordTwoToneSvg} {...props} />
}
