// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileExclamationOutlinedSvg from '@ant-design/icons-svg/es/asn/FileExclamationOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FileExclamationOutlined(props: IconProps) {
  return <Icon icon={FileExclamationOutlinedSvg} {...props} />
}
