// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileAddFilledSvg from '@ant-design/icons-svg/es/asn/FileAddFilled'
import { Icon, type IconProps } from '../components/icon'

export function FileAddFilled(props: IconProps) {
  return <Icon icon={FileAddFilledSvg} {...props} />
}
