// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FilePdfFilledSvg from '@ant-design/icons-svg/es/asn/FilePdfFilled'
import { Icon, type IconProps } from '../components/icon'

export function FilePdfFilled(props: IconProps) {
  return <Icon icon={FilePdfFilledSvg} {...props} />
}
