// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileZipOutlinedSvg from '@ant-design/icons-svg/es/asn/FileZipOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FileZipOutlined(props: IconProps) {
  return <Icon icon={FileZipOutlinedSvg} {...props} />
}
