// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileTextFilledSvg from '@ant-design/icons-svg/es/asn/FileTextFilled'
import { Icon, type IconProps } from '../components/icon'

export function FileTextFilled(props: IconProps) {
  return <Icon icon={FileTextFilledSvg} {...props} />
}
