// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileMarkdownOutlinedSvg from '@ant-design/icons-svg/es/asn/FileMarkdownOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FileMarkdownOutlined(props: IconProps) {
  return <Icon icon={FileMarkdownOutlinedSvg} {...props} />
}
