// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileTwoToneSvg from '@ant-design/icons-svg/es/asn/FileTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FileTwoTone(props: IconProps) {
  return <Icon icon={FileTwoToneSvg} {...props} />
}
