// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileOutlinedSvg from '@ant-design/icons-svg/es/asn/FileOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FileOutlined(props: IconProps) {
  return <Icon icon={FileOutlinedSvg} {...props} />
}
