// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileAddOutlinedSvg from '@ant-design/icons-svg/es/asn/FileAddOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FileAddOutlined(props: IconProps) {
  return <Icon icon={FileAddOutlinedSvg} {...props} />
}
