// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileDoneOutlinedSvg from '@ant-design/icons-svg/es/asn/FileDoneOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FileDoneOutlined(props: IconProps) {
  return <Icon icon={FileDoneOutlinedSvg} {...props} />
}
