// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileAddTwoToneSvg from '@ant-design/icons-svg/es/asn/FileAddTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FileAddTwoTone(props: IconProps) {
  return <Icon icon={FileAddTwoToneSvg} {...props} />
}
