// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileSearchOutlinedSvg from '@ant-design/icons-svg/es/asn/FileSearchOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FileSearchOutlined(props: IconProps) {
  return <Icon icon={FileSearchOutlinedSvg} {...props} />
}
