// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileUnknownOutlinedSvg from '@ant-design/icons-svg/es/asn/FileUnknownOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FileUnknownOutlined(props: IconProps) {
  return <Icon icon={FileUnknownOutlinedSvg} {...props} />
}
