// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileExclamationFilledSvg from '@ant-design/icons-svg/es/asn/FileExclamationFilled'
import { Icon, type IconProps } from '../components/icon'

export function FileExclamationFilled(props: IconProps) {
  return <Icon icon={FileExclamationFilledSvg} {...props} />
}
