// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FilePdfTwoToneSvg from '@ant-design/icons-svg/es/asn/FilePdfTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FilePdfTwoTone(props: IconProps) {
  return <Icon icon={FilePdfTwoToneSvg} {...props} />
}
