// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileExclamationTwoToneSvg from '@ant-design/icons-svg/es/asn/FileExclamationTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FileExclamationTwoTone(props: IconProps) {
  return <Icon icon={FileExclamationTwoToneSvg} {...props} />
}
