// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileZipTwoToneSvg from '@ant-design/icons-svg/es/asn/FileZipTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FileZipTwoTone(props: IconProps) {
  return <Icon icon={FileZipTwoToneSvg} {...props} />
}
