// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileImageOutlinedSvg from '@ant-design/icons-svg/es/asn/FileImageOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FileImageOutlined(props: IconProps) {
  return <Icon icon={FileImageOutlinedSvg} {...props} />
}
