// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FilePptFilledSvg from '@ant-design/icons-svg/es/asn/FilePptFilled'
import { Icon, type IconProps } from '../components/icon'

export function FilePptFilled(props: IconProps) {
  return <Icon icon={FilePptFilledSvg} {...props} />
}
