// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FilePdfOutlinedSvg from '@ant-design/icons-svg/es/asn/FilePdfOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FilePdfOutlined(props: IconProps) {
  return <Icon icon={FilePdfOutlinedSvg} {...props} />
}
