// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileUnknownTwoToneSvg from '@ant-design/icons-svg/es/asn/FileUnknownTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FileUnknownTwoTone(props: IconProps) {
  return <Icon icon={FileUnknownTwoToneSvg} {...props} />
}
