// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FileProtectOutlinedSvg from '@ant-design/icons-svg/es/asn/FileProtectOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FileProtectOutlined(props: IconProps) {
  return <Icon icon={FileProtectOutlinedSvg} {...props} />
}
