// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FilterTwoToneSvg from '@ant-design/icons-svg/es/asn/FilterTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FilterTwoTone(props: IconProps) {
  return <Icon icon={FilterTwoToneSvg} {...props} />
}
