// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FilterFilledSvg from '@ant-design/icons-svg/es/asn/FilterFilled'
import { Icon, type IconProps } from '../components/icon'

export function FilterFilled(props: IconProps) {
  return <Icon icon={FilterFilledSvg} {...props} />
}
