// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FilterOutlinedSvg from '@ant-design/icons-svg/es/asn/FilterOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FilterOutlined(props: IconProps) {
  return <Icon icon={FilterOutlinedSvg} {...props} />
}
