// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FireTwoToneSvg from '@ant-design/icons-svg/es/asn/FireTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FireTwoTone(props: IconProps) {
  return <Icon icon={FireTwoToneSvg} {...props} />
}
