// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FireFilledSvg from '@ant-design/icons-svg/es/asn/FireFilled'
import { Icon, type IconProps } from '../components/icon'

export function FireFilled(props: IconProps) {
  return <Icon icon={FireFilledSvg} {...props} />
}
