// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FireOutlinedSvg from '@ant-design/icons-svg/es/asn/FireOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FireOutlined(props: IconProps) {
  return <Icon icon={FireOutlinedSvg} {...props} />
}
