// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FlagTwoToneSvg from '@ant-design/icons-svg/es/asn/FlagTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FlagTwoTone(props: IconProps) {
  return <Icon icon={FlagTwoToneSvg} {...props} />
}
