// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FlagFilledSvg from '@ant-design/icons-svg/es/asn/FlagFilled'
import { Icon, type IconProps } from '../components/icon'

export function FlagFilled(props: IconProps) {
  return <Icon icon={FlagFilledSvg} {...props} />
}
