// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FlagOutlinedSvg from '@ant-design/icons-svg/es/asn/FlagOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FlagOutlined(props: IconProps) {
  return <Icon icon={FlagOutlinedSvg} {...props} />
}
