// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FolderAddTwoToneSvg from '@ant-design/icons-svg/es/asn/FolderAddTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FolderAddTwoTone(props: IconProps) {
  return <Icon icon={FolderAddTwoToneSvg} {...props} />
}
