// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FolderOpenTwoToneSvg from '@ant-design/icons-svg/es/asn/FolderOpenTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FolderOpenTwoTone(props: IconProps) {
  return <Icon icon={FolderOpenTwoToneSvg} {...props} />
}
