// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FolderOpenFilledSvg from '@ant-design/icons-svg/es/asn/FolderOpenFilled'
import { Icon, type IconProps } from '../components/icon'

export function FolderOpenFilled(props: IconProps) {
  return <Icon icon={FolderOpenFilledSvg} {...props} />
}
