// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FolderOutlinedSvg from '@ant-design/icons-svg/es/asn/FolderOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FolderOutlined(props: IconProps) {
  return <Icon icon={FolderOutlinedSvg} {...props} />
}
