// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FolderOpenOutlinedSvg from '@ant-design/icons-svg/es/asn/FolderOpenOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FolderOpenOutlined(props: IconProps) {
  return <Icon icon={FolderOpenOutlinedSvg} {...props} />
}
