// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FolderFilledSvg from '@ant-design/icons-svg/es/asn/FolderFilled'
import { Icon, type IconProps } from '../components/icon'

export function FolderFilled(props: IconProps) {
  return <Icon icon={FolderFilledSvg} {...props} />
}
