// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FolderViewOutlinedSvg from '@ant-design/icons-svg/es/asn/FolderViewOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FolderViewOutlined(props: IconProps) {
  return <Icon icon={FolderViewOutlinedSvg} {...props} />
}
