// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FolderAddFilledSvg from '@ant-design/icons-svg/es/asn/FolderAddFilled'
import { Icon, type IconProps } from '../components/icon'

export function FolderAddFilled(props: IconProps) {
  return <Icon icon={FolderAddFilledSvg} {...props} />
}
