// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FolderAddOutlinedSvg from '@ant-design/icons-svg/es/asn/FolderAddOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FolderAddOutlined(props: IconProps) {
  return <Icon icon={FolderAddOutlinedSvg} {...props} />
}
