// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FolderTwoToneSvg from '@ant-design/icons-svg/es/asn/FolderTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FolderTwoTone(props: IconProps) {
  return <Icon icon={FolderTwoToneSvg} {...props} />
}
