// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FontColorsOutlinedSvg from '@ant-design/icons-svg/es/asn/FontColorsOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FontColorsOutlined(props: IconProps) {
  return <Icon icon={FontColorsOutlinedSvg} {...props} />
}
