// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FontSizeOutlinedSvg from '@ant-design/icons-svg/es/asn/FontSizeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FontSizeOutlined(props: IconProps) {
  return <Icon icon={FontSizeOutlinedSvg} {...props} />
}
