// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ForkOutlinedSvg from '@ant-design/icons-svg/es/asn/ForkOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ForkOutlined(props: IconProps) {
  return <Icon icon={ForkOutlinedSvg} {...props} />
}
