// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FormOutlinedSvg from '@ant-design/icons-svg/es/asn/FormOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FormOutlined(props: IconProps) {
  return <Icon icon={FormOutlinedSvg} {...props} />
}
