// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FormatPainterOutlinedSvg from '@ant-design/icons-svg/es/asn/FormatPainterOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FormatPainterOutlined(props: IconProps) {
  return <Icon icon={FormatPainterOutlinedSvg} {...props} />
}
