// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FormatPainterFilledSvg from '@ant-design/icons-svg/es/asn/FormatPainterFilled'
import { Icon, type IconProps } from '../components/icon'

export function FormatPainterFilled(props: IconProps) {
  return <Icon icon={FormatPainterFilledSvg} {...props} />
}
