// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ForwardFilledSvg from '@ant-design/icons-svg/es/asn/ForwardFilled'
import { Icon, type IconProps } from '../components/icon'

export function ForwardFilled(props: IconProps) {
  return <Icon icon={ForwardFilledSvg} {...props} />
}
