// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ForwardOutlinedSvg from '@ant-design/icons-svg/es/asn/ForwardOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ForwardOutlined(props: IconProps) {
  return <Icon icon={ForwardOutlinedSvg} {...props} />
}
