// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FrownTwoToneSvg from '@ant-design/icons-svg/es/asn/FrownTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FrownTwoTone(props: IconProps) {
  return <Icon icon={FrownTwoToneSvg} {...props} />
}
