// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FrownOutlinedSvg from '@ant-design/icons-svg/es/asn/FrownOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FrownOutlined(props: IconProps) {
  return <Icon icon={FrownOutlinedSvg} {...props} />
}
