// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FrownFilledSvg from '@ant-design/icons-svg/es/asn/FrownFilled'
import { Icon, type IconProps } from '../components/icon'

export function FrownFilled(props: IconProps) {
  return <Icon icon={FrownFilledSvg} {...props} />
}
