// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FullscreenExitOutlinedSvg from '@ant-design/icons-svg/es/asn/FullscreenExitOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FullscreenExitOutlined(props: IconProps) {
  return <Icon icon={FullscreenExitOutlinedSvg} {...props} />
}
