// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FullscreenOutlinedSvg from '@ant-design/icons-svg/es/asn/FullscreenOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FullscreenOutlined(props: IconProps) {
  return <Icon icon={FullscreenOutlinedSvg} {...props} />
}
