// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FunctionOutlinedSvg from '@ant-design/icons-svg/es/asn/FunctionOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FunctionOutlined(props: IconProps) {
  return <Icon icon={FunctionOutlinedSvg} {...props} />
}
