// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FundTwoToneSvg from '@ant-design/icons-svg/es/asn/FundTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FundTwoTone(props: IconProps) {
  return <Icon icon={FundTwoToneSvg} {...props} />
}
