// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FundViewOutlinedSvg from '@ant-design/icons-svg/es/asn/FundViewOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FundViewOutlined(props: IconProps) {
  return <Icon icon={FundViewOutlinedSvg} {...props} />
}
