// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FundOutlinedSvg from '@ant-design/icons-svg/es/asn/FundOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FundOutlined(props: IconProps) {
  return <Icon icon={FundOutlinedSvg} {...props} />
}
