// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FundFilledSvg from '@ant-design/icons-svg/es/asn/FundFilled'
import { Icon, type IconProps } from '../components/icon'

export function FundFilled(props: IconProps) {
  return <Icon icon={FundFilledSvg} {...props} />
}
