// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FundProjectionScreenOutlinedSvg from '@ant-design/icons-svg/es/asn/FundProjectionScreenOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FundProjectionScreenOutlined(props: IconProps) {
  return <Icon icon={FundProjectionScreenOutlinedSvg} {...props} />
}
