// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FunnelPlotFilledSvg from '@ant-design/icons-svg/es/asn/FunnelPlotFilled'
import { Icon, type IconProps } from '../components/icon'

export function FunnelPlotFilled(props: IconProps) {
  return <Icon icon={FunnelPlotFilledSvg} {...props} />
}
