// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FunnelPlotTwoToneSvg from '@ant-design/icons-svg/es/asn/FunnelPlotTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function FunnelPlotTwoTone(props: IconProps) {
  return <Icon icon={FunnelPlotTwoToneSvg} {...props} />
}
