// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import FunnelPlotOutlinedSvg from '@ant-design/icons-svg/es/asn/FunnelPlotOutlined'
import { Icon, type IconProps } from '../components/icon'

export function FunnelPlotOutlined(props: IconProps) {
  return <Icon icon={FunnelPlotOutlinedSvg} {...props} />
}
