// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GatewayOutlinedSvg from '@ant-design/icons-svg/es/asn/GatewayOutlined'
import { Icon, type IconProps } from '../components/icon'

export function GatewayOutlined(props: IconProps) {
  return <Icon icon={GatewayOutlinedSvg} {...props} />
}
