// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GifOutlinedSvg from '@ant-design/icons-svg/es/asn/GifOutlined'
import { Icon, type IconProps } from '../components/icon'

export function GifOutlined(props: IconProps) {
  return <Icon icon={GifOutlinedSvg} {...props} />
}
