// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GiftOutlinedSvg from '@ant-design/icons-svg/es/asn/GiftOutlined'
import { Icon, type IconProps } from '../components/icon'

export function GiftOutlined(props: IconProps) {
  return <Icon icon={GiftOutlinedSvg} {...props} />
}
