// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GiftFilledSvg from '@ant-design/icons-svg/es/asn/GiftFilled'
import { Icon, type IconProps } from '../components/icon'

export function GiftFilled(props: IconProps) {
  return <Icon icon={GiftFilledSvg} {...props} />
}
