// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GiftTwoToneSvg from '@ant-design/icons-svg/es/asn/GiftTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function GiftTwoTone(props: IconProps) {
  return <Icon icon={GiftTwoToneSvg} {...props} />
}
