// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GithubOutlinedSvg from '@ant-design/icons-svg/es/asn/GithubOutlined'
import { Icon, type IconProps } from '../components/icon'

export function GithubOutlined(props: IconProps) {
  return <Icon icon={GithubOutlinedSvg} {...props} />
}
