// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GithubFilledSvg from '@ant-design/icons-svg/es/asn/GithubFilled'
import { Icon, type IconProps } from '../components/icon'

export function GithubFilled(props: IconProps) {
  return <Icon icon={GithubFilledSvg} {...props} />
}
