// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GitlabOutlinedSvg from '@ant-design/icons-svg/es/asn/GitlabOutlined'
import { Icon, type IconProps } from '../components/icon'

export function GitlabOutlined(props: IconProps) {
  return <Icon icon={GitlabOutlinedSvg} {...props} />
}
