// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GitlabFilledSvg from '@ant-design/icons-svg/es/asn/GitlabFilled'
import { Icon, type IconProps } from '../components/icon'

export function GitlabFilled(props: IconProps) {
  return <Icon icon={GitlabFilledSvg} {...props} />
}
