// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GlobalOutlinedSvg from '@ant-design/icons-svg/es/asn/GlobalOutlined'
import { Icon, type IconProps } from '../components/icon'

export function GlobalOutlined(props: IconProps) {
  return <Icon icon={GlobalOutlinedSvg} {...props} />
}
