// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GoldFilledSvg from '@ant-design/icons-svg/es/asn/GoldFilled'
import { Icon, type IconProps } from '../components/icon'

export function GoldFilled(props: IconProps) {
  return <Icon icon={GoldFilledSvg} {...props} />
}
