// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GoldOutlinedSvg from '@ant-design/icons-svg/es/asn/GoldOutlined'
import { Icon, type IconProps } from '../components/icon'

export function GoldOutlined(props: IconProps) {
  return <Icon icon={GoldOutlinedSvg} {...props} />
}
