// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GoldenFilledSvg from '@ant-design/icons-svg/es/asn/GoldenFilled'
import { Icon, type IconProps } from '../components/icon'

export function GoldenFilled(props: IconProps) {
  return <Icon icon={GoldenFilledSvg} {...props} />
}
