// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GoldTwoToneSvg from '@ant-design/icons-svg/es/asn/GoldTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function GoldTwoTone(props: IconProps) {
  return <Icon icon={GoldTwoToneSvg} {...props} />
}
