// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GoogleCircleFilledSvg from '@ant-design/icons-svg/es/asn/GoogleCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function GoogleCircleFilled(props: IconProps) {
  return <Icon icon={GoogleCircleFilledSvg} {...props} />
}
