// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GooglePlusSquareFilledSvg from '@ant-design/icons-svg/es/asn/GooglePlusSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function GooglePlusSquareFilled(props: IconProps) {
  return <Icon icon={GooglePlusSquareFilledSvg} {...props} />
}
