// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GooglePlusOutlinedSvg from '@ant-design/icons-svg/es/asn/GooglePlusOutlined'
import { Icon, type IconProps } from '../components/icon'

export function GooglePlusOutlined(props: IconProps) {
  return <Icon icon={GooglePlusOutlinedSvg} {...props} />
}
