// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GoogleOutlinedSvg from '@ant-design/icons-svg/es/asn/GoogleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function GoogleOutlined(props: IconProps) {
  return <Icon icon={GoogleOutlinedSvg} {...props} />
}
