// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GoogleSquareFilledSvg from '@ant-design/icons-svg/es/asn/GoogleSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function GoogleSquareFilled(props: IconProps) {
  return <Icon icon={GoogleSquareFilledSvg} {...props} />
}
