// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import GroupOutlinedSvg from '@ant-design/icons-svg/es/asn/GroupOutlined'
import { Icon, type IconProps } from '../components/icon'

export function GroupOutlined(props: IconProps) {
  return <Icon icon={GroupOutlinedSvg} {...props} />
}
