// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HarmonyOSOutlinedSvg from '@ant-design/icons-svg/es/asn/HarmonyOSOutlined'
import { Icon, type IconProps } from '../components/icon'

export function HarmonyOSOutlined(props: IconProps) {
  return <Icon icon={HarmonyOSOutlinedSvg} {...props} />
}
