// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HddFilledSvg from '@ant-design/icons-svg/es/asn/HddFilled'
import { Icon, type IconProps } from '../components/icon'

export function HddFilled(props: IconProps) {
  return <Icon icon={HddFilledSvg} {...props} />
}
