// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HddOutlinedSvg from '@ant-design/icons-svg/es/asn/HddOutlined'
import { Icon, type IconProps } from '../components/icon'

export function HddOutlined(props: IconProps) {
  return <Icon icon={HddOutlinedSvg} {...props} />
}
