// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HddTwoToneSvg from '@ant-design/icons-svg/es/asn/HddTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function HddTwoTone(props: IconProps) {
  return <Icon icon={HddTwoToneSvg} {...props} />
}
