// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HeartFilledSvg from '@ant-design/icons-svg/es/asn/HeartFilled'
import { Icon, type IconProps } from '../components/icon'

export function HeartFilled(props: IconProps) {
  return <Icon icon={HeartFilledSvg} {...props} />
}
