// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HeartTwoToneSvg from '@ant-design/icons-svg/es/asn/HeartTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function HeartTwoTone(props: IconProps) {
  return <Icon icon={HeartTwoToneSvg} {...props} />
}
