// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HeartOutlinedSvg from '@ant-design/icons-svg/es/asn/HeartOutlined'
import { Icon, type IconProps } from '../components/icon'

export function HeartOutlined(props: IconProps) {
  return <Icon icon={HeartOutlinedSvg} {...props} />
}
