// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HeatMapOutlinedSvg from '@ant-design/icons-svg/es/asn/HeatMapOutlined'
import { Icon, type IconProps } from '../components/icon'

export function HeatMapOutlined(props: IconProps) {
  return <Icon icon={HeatMapOutlinedSvg} {...props} />
}
