// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HighlightTwoToneSvg from '@ant-design/icons-svg/es/asn/HighlightTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function HighlightTwoTone(props: IconProps) {
  return <Icon icon={HighlightTwoToneSvg} {...props} />
}
