// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HighlightFilledSvg from '@ant-design/icons-svg/es/asn/HighlightFilled'
import { Icon, type IconProps } from '../components/icon'

export function HighlightFilled(props: IconProps) {
  return <Icon icon={HighlightFilledSvg} {...props} />
}
