// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HighlightOutlinedSvg from '@ant-design/icons-svg/es/asn/HighlightOutlined'
import { Icon, type IconProps } from '../components/icon'

export function HighlightOutlined(props: IconProps) {
  return <Icon icon={HighlightOutlinedSvg} {...props} />
}
