// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HistoryOutlinedSvg from '@ant-design/icons-svg/es/asn/HistoryOutlined'
import { Icon, type IconProps } from '../components/icon'

export function HistoryOutlined(props: IconProps) {
  return <Icon icon={HistoryOutlinedSvg} {...props} />
}
