// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HolderOutlinedSvg from '@ant-design/icons-svg/es/asn/HolderOutlined'
import { Icon, type IconProps } from '../components/icon'

export function HolderOutlined(props: IconProps) {
  return <Icon icon={HolderOutlinedSvg} {...props} />
}
