// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HomeTwoToneSvg from '@ant-design/icons-svg/es/asn/HomeTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function HomeTwoTone(props: IconProps) {
  return <Icon icon={HomeTwoToneSvg} {...props} />
}
