// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HomeFilledSvg from '@ant-design/icons-svg/es/asn/HomeFilled'
import { Icon, type IconProps } from '../components/icon'

export function HomeFilled(props: IconProps) {
  return <Icon icon={HomeFilledSvg} {...props} />
}
