// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HomeOutlinedSvg from '@ant-design/icons-svg/es/asn/HomeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function HomeOutlined(props: IconProps) {
  return <Icon icon={HomeOutlinedSvg} {...props} />
}
