// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HourglassTwoToneSvg from '@ant-design/icons-svg/es/asn/HourglassTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function HourglassTwoTone(props: IconProps) {
  return <Icon icon={HourglassTwoToneSvg} {...props} />
}
