// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HourglassOutlinedSvg from '@ant-design/icons-svg/es/asn/HourglassOutlined'
import { Icon, type IconProps } from '../components/icon'

export function HourglassOutlined(props: IconProps) {
  return <Icon icon={HourglassOutlinedSvg} {...props} />
}
