// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import HourglassFilledSvg from '@ant-design/icons-svg/es/asn/HourglassFilled'
import { Icon, type IconProps } from '../components/icon'

export function HourglassFilled(props: IconProps) {
  return <Icon icon={HourglassFilledSvg} {...props} />
}
