// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import Html5FilledSvg from '@ant-design/icons-svg/es/asn/Html5Filled'
import { Icon, type IconProps } from '../components/icon'

export function Html5Filled(props: IconProps) {
  return <Icon icon={Html5FilledSvg} {...props} />
}
