// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import Html5OutlinedSvg from '@ant-design/icons-svg/es/asn/Html5Outlined'
import { Icon, type IconProps } from '../components/icon'

export function Html5Outlined(props: IconProps) {
  return <Icon icon={Html5OutlinedSvg} {...props} />
}
