// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import Html5TwoToneSvg from '@ant-design/icons-svg/es/asn/Html5TwoTone'
import { Icon, type IconProps } from '../components/icon'

export function Html5TwoTone(props: IconProps) {
  return <Icon icon={Html5TwoToneSvg} {...props} />
}
