// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import IdcardFilledSvg from '@ant-design/icons-svg/es/asn/IdcardFilled'
import { Icon, type IconProps } from '../components/icon'

export function IdcardFilled(props: IconProps) {
  return <Icon icon={IdcardFilledSvg} {...props} />
}
