// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import IdcardTwoToneSvg from '@ant-design/icons-svg/es/asn/IdcardTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function IdcardTwoTone(props: IconProps) {
  return <Icon icon={IdcardTwoToneSvg} {...props} />
}
