// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import IdcardOutlinedSvg from '@ant-design/icons-svg/es/asn/IdcardOutlined'
import { Icon, type IconProps } from '../components/icon'

export function IdcardOutlined(props: IconProps) {
  return <Icon icon={IdcardOutlinedSvg} {...props} />
}
