// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import IeCircleFilledSvg from '@ant-design/icons-svg/es/asn/IeCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function IeCircleFilled(props: IconProps) {
  return <Icon icon={IeCircleFilledSvg} {...props} />
}
