// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import IeOutlinedSvg from '@ant-design/icons-svg/es/asn/IeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function IeOutlined(props: IconProps) {
  return <Icon icon={IeOutlinedSvg} {...props} />
}
