// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import IeSquareFilledSvg from '@ant-design/icons-svg/es/asn/IeSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function IeSquareFilled(props: IconProps) {
  return <Icon icon={IeSquareFilledSvg} {...props} />
}
