// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ImportOutlinedSvg from '@ant-design/icons-svg/es/asn/ImportOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ImportOutlined(props: IconProps) {
  return <Icon icon={ImportOutlinedSvg} {...props} />
}
