// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import InboxOutlinedSvg from '@ant-design/icons-svg/es/asn/InboxOutlined'
import { Icon, type IconProps } from '../components/icon'

export function InboxOutlined(props: IconProps) {
  return <Icon icon={InboxOutlinedSvg} {...props} />
}
