// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import InfoCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/InfoCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function InfoCircleTwoTone(props: IconProps) {
  return <Icon icon={InfoCircleTwoToneSvg} {...props} />
}
