// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import InfoCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/InfoCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function InfoCircleOutlined(props: IconProps) {
  return <Icon icon={InfoCircleOutlinedSvg} {...props} />
}
