// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import InfoCircleFilledSvg from '@ant-design/icons-svg/es/asn/InfoCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function InfoCircleFilled(props: IconProps) {
  return <Icon icon={InfoCircleFilledSvg} {...props} />
}
