// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import InfoOutlinedSvg from '@ant-design/icons-svg/es/asn/InfoOutlined'
import { Icon, type IconProps } from '../components/icon'

export function InfoOutlined(props: IconProps) {
  return <Icon icon={InfoOutlinedSvg} {...props} />
}
