// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import InsertRowBelowOutlinedSvg from '@ant-design/icons-svg/es/asn/InsertRowBelowOutlined'
import { Icon, type IconProps } from '../components/icon'

export function InsertRowBelowOutlined(props: IconProps) {
  return <Icon icon={InsertRowBelowOutlinedSvg} {...props} />
}
