// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import InsertRowLeftOutlinedSvg from '@ant-design/icons-svg/es/asn/InsertRowLeftOutlined'
import { Icon, type IconProps } from '../components/icon'

export function InsertRowLeftOutlined(props: IconProps) {
  return <Icon icon={InsertRowLeftOutlinedSvg} {...props} />
}
