// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import InsertRowRightOutlinedSvg from '@ant-design/icons-svg/es/asn/InsertRowRightOutlined'
import { Icon, type IconProps } from '../components/icon'

export function InsertRowRightOutlined(props: IconProps) {
  return <Icon icon={InsertRowRightOutlinedSvg} {...props} />
}
