// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import InsertRowAboveOutlinedSvg from '@ant-design/icons-svg/es/asn/InsertRowAboveOutlined'
import { Icon, type IconProps } from '../components/icon'

export function InsertRowAboveOutlined(props: IconProps) {
  return <Icon icon={InsertRowAboveOutlinedSvg} {...props} />
}
