// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import InstagramFilledSvg from '@ant-design/icons-svg/es/asn/InstagramFilled'
import { Icon, type IconProps } from '../components/icon'

export function InstagramFilled(props: IconProps) {
  return <Icon icon={InstagramFilledSvg} {...props} />
}
