// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import InstagramOutlinedSvg from '@ant-design/icons-svg/es/asn/InstagramOutlined'
import { Icon, type IconProps } from '../components/icon'

export function InstagramOutlined(props: IconProps) {
  return <Icon icon={InstagramOutlinedSvg} {...props} />
}
