// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import InsuranceTwoToneSvg from '@ant-design/icons-svg/es/asn/InsuranceTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function InsuranceTwoTone(props: IconProps) {
  return <Icon icon={InsuranceTwoToneSvg} {...props} />
}
