// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import InsuranceFilledSvg from '@ant-design/icons-svg/es/asn/InsuranceFilled'
import { Icon, type IconProps } from '../components/icon'

export function InsuranceFilled(props: IconProps) {
  return <Icon icon={InsuranceFilledSvg} {...props} />
}
