// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import InsuranceOutlinedSvg from '@ant-design/icons-svg/es/asn/InsuranceOutlined'
import { Icon, type IconProps } from '../components/icon'

export function InsuranceOutlined(props: IconProps) {
  return <Icon icon={InsuranceOutlinedSvg} {...props} />
}
