// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import InteractionFilledSvg from '@ant-design/icons-svg/es/asn/InteractionFilled'
import { Icon, type IconProps } from '../components/icon'

export function InteractionFilled(props: IconProps) {
  return <Icon icon={InteractionFilledSvg} {...props} />
}
