// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import InteractionOutlinedSvg from '@ant-design/icons-svg/es/asn/InteractionOutlined'
import { Icon, type IconProps } from '../components/icon'

export function InteractionOutlined(props: IconProps) {
  return <Icon icon={InteractionOutlinedSvg} {...props} />
}
