// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import InteractionTwoToneSvg from '@ant-design/icons-svg/es/asn/InteractionTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function InteractionTwoTone(props: IconProps) {
  return <Icon icon={InteractionTwoToneSvg} {...props} />
}
