// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import IssuesCloseOutlinedSvg from '@ant-design/icons-svg/es/asn/IssuesCloseOutlined'
import { Icon, type IconProps } from '../components/icon'

export function IssuesCloseOutlined(props: IconProps) {
  return <Icon icon={IssuesCloseOutlinedSvg} {...props} />
}
