// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ItalicOutlinedSvg from '@ant-design/icons-svg/es/asn/ItalicOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ItalicOutlined(props: IconProps) {
  return <Icon icon={ItalicOutlinedSvg} {...props} />
}
