// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import JavaOutlinedSvg from '@ant-design/icons-svg/es/asn/JavaOutlined'
import { Icon, type IconProps } from '../components/icon'

export function JavaOutlined(props: IconProps) {
  return <Icon icon={JavaOutlinedSvg} {...props} />
}
