// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import JavaScriptOutlinedSvg from '@ant-design/icons-svg/es/asn/JavaScriptOutlined'
import { Icon, type IconProps } from '../components/icon'

export function JavaScriptOutlined(props: IconProps) {
  return <Icon icon={JavaScriptOutlinedSvg} {...props} />
}
