// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import KeyOutlinedSvg from '@ant-design/icons-svg/es/asn/KeyOutlined'
import { Icon, type IconProps } from '../components/icon'

export function KeyOutlined(props: IconProps) {
  return <Icon icon={KeyOutlinedSvg} {...props} />
}
