// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import KubernetesOutlinedSvg from '@ant-design/icons-svg/es/asn/KubernetesOutlined'
import { Icon, type IconProps } from '../components/icon'

export function KubernetesOutlined(props: IconProps) {
  return <Icon icon={KubernetesOutlinedSvg} {...props} />
}
