// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LaptopOutlinedSvg from '@ant-design/icons-svg/es/asn/LaptopOutlined'
import { Icon, type IconProps } from '../components/icon'

export function LaptopOutlined(props: IconProps) {
  return <Icon icon={LaptopOutlinedSvg} {...props} />
}
