// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LayoutFilledSvg from '@ant-design/icons-svg/es/asn/LayoutFilled'
import { Icon, type IconProps } from '../components/icon'

export function LayoutFilled(props: IconProps) {
  return <Icon icon={LayoutFilledSvg} {...props} />
}
