// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LayoutOutlinedSvg from '@ant-design/icons-svg/es/asn/LayoutOutlined'
import { Icon, type IconProps } from '../components/icon'

export function LayoutOutlined(props: IconProps) {
  return <Icon icon={LayoutOutlinedSvg} {...props} />
}
