// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LeftSquareFilledSvg from '@ant-design/icons-svg/es/asn/LeftSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function LeftSquareFilled(props: IconProps) {
  return <Icon icon={LeftSquareFilledSvg} {...props} />
}
