// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LeftSquareTwoToneSvg from '@ant-design/icons-svg/es/asn/LeftSquareTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function LeftSquareTwoTone(props: IconProps) {
  return <Icon icon={LeftSquareTwoToneSvg} {...props} />
}
