// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LeftCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/LeftCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function LeftCircleOutlined(props: IconProps) {
  return <Icon icon={LeftCircleOutlinedSvg} {...props} />
}
