// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LeftCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/LeftCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function LeftCircleTwoTone(props: IconProps) {
  return <Icon icon={LeftCircleTwoToneSvg} {...props} />
}
