// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LeftSquareOutlinedSvg from '@ant-design/icons-svg/es/asn/LeftSquareOutlined'
import { Icon, type IconProps } from '../components/icon'

export function LeftSquareOutlined(props: IconProps) {
  return <Icon icon={LeftSquareOutlinedSvg} {...props} />
}
