// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LeftOutlinedSvg from '@ant-design/icons-svg/es/asn/LeftOutlined'
import { Icon, type IconProps } from '../components/icon'

export function LeftOutlined(props: IconProps) {
  return <Icon icon={LeftOutlinedSvg} {...props} />
}
