// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LeftCircleFilledSvg from '@ant-design/icons-svg/es/asn/LeftCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function LeftCircleFilled(props: IconProps) {
  return <Icon icon={LeftCircleFilledSvg} {...props} />
}
