// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LikeTwoToneSvg from '@ant-design/icons-svg/es/asn/LikeTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function LikeTwoTone(props: IconProps) {
  return <Icon icon={LikeTwoToneSvg} {...props} />
}
