// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LikeOutlinedSvg from '@ant-design/icons-svg/es/asn/LikeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function LikeOutlined(props: IconProps) {
  return <Icon icon={LikeOutlinedSvg} {...props} />
}
