// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LikeFilledSvg from '@ant-design/icons-svg/es/asn/LikeFilled'
import { Icon, type IconProps } from '../components/icon'

export function LikeFilled(props: IconProps) {
  return <Icon icon={LikeFilledSvg} {...props} />
}
