// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LineChartOutlinedSvg from '@ant-design/icons-svg/es/asn/LineChartOutlined'
import { Icon, type IconProps } from '../components/icon'

export function LineChartOutlined(props: IconProps) {
  return <Icon icon={LineChartOutlinedSvg} {...props} />
}
