// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LineHeightOutlinedSvg from '@ant-design/icons-svg/es/asn/LineHeightOutlined'
import { Icon, type IconProps } from '../components/icon'

export function LineHeightOutlined(props: IconProps) {
  return <Icon icon={LineHeightOutlinedSvg} {...props} />
}
