// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LineOutlinedSvg from '@ant-design/icons-svg/es/asn/LineOutlined'
import { Icon, type IconProps } from '../components/icon'

export function LineOutlined(props: IconProps) {
  return <Icon icon={LineOutlinedSvg} {...props} />
}
