// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LinkedinOutlinedSvg from '@ant-design/icons-svg/es/asn/LinkedinOutlined'
import { Icon, type IconProps } from '../components/icon'

export function LinkedinOutlined(props: IconProps) {
  return <Icon icon={LinkedinOutlinedSvg} {...props} />
}
