// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LinkOutlinedSvg from '@ant-design/icons-svg/es/asn/LinkOutlined'
import { Icon, type IconProps } from '../components/icon'

export function LinkOutlined(props: IconProps) {
  return <Icon icon={LinkOutlinedSvg} {...props} />
}
