// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LinkedinFilledSvg from '@ant-design/icons-svg/es/asn/LinkedinFilled'
import { Icon, type IconProps } from '../components/icon'

export function LinkedinFilled(props: IconProps) {
  return <Icon icon={LinkedinFilledSvg} {...props} />
}
