// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LinuxOutlinedSvg from '@ant-design/icons-svg/es/asn/LinuxOutlined'
import { Icon, type IconProps } from '../components/icon'

export function LinuxOutlined(props: IconProps) {
  return <Icon icon={LinuxOutlinedSvg} {...props} />
}
