// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LoadingOutlinedSvg from '@ant-design/icons-svg/es/asn/LoadingOutlined'
import { Icon, type IconProps } from '../components/icon'

export function LoadingOutlined(props: IconProps) {
  return <Icon icon={LoadingOutlinedSvg} {...props} />
}
