// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import Loading3QuartersOutlinedSvg from '@ant-design/icons-svg/es/asn/Loading3QuartersOutlined'
import { Icon, type IconProps } from '../components/icon'

export function Loading3QuartersOutlined(props: IconProps) {
  return <Icon icon={Loading3QuartersOutlinedSvg} {...props} />
}
