// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LockFilledSvg from '@ant-design/icons-svg/es/asn/LockFilled'
import { Icon, type IconProps } from '../components/icon'

export function LockFilled(props: IconProps) {
  return <Icon icon={LockFilledSvg} {...props} />
}
