// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LockTwoToneSvg from '@ant-design/icons-svg/es/asn/LockTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function LockTwoTone(props: IconProps) {
  return <Icon icon={LockTwoToneSvg} {...props} />
}
