// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LockOutlinedSvg from '@ant-design/icons-svg/es/asn/LockOutlined'
import { Icon, type IconProps } from '../components/icon'

export function LockOutlined(props: IconProps) {
  return <Icon icon={LockOutlinedSvg} {...props} />
}
