// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LoginOutlinedSvg from '@ant-design/icons-svg/es/asn/LoginOutlined'
import { Icon, type IconProps } from '../components/icon'

export function LoginOutlined(props: IconProps) {
  return <Icon icon={LoginOutlinedSvg} {...props} />
}
