// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import LogoutOutlinedSvg from '@ant-design/icons-svg/es/asn/LogoutOutlined'
import { Icon, type IconProps } from '../components/icon'

export function LogoutOutlined(props: IconProps) {
  return <Icon icon={LogoutOutlinedSvg} {...props} />
}
