// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MacCommandFilledSvg from '@ant-design/icons-svg/es/asn/MacCommandFilled'
import { Icon, type IconProps } from '../components/icon'

export function MacCommandFilled(props: IconProps) {
  return <Icon icon={MacCommandFilledSvg} {...props} />
}
