// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MacCommandOutlinedSvg from '@ant-design/icons-svg/es/asn/MacCommandOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MacCommandOutlined(props: IconProps) {
  return <Icon icon={MacCommandOutlinedSvg} {...props} />
}
