// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MailOutlinedSvg from '@ant-design/icons-svg/es/asn/MailOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MailOutlined(props: IconProps) {
  return <Icon icon={MailOutlinedSvg} {...props} />
}
