// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MailFilledSvg from '@ant-design/icons-svg/es/asn/MailFilled'
import { Icon, type IconProps } from '../components/icon'

export function MailFilled(props: IconProps) {
  return <Icon icon={MailFilledSvg} {...props} />
}
