// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MailTwoToneSvg from '@ant-design/icons-svg/es/asn/MailTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function MailTwoTone(props: IconProps) {
  return <Icon icon={MailTwoToneSvg} {...props} />
}
