// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ManOutlinedSvg from '@ant-design/icons-svg/es/asn/ManOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ManOutlined(props: IconProps) {
  return <Icon icon={ManOutlinedSvg} {...props} />
}
