// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MedicineBoxFilledSvg from '@ant-design/icons-svg/es/asn/MedicineBoxFilled'
import { Icon, type IconProps } from '../components/icon'

export function MedicineBoxFilled(props: IconProps) {
  return <Icon icon={MedicineBoxFilledSvg} {...props} />
}
