// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MedicineBoxTwoToneSvg from '@ant-design/icons-svg/es/asn/MedicineBoxTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function MedicineBoxTwoTone(props: IconProps) {
  return <Icon icon={MedicineBoxTwoToneSvg} {...props} />
}
