// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MediumOutlinedSvg from '@ant-design/icons-svg/es/asn/MediumOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MediumOutlined(props: IconProps) {
  return <Icon icon={MediumOutlinedSvg} {...props} />
}
