// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MediumCircleFilledSvg from '@ant-design/icons-svg/es/asn/MediumCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function MediumCircleFilled(props: IconProps) {
  return <Icon icon={MediumCircleFilledSvg} {...props} />
}
