// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MedicineBoxOutlinedSvg from '@ant-design/icons-svg/es/asn/MedicineBoxOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MedicineBoxOutlined(props: IconProps) {
  return <Icon icon={MedicineBoxOutlinedSvg} {...props} />
}
