// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MediumWorkmarkOutlinedSvg from '@ant-design/icons-svg/es/asn/MediumWorkmarkOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MediumWorkmarkOutlined(props: IconProps) {
  return <Icon icon={MediumWorkmarkOutlinedSvg} {...props} />
}
