// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MehOutlinedSvg from '@ant-design/icons-svg/es/asn/MehOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MehOutlined(props: IconProps) {
  return <Icon icon={MehOutlinedSvg} {...props} />
}
