// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MehTwoToneSvg from '@ant-design/icons-svg/es/asn/MehTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function MehTwoTone(props: IconProps) {
  return <Icon icon={MehTwoToneSvg} {...props} />
}
