// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MehFilledSvg from '@ant-design/icons-svg/es/asn/MehFilled'
import { Icon, type IconProps } from '../components/icon'

export function MehFilled(props: IconProps) {
  return <Icon icon={MehFilledSvg} {...props} />
}
