// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MenuOutlinedSvg from '@ant-design/icons-svg/es/asn/MenuOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MenuOutlined(props: IconProps) {
  return <Icon icon={MenuOutlinedSvg} {...props} />
}
