// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MenuFoldOutlinedSvg from '@ant-design/icons-svg/es/asn/MenuFoldOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MenuFoldOutlined(props: IconProps) {
  return <Icon icon={MenuFoldOutlinedSvg} {...props} />
}
