// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MenuUnfoldOutlinedSvg from '@ant-design/icons-svg/es/asn/MenuUnfoldOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MenuUnfoldOutlined(props: IconProps) {
  return <Icon icon={MenuUnfoldOutlinedSvg} {...props} />
}
