// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MergeOutlinedSvg from '@ant-design/icons-svg/es/asn/MergeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MergeOutlined(props: IconProps) {
  return <Icon icon={MergeOutlinedSvg} {...props} />
}
