// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MergeCellsOutlinedSvg from '@ant-design/icons-svg/es/asn/MergeCellsOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MergeCellsOutlined(props: IconProps) {
  return <Icon icon={MergeCellsOutlinedSvg} {...props} />
}
