// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MergeFilledSvg from '@ant-design/icons-svg/es/asn/MergeFilled'
import { Icon, type IconProps } from '../components/icon'

export function MergeFilled(props: IconProps) {
  return <Icon icon={MergeFilledSvg} {...props} />
}
