// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MessageOutlinedSvg from '@ant-design/icons-svg/es/asn/MessageOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MessageOutlined(props: IconProps) {
  return <Icon icon={MessageOutlinedSvg} {...props} />
}
