// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MessageTwoToneSvg from '@ant-design/icons-svg/es/asn/MessageTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function MessageTwoTone(props: IconProps) {
  return <Icon icon={MessageTwoToneSvg} {...props} />
}
