// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MessageFilledSvg from '@ant-design/icons-svg/es/asn/MessageFilled'
import { Icon, type IconProps } from '../components/icon'

export function MessageFilled(props: IconProps) {
  return <Icon icon={MessageFilledSvg} {...props} />
}
