// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MinusSquareTwoToneSvg from '@ant-design/icons-svg/es/asn/MinusSquareTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function MinusSquareTwoTone(props: IconProps) {
  return <Icon icon={MinusSquareTwoToneSvg} {...props} />
}
