// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MinusCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/MinusCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MinusCircleOutlined(props: IconProps) {
  return <Icon icon={MinusCircleOutlinedSvg} {...props} />
}
