// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MinusSquareOutlinedSvg from '@ant-design/icons-svg/es/asn/MinusSquareOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MinusSquareOutlined(props: IconProps) {
  return <Icon icon={MinusSquareOutlinedSvg} {...props} />
}
