// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MinusCircleFilledSvg from '@ant-design/icons-svg/es/asn/MinusCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function MinusCircleFilled(props: IconProps) {
  return <Icon icon={MinusCircleFilledSvg} {...props} />
}
