// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MinusSquareFilledSvg from '@ant-design/icons-svg/es/asn/MinusSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function MinusSquareFilled(props: IconProps) {
  return <Icon icon={MinusSquareFilledSvg} {...props} />
}
