// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MinusOutlinedSvg from '@ant-design/icons-svg/es/asn/MinusOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MinusOutlined(props: IconProps) {
  return <Icon icon={MinusOutlinedSvg} {...props} />
}
