// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MinusCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/MinusCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function MinusCircleTwoTone(props: IconProps) {
  return <Icon icon={MinusCircleTwoToneSvg} {...props} />
}
