// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MobileTwoToneSvg from '@ant-design/icons-svg/es/asn/MobileTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function MobileTwoTone(props: IconProps) {
  return <Icon icon={MobileTwoToneSvg} {...props} />
}
