// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MobileFilledSvg from '@ant-design/icons-svg/es/asn/MobileFilled'
import { Icon, type IconProps } from '../components/icon'

export function MobileFilled(props: IconProps) {
  return <Icon icon={MobileFilledSvg} {...props} />
}
