// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MobileOutlinedSvg from '@ant-design/icons-svg/es/asn/MobileOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MobileOutlined(props: IconProps) {
  return <Icon icon={MobileOutlinedSvg} {...props} />
}
