// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MoneyCollectOutlinedSvg from '@ant-design/icons-svg/es/asn/MoneyCollectOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MoneyCollectOutlined(props: IconProps) {
  return <Icon icon={MoneyCollectOutlinedSvg} {...props} />
}
