// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MoneyCollectTwoToneSvg from '@ant-design/icons-svg/es/asn/MoneyCollectTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function MoneyCollectTwoTone(props: IconProps) {
  return <Icon icon={MoneyCollectTwoToneSvg} {...props} />
}
