// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MoneyCollectFilledSvg from '@ant-design/icons-svg/es/asn/MoneyCollectFilled'
import { Icon, type IconProps } from '../components/icon'

export function MoneyCollectFilled(props: IconProps) {
  return <Icon icon={MoneyCollectFilledSvg} {...props} />
}
