// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MonitorOutlinedSvg from '@ant-design/icons-svg/es/asn/MonitorOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MonitorOutlined(props: IconProps) {
  return <Icon icon={MonitorOutlinedSvg} {...props} />
}
