// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MoonOutlinedSvg from '@ant-design/icons-svg/es/asn/MoonOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MoonOutlined(props: IconProps) {
  return <Icon icon={MoonOutlinedSvg} {...props} />
}
