// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MoonFilledSvg from '@ant-design/icons-svg/es/asn/MoonFilled'
import { Icon, type IconProps } from '../components/icon'

export function MoonFilled(props: IconProps) {
  return <Icon icon={MoonFilledSvg} {...props} />
}
