// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MoreOutlinedSvg from '@ant-design/icons-svg/es/asn/MoreOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MoreOutlined(props: IconProps) {
  return <Icon icon={MoreOutlinedSvg} {...props} />
}
