// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MutedOutlinedSvg from '@ant-design/icons-svg/es/asn/MutedOutlined'
import { Icon, type IconProps } from '../components/icon'

export function MutedOutlined(props: IconProps) {
  return <Icon icon={MutedOutlinedSvg} {...props} />
}
