// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import MutedFilledSvg from '@ant-design/icons-svg/es/asn/MutedFilled'
import { Icon, type IconProps } from '../components/icon'

export function MutedFilled(props: IconProps) {
  return <Icon icon={MutedFilledSvg} {...props} />
}
