// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import NodeCollapseOutlinedSvg from '@ant-design/icons-svg/es/asn/NodeCollapseOutlined'
import { Icon, type IconProps } from '../components/icon'

export function NodeCollapseOutlined(props: IconProps) {
  return <Icon icon={NodeCollapseOutlinedSvg} {...props} />
}
