// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import NodeExpandOutlinedSvg from '@ant-design/icons-svg/es/asn/NodeExpandOutlined'
import { Icon, type IconProps } from '../components/icon'

export function NodeExpandOutlined(props: IconProps) {
  return <Icon icon={NodeExpandOutlinedSvg} {...props} />
}
