// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import NodeIndexOutlinedSvg from '@ant-design/icons-svg/es/asn/NodeIndexOutlined'
import { Icon, type IconProps } from '../components/icon'

export function NodeIndexOutlined(props: IconProps) {
  return <Icon icon={NodeIndexOutlinedSvg} {...props} />
}
