// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import NotificationOutlinedSvg from '@ant-design/icons-svg/es/asn/NotificationOutlined'
import { Icon, type IconProps } from '../components/icon'

export function NotificationOutlined(props: IconProps) {
  return <Icon icon={NotificationOutlinedSvg} {...props} />
}
