// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import NotificationFilledSvg from '@ant-design/icons-svg/es/asn/NotificationFilled'
import { Icon, type IconProps } from '../components/icon'

export function NotificationFilled(props: IconProps) {
  return <Icon icon={NotificationFilledSvg} {...props} />
}
