// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import NotificationTwoToneSvg from '@ant-design/icons-svg/es/asn/NotificationTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function NotificationTwoTone(props: IconProps) {
  return <Icon icon={NotificationTwoToneSvg} {...props} />
}
