// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import NumberOutlinedSvg from '@ant-design/icons-svg/es/asn/NumberOutlined'
import { Icon, type IconProps } from '../components/icon'

export function NumberOutlined(props: IconProps) {
  return <Icon icon={NumberOutlinedSvg} {...props} />
}
