// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import OneToOneOutlinedSvg from '@ant-design/icons-svg/es/asn/OneToOneOutlined'
import { Icon, type IconProps } from '../components/icon'

export function OneToOneOutlined(props: IconProps) {
  return <Icon icon={OneToOneOutlinedSvg} {...props} />
}
