// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import OpenAIFilledSvg from '@ant-design/icons-svg/es/asn/OpenAIFilled'
import { Icon, type IconProps } from '../components/icon'

export function OpenAIFilled(props: IconProps) {
  return <Icon icon={OpenAIFilledSvg} {...props} />
}
