// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import OpenAIOutlinedSvg from '@ant-design/icons-svg/es/asn/OpenAIOutlined'
import { Icon, type IconProps } from '../components/icon'

export function OpenAIOutlined(props: IconProps) {
  return <Icon icon={OpenAIOutlinedSvg} {...props} />
}
