// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import OrderedListOutlinedSvg from '@ant-design/icons-svg/es/asn/OrderedListOutlined'
import { Icon, type IconProps } from '../components/icon'

export function OrderedListOutlined(props: IconProps) {
  return <Icon icon={OrderedListOutlinedSvg} {...props} />
}
