// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PaperClipOutlinedSvg from '@ant-design/icons-svg/es/asn/PaperClipOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PaperClipOutlined(props: IconProps) {
  return <Icon icon={PaperClipOutlinedSvg} {...props} />
}
