// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PartitionOutlinedSvg from '@ant-design/icons-svg/es/asn/PartitionOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PartitionOutlined(props: IconProps) {
  return <Icon icon={PartitionOutlinedSvg} {...props} />
}
