// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PauseCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/PauseCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PauseCircleOutlined(props: IconProps) {
  return <Icon icon={PauseCircleOutlinedSvg} {...props} />
}
