// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PauseOutlinedSvg from '@ant-design/icons-svg/es/asn/PauseOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PauseOutlined(props: IconProps) {
  return <Icon icon={PauseOutlinedSvg} {...props} />
}
