// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PauseCircleFilledSvg from '@ant-design/icons-svg/es/asn/PauseCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function PauseCircleFilled(props: IconProps) {
  return <Icon icon={PauseCircleFilledSvg} {...props} />
}
