// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PauseCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/PauseCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function PauseCircleTwoTone(props: IconProps) {
  return <Icon icon={PauseCircleTwoToneSvg} {...props} />
}
