// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PayCircleFilledSvg from '@ant-design/icons-svg/es/asn/PayCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function PayCircleFilled(props: IconProps) {
  return <Icon icon={PayCircleFilledSvg} {...props} />
}
