// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PayCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/PayCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PayCircleOutlined(props: IconProps) {
  return <Icon icon={PayCircleOutlinedSvg} {...props} />
}
