// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PercentageOutlinedSvg from '@ant-design/icons-svg/es/asn/PercentageOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PercentageOutlined(props: IconProps) {
  return <Icon icon={PercentageOutlinedSvg} {...props} />
}
