// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PhoneFilledSvg from '@ant-design/icons-svg/es/asn/PhoneFilled'
import { Icon, type IconProps } from '../components/icon'

export function PhoneFilled(props: IconProps) {
  return <Icon icon={PhoneFilledSvg} {...props} />
}
