// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PhoneTwoToneSvg from '@ant-design/icons-svg/es/asn/PhoneTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function PhoneTwoTone(props: IconProps) {
  return <Icon icon={PhoneTwoToneSvg} {...props} />
}
