// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PhoneOutlinedSvg from '@ant-design/icons-svg/es/asn/PhoneOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PhoneOutlined(props: IconProps) {
  return <Icon icon={PhoneOutlinedSvg} {...props} />
}
