// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PicLeftOutlinedSvg from '@ant-design/icons-svg/es/asn/PicLeftOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PicLeftOutlined(props: IconProps) {
  return <Icon icon={PicLeftOutlinedSvg} {...props} />
}
