// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PicRightOutlinedSvg from '@ant-design/icons-svg/es/asn/PicRightOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PicRightOutlined(props: IconProps) {
  return <Icon icon={PicRightOutlinedSvg} {...props} />
}
