// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PicCenterOutlinedSvg from '@ant-design/icons-svg/es/asn/PicCenterOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PicCenterOutlined(props: IconProps) {
  return <Icon icon={PicCenterOutlinedSvg} {...props} />
}
