// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PictureTwoToneSvg from '@ant-design/icons-svg/es/asn/PictureTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function PictureTwoTone(props: IconProps) {
  return <Icon icon={PictureTwoToneSvg} {...props} />
}
