// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PictureFilledSvg from '@ant-design/icons-svg/es/asn/PictureFilled'
import { Icon, type IconProps } from '../components/icon'

export function PictureFilled(props: IconProps) {
  return <Icon icon={PictureFilledSvg} {...props} />
}
