// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PictureOutlinedSvg from '@ant-design/icons-svg/es/asn/PictureOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PictureOutlined(props: IconProps) {
  return <Icon icon={PictureOutlinedSvg} {...props} />
}
