// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PieChartTwoToneSvg from '@ant-design/icons-svg/es/asn/PieChartTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function PieChartTwoTone(props: IconProps) {
  return <Icon icon={PieChartTwoToneSvg} {...props} />
}
