// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PieChartFilledSvg from '@ant-design/icons-svg/es/asn/PieChartFilled'
import { Icon, type IconProps } from '../components/icon'

export function PieChartFilled(props: IconProps) {
  return <Icon icon={PieChartFilledSvg} {...props} />
}
