// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PieChartOutlinedSvg from '@ant-design/icons-svg/es/asn/PieChartOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PieChartOutlined(props: IconProps) {
  return <Icon icon={PieChartOutlinedSvg} {...props} />
}
