// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PinterestOutlinedSvg from '@ant-design/icons-svg/es/asn/PinterestOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PinterestOutlined(props: IconProps) {
  return <Icon icon={PinterestOutlinedSvg} {...props} />
}
