// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PinterestFilledSvg from '@ant-design/icons-svg/es/asn/PinterestFilled'
import { Icon, type IconProps } from '../components/icon'

export function PinterestFilled(props: IconProps) {
  return <Icon icon={PinterestFilledSvg} {...props} />
}
