// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PlaySquareFilledSvg from '@ant-design/icons-svg/es/asn/PlaySquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function PlaySquareFilled(props: IconProps) {
  return <Icon icon={PlaySquareFilledSvg} {...props} />
}
