// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PlayCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/PlayCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function PlayCircleTwoTone(props: IconProps) {
  return <Icon icon={PlayCircleTwoToneSvg} {...props} />
}
