// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PlaySquareTwoToneSvg from '@ant-design/icons-svg/es/asn/PlaySquareTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function PlaySquareTwoTone(props: IconProps) {
  return <Icon icon={PlaySquareTwoToneSvg} {...props} />
}
