// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PlaySquareOutlinedSvg from '@ant-design/icons-svg/es/asn/PlaySquareOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PlaySquareOutlined(props: IconProps) {
  return <Icon icon={PlaySquareOutlinedSvg} {...props} />
}
