// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PlayCircleFilledSvg from '@ant-design/icons-svg/es/asn/PlayCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function PlayCircleFilled(props: IconProps) {
  return <Icon icon={PlayCircleFilledSvg} {...props} />
}
