// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PlayCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/PlayCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PlayCircleOutlined(props: IconProps) {
  return <Icon icon={PlayCircleOutlinedSvg} {...props} />
}
