// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PlusCircleFilledSvg from '@ant-design/icons-svg/es/asn/PlusCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function PlusCircleFilled(props: IconProps) {
  return <Icon icon={PlusCircleFilledSvg} {...props} />
}
