// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PlusSquareFilledSvg from '@ant-design/icons-svg/es/asn/PlusSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function PlusSquareFilled(props: IconProps) {
  return <Icon icon={PlusSquareFilledSvg} {...props} />
}
