// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PlusSquareOutlinedSvg from '@ant-design/icons-svg/es/asn/PlusSquareOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PlusSquareOutlined(props: IconProps) {
  return <Icon icon={PlusSquareOutlinedSvg} {...props} />
}
