// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PlusCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/PlusCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function PlusCircleTwoTone(props: IconProps) {
  return <Icon icon={PlusCircleTwoToneSvg} {...props} />
}
