// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PlusOutlinedSvg from '@ant-design/icons-svg/es/asn/PlusOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PlusOutlined(props: IconProps) {
  return <Icon icon={PlusOutlinedSvg} {...props} />
}
