// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PlusSquareTwoToneSvg from '@ant-design/icons-svg/es/asn/PlusSquareTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function PlusSquareTwoTone(props: IconProps) {
  return <Icon icon={PlusSquareTwoToneSvg} {...props} />
}
