// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PlusCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/PlusCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PlusCircleOutlined(props: IconProps) {
  return <Icon icon={PlusCircleOutlinedSvg} {...props} />
}
