// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PoundCircleFilledSvg from '@ant-design/icons-svg/es/asn/PoundCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function PoundCircleFilled(props: IconProps) {
  return <Icon icon={PoundCircleFilledSvg} {...props} />
}
