// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PoundCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/PoundCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PoundCircleOutlined(props: IconProps) {
  return <Icon icon={PoundCircleOutlinedSvg} {...props} />
}
