// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PoundOutlinedSvg from '@ant-design/icons-svg/es/asn/PoundOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PoundOutlined(props: IconProps) {
  return <Icon icon={PoundOutlinedSvg} {...props} />
}
