// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PoundCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/PoundCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function PoundCircleTwoTone(props: IconProps) {
  return <Icon icon={PoundCircleTwoToneSvg} {...props} />
}
