// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PoweroffOutlinedSvg from '@ant-design/icons-svg/es/asn/PoweroffOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PoweroffOutlined(props: IconProps) {
  return <Icon icon={PoweroffOutlinedSvg} {...props} />
}
