// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PrinterOutlinedSvg from '@ant-design/icons-svg/es/asn/PrinterOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PrinterOutlined(props: IconProps) {
  return <Icon icon={PrinterOutlinedSvg} {...props} />
}
