// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PrinterTwoToneSvg from '@ant-design/icons-svg/es/asn/PrinterTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function PrinterTwoTone(props: IconProps) {
  return <Icon icon={PrinterTwoToneSvg} {...props} />
}
