// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PrinterFilledSvg from '@ant-design/icons-svg/es/asn/PrinterFilled'
import { Icon, type IconProps } from '../components/icon'

export function PrinterFilled(props: IconProps) {
  return <Icon icon={PrinterFilledSvg} {...props} />
}
