// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ProductOutlinedSvg from '@ant-design/icons-svg/es/asn/ProductOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ProductOutlined(props: IconProps) {
  return <Icon icon={ProductOutlinedSvg} {...props} />
}
