// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ProductFilledSvg from '@ant-design/icons-svg/es/asn/ProductFilled'
import { Icon, type IconProps } from '../components/icon'

export function ProductFilled(props: IconProps) {
  return <Icon icon={ProductFilledSvg} {...props} />
}
