// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ProfileOutlinedSvg from '@ant-design/icons-svg/es/asn/ProfileOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ProfileOutlined(props: IconProps) {
  return <Icon icon={ProfileOutlinedSvg} {...props} />
}
