// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ProfileTwoToneSvg from '@ant-design/icons-svg/es/asn/ProfileTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function ProfileTwoTone(props: IconProps) {
  return <Icon icon={ProfileTwoToneSvg} {...props} />
}
