// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ProfileFilledSvg from '@ant-design/icons-svg/es/asn/ProfileFilled'
import { Icon, type IconProps } from '../components/icon'

export function ProfileFilled(props: IconProps) {
  return <Icon icon={ProfileFilledSvg} {...props} />
}
