// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ProjectFilledSvg from '@ant-design/icons-svg/es/asn/ProjectFilled'
import { Icon, type IconProps } from '../components/icon'

export function ProjectFilled(props: IconProps) {
  return <Icon icon={ProjectFilledSvg} {...props} />
}
