// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ProjectTwoToneSvg from '@ant-design/icons-svg/es/asn/ProjectTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function ProjectTwoTone(props: IconProps) {
  return <Icon icon={ProjectTwoToneSvg} {...props} />
}
