// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PropertySafetyOutlinedSvg from '@ant-design/icons-svg/es/asn/PropertySafetyOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PropertySafetyOutlined(props: IconProps) {
  return <Icon icon={PropertySafetyOutlinedSvg} {...props} />
}
