// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PropertySafetyFilledSvg from '@ant-design/icons-svg/es/asn/PropertySafetyFilled'
import { Icon, type IconProps } from '../components/icon'

export function PropertySafetyFilled(props: IconProps) {
  return <Icon icon={PropertySafetyFilledSvg} {...props} />
}
