// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PropertySafetyTwoToneSvg from '@ant-design/icons-svg/es/asn/PropertySafetyTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function PropertySafetyTwoTone(props: IconProps) {
  return <Icon icon={PropertySafetyTwoToneSvg} {...props} />
}
