// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PullRequestOutlinedSvg from '@ant-design/icons-svg/es/asn/PullRequestOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PullRequestOutlined(props: IconProps) {
  return <Icon icon={PullRequestOutlinedSvg} {...props} />
}
