// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PushpinFilledSvg from '@ant-design/icons-svg/es/asn/PushpinFilled'
import { Icon, type IconProps } from '../components/icon'

export function PushpinFilled(props: IconProps) {
  return <Icon icon={PushpinFilledSvg} {...props} />
}
