// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PushpinOutlinedSvg from '@ant-design/icons-svg/es/asn/PushpinOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PushpinOutlined(props: IconProps) {
  return <Icon icon={PushpinOutlinedSvg} {...props} />
}
