// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PushpinTwoToneSvg from '@ant-design/icons-svg/es/asn/PushpinTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function PushpinTwoTone(props: IconProps) {
  return <Icon icon={PushpinTwoToneSvg} {...props} />
}
