// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import PythonOutlinedSvg from '@ant-design/icons-svg/es/asn/PythonOutlined'
import { Icon, type IconProps } from '../components/icon'

export function PythonOutlined(props: IconProps) {
  return <Icon icon={PythonOutlinedSvg} {...props} />
}
