// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import QqCircleFilledSvg from '@ant-design/icons-svg/es/asn/QqCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function QqCircleFilled(props: IconProps) {
  return <Icon icon={QqCircleFilledSvg} {...props} />
}
