// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import QqOutlinedSvg from '@ant-design/icons-svg/es/asn/QqOutlined'
import { Icon, type IconProps } from '../components/icon'

export function QqOutlined(props: IconProps) {
  return <Icon icon={QqOutlinedSvg} {...props} />
}
