// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import QqSquareFilledSvg from '@ant-design/icons-svg/es/asn/QqSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function QqSquareFilled(props: IconProps) {
  return <Icon icon={QqSquareFilledSvg} {...props} />
}
