// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import QrcodeOutlinedSvg from '@ant-design/icons-svg/es/asn/QrcodeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function QrcodeOutlined(props: IconProps) {
  return <Icon icon={QrcodeOutlinedSvg} {...props} />
}
