// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import QuestionOutlinedSvg from '@ant-design/icons-svg/es/asn/QuestionOutlined'
import { Icon, type IconProps } from '../components/icon'

export function QuestionOutlined(props: IconProps) {
  return <Icon icon={QuestionOutlinedSvg} {...props} />
}
