// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import QuestionCircleFilledSvg from '@ant-design/icons-svg/es/asn/QuestionCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function QuestionCircleFilled(props: IconProps) {
  return <Icon icon={QuestionCircleFilledSvg} {...props} />
}
