// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import QuestionCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/QuestionCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function QuestionCircleTwoTone(props: IconProps) {
  return <Icon icon={QuestionCircleTwoToneSvg} {...props} />
}
