// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import QuestionCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/QuestionCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function QuestionCircleOutlined(props: IconProps) {
  return <Icon icon={QuestionCircleOutlinedSvg} {...props} />
}
