// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RadarChartOutlinedSvg from '@ant-design/icons-svg/es/asn/RadarChartOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RadarChartOutlined(props: IconProps) {
  return <Icon icon={RadarChartOutlinedSvg} {...props} />
}
