// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RadiusSettingOutlinedSvg from '@ant-design/icons-svg/es/asn/RadiusSettingOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RadiusSettingOutlined(props: IconProps) {
  return <Icon icon={RadiusSettingOutlinedSvg} {...props} />
}
