// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RadiusBottomleftOutlinedSvg from '@ant-design/icons-svg/es/asn/RadiusBottomleftOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RadiusBottomleftOutlined(props: IconProps) {
  return <Icon icon={RadiusBottomleftOutlinedSvg} {...props} />
}
