// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RadiusBottomrightOutlinedSvg from '@ant-design/icons-svg/es/asn/RadiusBottomrightOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RadiusBottomrightOutlined(props: IconProps) {
  return <Icon icon={RadiusBottomrightOutlinedSvg} {...props} />
}
