// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RadiusUprightOutlinedSvg from '@ant-design/icons-svg/es/asn/RadiusUprightOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RadiusUprightOutlined(props: IconProps) {
  return <Icon icon={RadiusUprightOutlinedSvg} {...props} />
}
