// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RadiusUpleftOutlinedSvg from '@ant-design/icons-svg/es/asn/RadiusUpleftOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RadiusUpleftOutlined(props: IconProps) {
  return <Icon icon={RadiusUpleftOutlinedSvg} {...props} />
}
