// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ReadOutlinedSvg from '@ant-design/icons-svg/es/asn/ReadOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ReadOutlined(props: IconProps) {
  return <Icon icon={ReadOutlinedSvg} {...props} />
}
