// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ReadFilledSvg from '@ant-design/icons-svg/es/asn/ReadFilled'
import { Icon, type IconProps } from '../components/icon'

export function ReadFilled(props: IconProps) {
  return <Icon icon={ReadFilledSvg} {...props} />
}
