// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ReconciliationTwoToneSvg from '@ant-design/icons-svg/es/asn/ReconciliationTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function ReconciliationTwoTone(props: IconProps) {
  return <Icon icon={ReconciliationTwoToneSvg} {...props} />
}
