// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ReconciliationFilledSvg from '@ant-design/icons-svg/es/asn/ReconciliationFilled'
import { Icon, type IconProps } from '../components/icon'

export function ReconciliationFilled(props: IconProps) {
  return <Icon icon={ReconciliationFilledSvg} {...props} />
}
