// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ReconciliationOutlinedSvg from '@ant-design/icons-svg/es/asn/ReconciliationOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ReconciliationOutlined(props: IconProps) {
  return <Icon icon={ReconciliationOutlinedSvg} {...props} />
}
