// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RedEnvelopeOutlinedSvg from '@ant-design/icons-svg/es/asn/RedEnvelopeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RedEnvelopeOutlined(props: IconProps) {
  return <Icon icon={RedEnvelopeOutlinedSvg} {...props} />
}
