// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RedEnvelopeTwoToneSvg from '@ant-design/icons-svg/es/asn/RedEnvelopeTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function RedEnvelopeTwoTone(props: IconProps) {
  return <Icon icon={RedEnvelopeTwoToneSvg} {...props} />
}
