// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RedditCircleFilledSvg from '@ant-design/icons-svg/es/asn/RedditCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function RedditCircleFilled(props: IconProps) {
  return <Icon icon={RedditCircleFilledSvg} {...props} />
}
