// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RedditSquareFilledSvg from '@ant-design/icons-svg/es/asn/RedditSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function RedditSquareFilled(props: IconProps) {
  return <Icon icon={RedditSquareFilledSvg} {...props} />
}
