// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RedditOutlinedSvg from '@ant-design/icons-svg/es/asn/RedditOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RedditOutlined(props: IconProps) {
  return <Icon icon={RedditOutlinedSvg} {...props} />
}
