// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RedoOutlinedSvg from '@ant-design/icons-svg/es/asn/RedoOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RedoOutlined(props: IconProps) {
  return <Icon icon={RedoOutlinedSvg} {...props} />
}
