// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ReloadOutlinedSvg from '@ant-design/icons-svg/es/asn/ReloadOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ReloadOutlined(props: IconProps) {
  return <Icon icon={ReloadOutlinedSvg} {...props} />
}
