// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RestFilledSvg from '@ant-design/icons-svg/es/asn/RestFilled'
import { Icon, type IconProps } from '../components/icon'

export function RestFilled(props: IconProps) {
  return <Icon icon={RestFilledSvg} {...props} />
}
