// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RestTwoToneSvg from '@ant-design/icons-svg/es/asn/RestTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function RestTwoTone(props: IconProps) {
  return <Icon icon={RestTwoToneSvg} {...props} />
}
