// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RestOutlinedSvg from '@ant-design/icons-svg/es/asn/RestOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RestOutlined(props: IconProps) {
  return <Icon icon={RestOutlinedSvg} {...props} />
}
