// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RetweetOutlinedSvg from '@ant-design/icons-svg/es/asn/RetweetOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RetweetOutlined(props: IconProps) {
  return <Icon icon={RetweetOutlinedSvg} {...props} />
}
