// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RightCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/RightCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function RightCircleTwoTone(props: IconProps) {
  return <Icon icon={RightCircleTwoToneSvg} {...props} />
}
