// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RightSquareTwoToneSvg from '@ant-design/icons-svg/es/asn/RightSquareTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function RightSquareTwoTone(props: IconProps) {
  return <Icon icon={RightSquareTwoToneSvg} {...props} />
}
