// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RightSquareFilledSvg from '@ant-design/icons-svg/es/asn/RightSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function RightSquareFilled(props: IconProps) {
  return <Icon icon={RightSquareFilledSvg} {...props} />
}
