// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RightCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/RightCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RightCircleOutlined(props: IconProps) {
  return <Icon icon={RightCircleOutlinedSvg} {...props} />
}
