// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RightCircleFilledSvg from '@ant-design/icons-svg/es/asn/RightCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function RightCircleFilled(props: IconProps) {
  return <Icon icon={RightCircleFilledSvg} {...props} />
}
