// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RightOutlinedSvg from '@ant-design/icons-svg/es/asn/RightOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RightOutlined(props: IconProps) {
  return <Icon icon={RightOutlinedSvg} {...props} />
}
