// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RightSquareOutlinedSvg from '@ant-design/icons-svg/es/asn/RightSquareOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RightSquareOutlined(props: IconProps) {
  return <Icon icon={RightSquareOutlinedSvg} {...props} />
}
