// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RiseOutlinedSvg from '@ant-design/icons-svg/es/asn/RiseOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RiseOutlined(props: IconProps) {
  return <Icon icon={RiseOutlinedSvg} {...props} />
}
