// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RobotFilledSvg from '@ant-design/icons-svg/es/asn/RobotFilled'
import { Icon, type IconProps } from '../components/icon'

export function RobotFilled(props: IconProps) {
  return <Icon icon={RobotFilledSvg} {...props} />
}
