// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RobotOutlinedSvg from '@ant-design/icons-svg/es/asn/RobotOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RobotOutlined(props: IconProps) {
  return <Icon icon={RobotOutlinedSvg} {...props} />
}
