// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RocketTwoToneSvg from '@ant-design/icons-svg/es/asn/RocketTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function RocketTwoTone(props: IconProps) {
  return <Icon icon={RocketTwoToneSvg} {...props} />
}
