// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RocketFilledSvg from '@ant-design/icons-svg/es/asn/RocketFilled'
import { Icon, type IconProps } from '../components/icon'

export function RocketFilled(props: IconProps) {
  return <Icon icon={RocketFilledSvg} {...props} />
}
