// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RocketOutlinedSvg from '@ant-design/icons-svg/es/asn/RocketOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RocketOutlined(props: IconProps) {
  return <Icon icon={RocketOutlinedSvg} {...props} />
}
