// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RollbackOutlinedSvg from '@ant-design/icons-svg/es/asn/RollbackOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RollbackOutlined(props: IconProps) {
  return <Icon icon={RollbackOutlinedSvg} {...props} />
}
