// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RotateLeftOutlinedSvg from '@ant-design/icons-svg/es/asn/RotateLeftOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RotateLeftOutlined(props: IconProps) {
  return <Icon icon={RotateLeftOutlinedSvg} {...props} />
}
