// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RotateRightOutlinedSvg from '@ant-design/icons-svg/es/asn/RotateRightOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RotateRightOutlined(props: IconProps) {
  return <Icon icon={RotateRightOutlinedSvg} {...props} />
}
