// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import RubyOutlinedSvg from '@ant-design/icons-svg/es/asn/RubyOutlined'
import { Icon, type IconProps } from '../components/icon'

export function RubyOutlined(props: IconProps) {
  return <Icon icon={RubyOutlinedSvg} {...props} />
}
