// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SafetyCertificateTwoToneSvg from '@ant-design/icons-svg/es/asn/SafetyCertificateTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function SafetyCertificateTwoTone(props: IconProps) {
  return <Icon icon={SafetyCertificateTwoToneSvg} {...props} />
}
