// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SafetyOutlinedSvg from '@ant-design/icons-svg/es/asn/SafetyOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SafetyOutlined(props: IconProps) {
  return <Icon icon={SafetyOutlinedSvg} {...props} />
}
