// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SafetyCertificateFilledSvg from '@ant-design/icons-svg/es/asn/SafetyCertificateFilled'
import { Icon, type IconProps } from '../components/icon'

export function SafetyCertificateFilled(props: IconProps) {
  return <Icon icon={SafetyCertificateFilledSvg} {...props} />
}
