// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SafetyCertificateOutlinedSvg from '@ant-design/icons-svg/es/asn/SafetyCertificateOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SafetyCertificateOutlined(props: IconProps) {
  return <Icon icon={SafetyCertificateOutlinedSvg} {...props} />
}
