// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SaveTwoToneSvg from '@ant-design/icons-svg/es/asn/SaveTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function SaveTwoTone(props: IconProps) {
  return <Icon icon={SaveTwoToneSvg} {...props} />
}
