// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SaveFilledSvg from '@ant-design/icons-svg/es/asn/SaveFilled'
import { Icon, type IconProps } from '../components/icon'

export function SaveFilled(props: IconProps) {
  return <Icon icon={SaveFilledSvg} {...props} />
}
