// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SaveOutlinedSvg from '@ant-design/icons-svg/es/asn/SaveOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SaveOutlined(props: IconProps) {
  return <Icon icon={SaveOutlinedSvg} {...props} />
}
