// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ScanOutlinedSvg from '@ant-design/icons-svg/es/asn/ScanOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ScanOutlined(props: IconProps) {
  return <Icon icon={ScanOutlinedSvg} {...props} />
}
