// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ScheduleOutlinedSvg from '@ant-design/icons-svg/es/asn/ScheduleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ScheduleOutlined(props: IconProps) {
  return <Icon icon={ScheduleOutlinedSvg} {...props} />
}
