// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ScheduleFilledSvg from '@ant-design/icons-svg/es/asn/ScheduleFilled'
import { Icon, type IconProps } from '../components/icon'

export function ScheduleFilled(props: IconProps) {
  return <Icon icon={ScheduleFilledSvg} {...props} />
}
