// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ScheduleTwoToneSvg from '@ant-design/icons-svg/es/asn/ScheduleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function ScheduleTwoTone(props: IconProps) {
  return <Icon icon={ScheduleTwoToneSvg} {...props} />
}
