// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ScissorOutlinedSvg from '@ant-design/icons-svg/es/asn/ScissorOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ScissorOutlined(props: IconProps) {
  return <Icon icon={ScissorOutlinedSvg} {...props} />
}
