// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SearchOutlinedSvg from '@ant-design/icons-svg/es/asn/SearchOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SearchOutlined(props: IconProps) {
  return <Icon icon={SearchOutlinedSvg} {...props} />
}
