// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SecurityScanFilledSvg from '@ant-design/icons-svg/es/asn/SecurityScanFilled'
import { Icon, type IconProps } from '../components/icon'

export function SecurityScanFilled(props: IconProps) {
  return <Icon icon={SecurityScanFilledSvg} {...props} />
}
