// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SecurityScanOutlinedSvg from '@ant-design/icons-svg/es/asn/SecurityScanOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SecurityScanOutlined(props: IconProps) {
  return <Icon icon={SecurityScanOutlinedSvg} {...props} />
}
