// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SecurityScanTwoToneSvg from '@ant-design/icons-svg/es/asn/SecurityScanTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function SecurityScanTwoTone(props: IconProps) {
  return <Icon icon={SecurityScanTwoToneSvg} {...props} />
}
