// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SelectOutlinedSvg from '@ant-design/icons-svg/es/asn/SelectOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SelectOutlined(props: IconProps) {
  return <Icon icon={SelectOutlinedSvg} {...props} />
}
