// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SendOutlinedSvg from '@ant-design/icons-svg/es/asn/SendOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SendOutlined(props: IconProps) {
  return <Icon icon={SendOutlinedSvg} {...props} />
}
