// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SettingTwoToneSvg from '@ant-design/icons-svg/es/asn/SettingTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function SettingTwoTone(props: IconProps) {
  return <Icon icon={SettingTwoToneSvg} {...props} />
}
