// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SettingFilledSvg from '@ant-design/icons-svg/es/asn/SettingFilled'
import { Icon, type IconProps } from '../components/icon'

export function SettingFilled(props: IconProps) {
  return <Icon icon={SettingFilledSvg} {...props} />
}
