// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SettingOutlinedSvg from '@ant-design/icons-svg/es/asn/SettingOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SettingOutlined(props: IconProps) {
  return <Icon icon={SettingOutlinedSvg} {...props} />
}
