// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ShakeOutlinedSvg from '@ant-design/icons-svg/es/asn/ShakeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ShakeOutlined(props: IconProps) {
  return <Icon icon={ShakeOutlinedSvg} {...props} />
}
