// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ShareAltOutlinedSvg from '@ant-design/icons-svg/es/asn/ShareAltOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ShareAltOutlined(props: IconProps) {
  return <Icon icon={ShareAltOutlinedSvg} {...props} />
}
