// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ShoppingFilledSvg from '@ant-design/icons-svg/es/asn/ShoppingFilled'
import { Icon, type IconProps } from '../components/icon'

export function ShoppingFilled(props: IconProps) {
  return <Icon icon={ShoppingFilledSvg} {...props} />
}
