// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ShopFilledSvg from '@ant-design/icons-svg/es/asn/ShopFilled'
import { Icon, type IconProps } from '../components/icon'

export function ShopFilled(props: IconProps) {
  return <Icon icon={ShopFilledSvg} {...props} />
}
