// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ShopTwoToneSvg from '@ant-design/icons-svg/es/asn/ShopTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function ShopTwoTone(props: IconProps) {
  return <Icon icon={ShopTwoToneSvg} {...props} />
}
