// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ShoppingTwoToneSvg from '@ant-design/icons-svg/es/asn/ShoppingTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function ShoppingTwoTone(props: IconProps) {
  return <Icon icon={ShoppingTwoToneSvg} {...props} />
}
