// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ShopOutlinedSvg from '@ant-design/icons-svg/es/asn/ShopOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ShopOutlined(props: IconProps) {
  return <Icon icon={ShopOutlinedSvg} {...props} />
}
