// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ShoppingOutlinedSvg from '@ant-design/icons-svg/es/asn/ShoppingOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ShoppingOutlined(props: IconProps) {
  return <Icon icon={ShoppingOutlinedSvg} {...props} />
}
