// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ShoppingCartOutlinedSvg from '@ant-design/icons-svg/es/asn/ShoppingCartOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ShoppingCartOutlined(props: IconProps) {
  return <Icon icon={ShoppingCartOutlinedSvg} {...props} />
}
