// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ShrinkOutlinedSvg from '@ant-design/icons-svg/es/asn/ShrinkOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ShrinkOutlined(props: IconProps) {
  return <Icon icon={ShrinkOutlinedSvg} {...props} />
}
