// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SignalFilledSvg from '@ant-design/icons-svg/es/asn/SignalFilled'
import { Icon, type IconProps } from '../components/icon'

export function SignalFilled(props: IconProps) {
  return <Icon icon={SignalFilledSvg} {...props} />
}
