// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SignatureOutlinedSvg from '@ant-design/icons-svg/es/asn/SignatureOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SignatureOutlined(props: IconProps) {
  return <Icon icon={SignatureOutlinedSvg} {...props} />
}
