// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SignatureFilledSvg from '@ant-design/icons-svg/es/asn/SignatureFilled'
import { Icon, type IconProps } from '../components/icon'

export function SignatureFilled(props: IconProps) {
  return <Icon icon={SignatureFilledSvg} {...props} />
}
