// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SisternodeOutlinedSvg from '@ant-design/icons-svg/es/asn/SisternodeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SisternodeOutlined(props: IconProps) {
  return <Icon icon={SisternodeOutlinedSvg} {...props} />
}
