// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SketchCircleFilledSvg from '@ant-design/icons-svg/es/asn/SketchCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function SketchCircleFilled(props: IconProps) {
  return <Icon icon={SketchCircleFilledSvg} {...props} />
}
