// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SketchOutlinedSvg from '@ant-design/icons-svg/es/asn/SketchOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SketchOutlined(props: IconProps) {
  return <Icon icon={SketchOutlinedSvg} {...props} />
}
