// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SketchSquareFilledSvg from '@ant-design/icons-svg/es/asn/SketchSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function SketchSquareFilled(props: IconProps) {
  return <Icon icon={SketchSquareFilledSvg} {...props} />
}
