// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SkinFilledSvg from '@ant-design/icons-svg/es/asn/SkinFilled'
import { Icon, type IconProps } from '../components/icon'

export function SkinFilled(props: IconProps) {
  return <Icon icon={SkinFilledSvg} {...props} />
}
