// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SkinTwoToneSvg from '@ant-design/icons-svg/es/asn/SkinTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function SkinTwoTone(props: IconProps) {
  return <Icon icon={SkinTwoToneSvg} {...props} />
}
