// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SkinOutlinedSvg from '@ant-design/icons-svg/es/asn/SkinOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SkinOutlined(props: IconProps) {
  return <Icon icon={SkinOutlinedSvg} {...props} />
}
