// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SkypeFilledSvg from '@ant-design/icons-svg/es/asn/SkypeFilled'
import { Icon, type IconProps } from '../components/icon'

export function SkypeFilled(props: IconProps) {
  return <Icon icon={SkypeFilledSvg} {...props} />
}
