// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SkypeOutlinedSvg from '@ant-design/icons-svg/es/asn/SkypeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SkypeOutlined(props: IconProps) {
  return <Icon icon={SkypeOutlinedSvg} {...props} />
}
