// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SlackSquareOutlinedSvg from '@ant-design/icons-svg/es/asn/SlackSquareOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SlackSquareOutlined(props: IconProps) {
  return <Icon icon={SlackSquareOutlinedSvg} {...props} />
}
