// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SlackSquareFilledSvg from '@ant-design/icons-svg/es/asn/SlackSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function SlackSquareFilled(props: IconProps) {
  return <Icon icon={SlackSquareFilledSvg} {...props} />
}
