// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SlackOutlinedSvg from '@ant-design/icons-svg/es/asn/SlackOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SlackOutlined(props: IconProps) {
  return <Icon icon={SlackOutlinedSvg} {...props} />
}
