// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SlackCircleFilledSvg from '@ant-design/icons-svg/es/asn/SlackCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function SlackCircleFilled(props: IconProps) {
  return <Icon icon={SlackCircleFilledSvg} {...props} />
}
