// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SlidersOutlinedSvg from '@ant-design/icons-svg/es/asn/SlidersOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SlidersOutlined(props: IconProps) {
  return <Icon icon={SlidersOutlinedSvg} {...props} />
}
