// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SlidersFilledSvg from '@ant-design/icons-svg/es/asn/SlidersFilled'
import { Icon, type IconProps } from '../components/icon'

export function SlidersFilled(props: IconProps) {
  return <Icon icon={SlidersFilledSvg} {...props} />
}
