// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SlidersTwoToneSvg from '@ant-design/icons-svg/es/asn/SlidersTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function SlidersTwoTone(props: IconProps) {
  return <Icon icon={SlidersTwoToneSvg} {...props} />
}
