// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SmallDashOutlinedSvg from '@ant-design/icons-svg/es/asn/SmallDashOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SmallDashOutlined(props: IconProps) {
  return <Icon icon={SmallDashOutlinedSvg} {...props} />
}
