// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SmileFilledSvg from '@ant-design/icons-svg/es/asn/SmileFilled'
import { Icon, type IconProps } from '../components/icon'

export function SmileFilled(props: IconProps) {
  return <Icon icon={SmileFilledSvg} {...props} />
}
