// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SmileTwoToneSvg from '@ant-design/icons-svg/es/asn/SmileTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function SmileTwoTone(props: IconProps) {
  return <Icon icon={SmileTwoToneSvg} {...props} />
}
