// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SmileOutlinedSvg from '@ant-design/icons-svg/es/asn/SmileOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SmileOutlined(props: IconProps) {
  return <Icon icon={SmileOutlinedSvg} {...props} />
}
