// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SnippetsFilledSvg from '@ant-design/icons-svg/es/asn/SnippetsFilled'
import { Icon, type IconProps } from '../components/icon'

export function SnippetsFilled(props: IconProps) {
  return <Icon icon={SnippetsFilledSvg} {...props} />
}
