// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SnippetsTwoToneSvg from '@ant-design/icons-svg/es/asn/SnippetsTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function SnippetsTwoTone(props: IconProps) {
  return <Icon icon={SnippetsTwoToneSvg} {...props} />
}
