// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SnippetsOutlinedSvg from '@ant-design/icons-svg/es/asn/SnippetsOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SnippetsOutlined(props: IconProps) {
  return <Icon icon={SnippetsOutlinedSvg} {...props} />
}
