// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SolutionOutlinedSvg from '@ant-design/icons-svg/es/asn/SolutionOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SolutionOutlined(props: IconProps) {
  return <Icon icon={SolutionOutlinedSvg} {...props} />
}
