// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SortDescendingOutlinedSvg from '@ant-design/icons-svg/es/asn/SortDescendingOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SortDescendingOutlined(props: IconProps) {
  return <Icon icon={SortDescendingOutlinedSvg} {...props} />
}
