// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SortAscendingOutlinedSvg from '@ant-design/icons-svg/es/asn/SortAscendingOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SortAscendingOutlined(props: IconProps) {
  return <Icon icon={SortAscendingOutlinedSvg} {...props} />
}
