// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SoundTwoToneSvg from '@ant-design/icons-svg/es/asn/SoundTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function SoundTwoTone(props: IconProps) {
  return <Icon icon={SoundTwoToneSvg} {...props} />
}
