// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SoundFilledSvg from '@ant-design/icons-svg/es/asn/SoundFilled'
import { Icon, type IconProps } from '../components/icon'

export function SoundFilled(props: IconProps) {
  return <Icon icon={SoundFilledSvg} {...props} />
}
