// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SoundOutlinedSvg from '@ant-design/icons-svg/es/asn/SoundOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SoundOutlined(props: IconProps) {
  return <Icon icon={SoundOutlinedSvg} {...props} />
}
