// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SplitCellsOutlinedSvg from '@ant-design/icons-svg/es/asn/SplitCellsOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SplitCellsOutlined(props: IconProps) {
  return <Icon icon={SplitCellsOutlinedSvg} {...props} />
}
