// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SpotifyFilledSvg from '@ant-design/icons-svg/es/asn/SpotifyFilled'
import { Icon, type IconProps } from '../components/icon'

export function SpotifyFilled(props: IconProps) {
  return <Icon icon={SpotifyFilledSvg} {...props} />
}
