// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SpotifyOutlinedSvg from '@ant-design/icons-svg/es/asn/SpotifyOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SpotifyOutlined(props: IconProps) {
  return <Icon icon={SpotifyOutlinedSvg} {...props} />
}
