// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import StarOutlinedSvg from '@ant-design/icons-svg/es/asn/StarOutlined'
import { Icon, type IconProps } from '../components/icon'

export function StarOutlined(props: IconProps) {
  return <Icon icon={StarOutlinedSvg} {...props} />
}
