// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import StarFilledSvg from '@ant-design/icons-svg/es/asn/StarFilled'
import { Icon, type IconProps } from '../components/icon'

export function StarFilled(props: IconProps) {
  return <Icon icon={StarFilledSvg} {...props} />
}
