// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import StarTwoToneSvg from '@ant-design/icons-svg/es/asn/StarTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function StarTwoTone(props: IconProps) {
  return <Icon icon={StarTwoToneSvg} {...props} />
}
