// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import StepForwardFilledSvg from '@ant-design/icons-svg/es/asn/StepForwardFilled'
import { Icon, type IconProps } from '../components/icon'

export function StepForwardFilled(props: IconProps) {
  return <Icon icon={StepForwardFilledSvg} {...props} />
}
