// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import StepBackwardFilledSvg from '@ant-design/icons-svg/es/asn/StepBackwardFilled'
import { Icon, type IconProps } from '../components/icon'

export function StepBackwardFilled(props: IconProps) {
  return <Icon icon={StepBackwardFilledSvg} {...props} />
}
