// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import StepForwardOutlinedSvg from '@ant-design/icons-svg/es/asn/StepForwardOutlined'
import { Icon, type IconProps } from '../components/icon'

export function StepForwardOutlined(props: IconProps) {
  return <Icon icon={StepForwardOutlinedSvg} {...props} />
}
