// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import StepBackwardOutlinedSvg from '@ant-design/icons-svg/es/asn/StepBackwardOutlined'
import { Icon, type IconProps } from '../components/icon'

export function StepBackwardOutlined(props: IconProps) {
  return <Icon icon={StepBackwardOutlinedSvg} {...props} />
}
