// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import StockOutlinedSvg from '@ant-design/icons-svg/es/asn/StockOutlined'
import { Icon, type IconProps } from '../components/icon'

export function StockOutlined(props: IconProps) {
  return <Icon icon={StockOutlinedSvg} {...props} />
}
