// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import StopTwoToneSvg from '@ant-design/icons-svg/es/asn/StopTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function StopTwoTone(props: IconProps) {
  return <Icon icon={StopTwoToneSvg} {...props} />
}
