// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import StopOutlinedSvg from '@ant-design/icons-svg/es/asn/StopOutlined'
import { Icon, type IconProps } from '../components/icon'

export function StopOutlined(props: IconProps) {
  return <Icon icon={StopOutlinedSvg} {...props} />
}
