// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import StopFilledSvg from '@ant-design/icons-svg/es/asn/StopFilled'
import { Icon, type IconProps } from '../components/icon'

export function StopFilled(props: IconProps) {
  return <Icon icon={StopFilledSvg} {...props} />
}
