// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import StrikethroughOutlinedSvg from '@ant-design/icons-svg/es/asn/StrikethroughOutlined'
import { Icon, type IconProps } from '../components/icon'

export function StrikethroughOutlined(props: IconProps) {
  return <Icon icon={StrikethroughOutlinedSvg} {...props} />
}
