// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SubnodeOutlinedSvg from '@ant-design/icons-svg/es/asn/SubnodeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SubnodeOutlined(props: IconProps) {
  return <Icon icon={SubnodeOutlinedSvg} {...props} />
}
