// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SunFilledSvg from '@ant-design/icons-svg/es/asn/SunFilled'
import { Icon, type IconProps } from '../components/icon'

export function SunFilled(props: IconProps) {
  return <Icon icon={SunFilledSvg} {...props} />
}
