// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SunOutlinedSvg from '@ant-design/icons-svg/es/asn/SunOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SunOutlined(props: IconProps) {
  return <Icon icon={SunOutlinedSvg} {...props} />
}
