// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SwapRightOutlinedSvg from '@ant-design/icons-svg/es/asn/SwapRightOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SwapRightOutlined(props: IconProps) {
  return <Icon icon={SwapRightOutlinedSvg} {...props} />
}
