// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SwapOutlinedSvg from '@ant-design/icons-svg/es/asn/SwapOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SwapOutlined(props: IconProps) {
  return <Icon icon={SwapOutlinedSvg} {...props} />
}
