// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SwapLeftOutlinedSvg from '@ant-design/icons-svg/es/asn/SwapLeftOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SwapLeftOutlined(props: IconProps) {
  return <Icon icon={SwapLeftOutlinedSvg} {...props} />
}
