// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SwitcherTwoToneSvg from '@ant-design/icons-svg/es/asn/SwitcherTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function SwitcherTwoTone(props: IconProps) {
  return <Icon icon={SwitcherTwoToneSvg} {...props} />
}
