// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SwitcherFilledSvg from '@ant-design/icons-svg/es/asn/SwitcherFilled'
import { Icon, type IconProps } from '../components/icon'

export function SwitcherFilled(props: IconProps) {
  return <Icon icon={SwitcherFilledSvg} {...props} />
}
