// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SwitcherOutlinedSvg from '@ant-design/icons-svg/es/asn/SwitcherOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SwitcherOutlined(props: IconProps) {
  return <Icon icon={SwitcherOutlinedSvg} {...props} />
}
