// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import SyncOutlinedSvg from '@ant-design/icons-svg/es/asn/SyncOutlined'
import { Icon, type IconProps } from '../components/icon'

export function SyncOutlined(props: IconProps) {
  return <Icon icon={SyncOutlinedSvg} {...props} />
}
