// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TabletFilledSvg from '@ant-design/icons-svg/es/asn/TabletFilled'
import { Icon, type IconProps } from '../components/icon'

export function TabletFilled(props: IconProps) {
  return <Icon icon={TabletFilledSvg} {...props} />
}
