// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TabletTwoToneSvg from '@ant-design/icons-svg/es/asn/TabletTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function TabletTwoTone(props: IconProps) {
  return <Icon icon={TabletTwoToneSvg} {...props} />
}
