// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TabletOutlinedSvg from '@ant-design/icons-svg/es/asn/TabletOutlined'
import { Icon, type IconProps } from '../components/icon'

export function TabletOutlined(props: IconProps) {
  return <Icon icon={TabletOutlinedSvg} {...props} />
}
