// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TableOutlinedSvg from '@ant-design/icons-svg/es/asn/TableOutlined'
import { Icon, type IconProps } from '../components/icon'

export function TableOutlined(props: IconProps) {
  return <Icon icon={TableOutlinedSvg} {...props} />
}
