// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TagOutlinedSvg from '@ant-design/icons-svg/es/asn/TagOutlined'
import { Icon, type IconProps } from '../components/icon'

export function TagOutlined(props: IconProps) {
  return <Icon icon={TagOutlinedSvg} {...props} />
}
