// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TagFilledSvg from '@ant-design/icons-svg/es/asn/TagFilled'
import { Icon, type IconProps } from '../components/icon'

export function TagFilled(props: IconProps) {
  return <Icon icon={TagFilledSvg} {...props} />
}
