// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TagTwoToneSvg from '@ant-design/icons-svg/es/asn/TagTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function TagTwoTone(props: IconProps) {
  return <Icon icon={TagTwoToneSvg} {...props} />
}
