// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TagsOutlinedSvg from '@ant-design/icons-svg/es/asn/TagsOutlined'
import { Icon, type IconProps } from '../components/icon'

export function TagsOutlined(props: IconProps) {
  return <Icon icon={TagsOutlinedSvg} {...props} />
}
