// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TagsFilledSvg from '@ant-design/icons-svg/es/asn/TagsFilled'
import { Icon, type IconProps } from '../components/icon'

export function TagsFilled(props: IconProps) {
  return <Icon icon={TagsFilledSvg} {...props} />
}
