// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TagsTwoToneSvg from '@ant-design/icons-svg/es/asn/TagsTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function TagsTwoTone(props: IconProps) {
  return <Icon icon={TagsTwoToneSvg} {...props} />
}
