// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TaobaoCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/TaobaoCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function TaobaoCircleOutlined(props: IconProps) {
  return <Icon icon={TaobaoCircleOutlinedSvg} {...props} />
}
