// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TaobaoCircleFilledSvg from '@ant-design/icons-svg/es/asn/TaobaoCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function TaobaoCircleFilled(props: IconProps) {
  return <Icon icon={TaobaoCircleFilledSvg} {...props} />
}
