// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TaobaoOutlinedSvg from '@ant-design/icons-svg/es/asn/TaobaoOutlined'
import { Icon, type IconProps } from '../components/icon'

export function TaobaoOutlined(props: IconProps) {
  return <Icon icon={TaobaoOutlinedSvg} {...props} />
}
