// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TaobaoSquareFilledSvg from '@ant-design/icons-svg/es/asn/TaobaoSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function TaobaoSquareFilled(props: IconProps) {
  return <Icon icon={TaobaoSquareFilledSvg} {...props} />
}
