// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TeamOutlinedSvg from '@ant-design/icons-svg/es/asn/TeamOutlined'
import { Icon, type IconProps } from '../components/icon'

export function TeamOutlined(props: IconProps) {
  return <Icon icon={TeamOutlinedSvg} {...props} />
}
