// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ThunderboltFilledSvg from '@ant-design/icons-svg/es/asn/ThunderboltFilled'
import { Icon, type IconProps } from '../components/icon'

export function ThunderboltFilled(props: IconProps) {
  return <Icon icon={ThunderboltFilledSvg} {...props} />
}
