// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ThunderboltOutlinedSvg from '@ant-design/icons-svg/es/asn/ThunderboltOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ThunderboltOutlined(props: IconProps) {
  return <Icon icon={ThunderboltOutlinedSvg} {...props} />
}
