// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ThunderboltTwoToneSvg from '@ant-design/icons-svg/es/asn/ThunderboltTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function ThunderboltTwoTone(props: IconProps) {
  return <Icon icon={ThunderboltTwoToneSvg} {...props} />
}
