// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TikTokFilledSvg from '@ant-design/icons-svg/es/asn/TikTokFilled'
import { Icon, type IconProps } from '../components/icon'

export function TikTokFilled(props: IconProps) {
  return <Icon icon={TikTokFilledSvg} {...props} />
}
