// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TikTokOutlinedSvg from '@ant-design/icons-svg/es/asn/TikTokOutlined'
import { Icon, type IconProps } from '../components/icon'

export function TikTokOutlined(props: IconProps) {
  return <Icon icon={TikTokOutlinedSvg} {...props} />
}
