// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ToTopOutlinedSvg from '@ant-design/icons-svg/es/asn/ToTopOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ToTopOutlined(props: IconProps) {
  return <Icon icon={ToTopOutlinedSvg} {...props} />
}
