// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ToolOutlinedSvg from '@ant-design/icons-svg/es/asn/ToolOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ToolOutlined(props: IconProps) {
  return <Icon icon={ToolOutlinedSvg} {...props} />
}
