// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ToolFilledSvg from '@ant-design/icons-svg/es/asn/ToolFilled'
import { Icon, type IconProps } from '../components/icon'

export function ToolFilled(props: IconProps) {
  return <Icon icon={ToolFilledSvg} {...props} />
}
