// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ToolTwoToneSvg from '@ant-design/icons-svg/es/asn/ToolTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function ToolTwoTone(props: IconProps) {
  return <Icon icon={ToolTwoToneSvg} {...props} />
}
