// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TrademarkOutlinedSvg from '@ant-design/icons-svg/es/asn/TrademarkOutlined'
import { Icon, type IconProps } from '../components/icon'

export function TrademarkOutlined(props: IconProps) {
  return <Icon icon={TrademarkOutlinedSvg} {...props} />
}
