// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TrademarkCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/TrademarkCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function TrademarkCircleTwoTone(props: IconProps) {
  return <Icon icon={TrademarkCircleTwoToneSvg} {...props} />
}
