// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TrademarkCircleFilledSvg from '@ant-design/icons-svg/es/asn/TrademarkCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function TrademarkCircleFilled(props: IconProps) {
  return <Icon icon={TrademarkCircleFilledSvg} {...props} />
}
