// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TrademarkCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/TrademarkCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function TrademarkCircleOutlined(props: IconProps) {
  return <Icon icon={TrademarkCircleOutlinedSvg} {...props} />
}
