// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TranslationOutlinedSvg from '@ant-design/icons-svg/es/asn/TranslationOutlined'
import { Icon, type IconProps } from '../components/icon'

export function TranslationOutlined(props: IconProps) {
  return <Icon icon={TranslationOutlinedSvg} {...props} />
}
