// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TransactionOutlinedSvg from '@ant-design/icons-svg/es/asn/TransactionOutlined'
import { Icon, type IconProps } from '../components/icon'

export function TransactionOutlined(props: IconProps) {
  return <Icon icon={TransactionOutlinedSvg} {...props} />
}
