// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TrophyFilledSvg from '@ant-design/icons-svg/es/asn/TrophyFilled'
import { Icon, type IconProps } from '../components/icon'

export function TrophyFilled(props: IconProps) {
  return <Icon icon={TrophyFilledSvg} {...props} />
}
