// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TrophyOutlinedSvg from '@ant-design/icons-svg/es/asn/TrophyOutlined'
import { Icon, type IconProps } from '../components/icon'

export function TrophyOutlined(props: IconProps) {
  return <Icon icon={TrophyOutlinedSvg} {...props} />
}
