// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TrophyTwoToneSvg from '@ant-design/icons-svg/es/asn/TrophyTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function TrophyTwoTone(props: IconProps) {
  return <Icon icon={TrophyTwoToneSvg} {...props} />
}
