// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TruckOutlinedSvg from '@ant-design/icons-svg/es/asn/TruckOutlined'
import { Icon, type IconProps } from '../components/icon'

export function TruckOutlined(props: IconProps) {
  return <Icon icon={TruckOutlinedSvg} {...props} />
}
