// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TruckFilledSvg from '@ant-design/icons-svg/es/asn/TruckFilled'
import { Icon, type IconProps } from '../components/icon'

export function TruckFilled(props: IconProps) {
  return <Icon icon={TruckFilledSvg} {...props} />
}
