// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TwitterOutlinedSvg from '@ant-design/icons-svg/es/asn/TwitterOutlined'
import { Icon, type IconProps } from '../components/icon'

export function TwitterOutlined(props: IconProps) {
  return <Icon icon={TwitterOutlinedSvg} {...props} />
}
