// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TwitchFilledSvg from '@ant-design/icons-svg/es/asn/TwitchFilled'
import { Icon, type IconProps } from '../components/icon'

export function TwitchFilled(props: IconProps) {
  return <Icon icon={TwitchFilledSvg} {...props} />
}
