// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TwitterSquareFilledSvg from '@ant-design/icons-svg/es/asn/TwitterSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function TwitterSquareFilled(props: IconProps) {
  return <Icon icon={TwitterSquareFilledSvg} {...props} />
}
