// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TwitterCircleFilledSvg from '@ant-design/icons-svg/es/asn/TwitterCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function TwitterCircleFilled(props: IconProps) {
  return <Icon icon={TwitterCircleFilledSvg} {...props} />
}
