// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import TwitchOutlinedSvg from '@ant-design/icons-svg/es/asn/TwitchOutlined'
import { Icon, type IconProps } from '../components/icon'

export function TwitchOutlined(props: IconProps) {
  return <Icon icon={TwitchOutlinedSvg} {...props} />
}
