// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UnderlineOutlinedSvg from '@ant-design/icons-svg/es/asn/UnderlineOutlined'
import { Icon, type IconProps } from '../components/icon'

export function UnderlineOutlined(props: IconProps) {
  return <Icon icon={UnderlineOutlinedSvg} {...props} />
}
