// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UndoOutlinedSvg from '@ant-design/icons-svg/es/asn/UndoOutlined'
import { Icon, type IconProps } from '../components/icon'

export function UndoOutlined(props: IconProps) {
  return <Icon icon={UndoOutlinedSvg} {...props} />
}
