// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UngroupOutlinedSvg from '@ant-design/icons-svg/es/asn/UngroupOutlined'
import { Icon, type IconProps } from '../components/icon'

export function UngroupOutlined(props: IconProps) {
  return <Icon icon={UngroupOutlinedSvg} {...props} />
}
