// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UnlockTwoToneSvg from '@ant-design/icons-svg/es/asn/UnlockTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function UnlockTwoTone(props: IconProps) {
  return <Icon icon={UnlockTwoToneSvg} {...props} />
}
