// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UnlockOutlinedSvg from '@ant-design/icons-svg/es/asn/UnlockOutlined'
import { Icon, type IconProps } from '../components/icon'

export function UnlockOutlined(props: IconProps) {
  return <Icon icon={UnlockOutlinedSvg} {...props} />
}
