// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UnlockFilledSvg from '@ant-design/icons-svg/es/asn/UnlockFilled'
import { Icon, type IconProps } from '../components/icon'

export function UnlockFilled(props: IconProps) {
  return <Icon icon={UnlockFilledSvg} {...props} />
}
