// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UnorderedListOutlinedSvg from '@ant-design/icons-svg/es/asn/UnorderedListOutlined'
import { Icon, type IconProps } from '../components/icon'

export function UnorderedListOutlined(props: IconProps) {
  return <Icon icon={UnorderedListOutlinedSvg} {...props} />
}
