// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UpCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/UpCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function UpCircleOutlined(props: IconProps) {
  return <Icon icon={UpCircleOutlinedSvg} {...props} />
}
