// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UpCircleTwoToneSvg from '@ant-design/icons-svg/es/asn/UpCircleTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function UpCircleTwoTone(props: IconProps) {
  return <Icon icon={UpCircleTwoToneSvg} {...props} />
}
