// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UpCircleFilledSvg from '@ant-design/icons-svg/es/asn/UpCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function UpCircleFilled(props: IconProps) {
  return <Icon icon={UpCircleFilledSvg} {...props} />
}
