// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UpOutlinedSvg from '@ant-design/icons-svg/es/asn/UpOutlined'
import { Icon, type IconProps } from '../components/icon'

export function UpOutlined(props: IconProps) {
  return <Icon icon={UpOutlinedSvg} {...props} />
}
