// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UpSquareFilledSvg from '@ant-design/icons-svg/es/asn/UpSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function UpSquareFilled(props: IconProps) {
  return <Icon icon={UpSquareFilledSvg} {...props} />
}
