// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UpSquareOutlinedSvg from '@ant-design/icons-svg/es/asn/UpSquareOutlined'
import { Icon, type IconProps } from '../components/icon'

export function UpSquareOutlined(props: IconProps) {
  return <Icon icon={UpSquareOutlinedSvg} {...props} />
}
