// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UpSquareTwoToneSvg from '@ant-design/icons-svg/es/asn/UpSquareTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function UpSquareTwoTone(props: IconProps) {
  return <Icon icon={UpSquareTwoToneSvg} {...props} />
}
