// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UploadOutlinedSvg from '@ant-design/icons-svg/es/asn/UploadOutlined'
import { Icon, type IconProps } from '../components/icon'

export function UploadOutlined(props: IconProps) {
  return <Icon icon={UploadOutlinedSvg} {...props} />
}
