// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UsbOutlinedSvg from '@ant-design/icons-svg/es/asn/UsbOutlined'
import { Icon, type IconProps } from '../components/icon'

export function UsbOutlined(props: IconProps) {
  return <Icon icon={UsbOutlinedSvg} {...props} />
}
