// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UsbTwoToneSvg from '@ant-design/icons-svg/es/asn/UsbTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function UsbTwoTone(props: IconProps) {
  return <Icon icon={UsbTwoToneSvg} {...props} />
}
