// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UsbFilledSvg from '@ant-design/icons-svg/es/asn/UsbFilled'
import { Icon, type IconProps } from '../components/icon'

export function UsbFilled(props: IconProps) {
  return <Icon icon={UsbFilledSvg} {...props} />
}
