// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UserAddOutlinedSvg from '@ant-design/icons-svg/es/asn/UserAddOutlined'
import { Icon, type IconProps } from '../components/icon'

export function UserAddOutlined(props: IconProps) {
  return <Icon icon={UserAddOutlinedSvg} {...props} />
}
