// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UserDeleteOutlinedSvg from '@ant-design/icons-svg/es/asn/UserDeleteOutlined'
import { Icon, type IconProps } from '../components/icon'

export function UserDeleteOutlined(props: IconProps) {
  return <Icon icon={UserDeleteOutlinedSvg} {...props} />
}
