// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UsergroupAddOutlinedSvg from '@ant-design/icons-svg/es/asn/UsergroupAddOutlined'
import { Icon, type IconProps } from '../components/icon'

export function UsergroupAddOutlined(props: IconProps) {
  return <Icon icon={UsergroupAddOutlinedSvg} {...props} />
}
