// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UsergroupDeleteOutlinedSvg from '@ant-design/icons-svg/es/asn/UsergroupDeleteOutlined'
import { Icon, type IconProps } from '../components/icon'

export function UsergroupDeleteOutlined(props: IconProps) {
  return <Icon icon={UsergroupDeleteOutlinedSvg} {...props} />
}
