// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UserOutlinedSvg from '@ant-design/icons-svg/es/asn/UserOutlined'
import { Icon, type IconProps } from '../components/icon'

export function UserOutlined(props: IconProps) {
  return <Icon icon={UserOutlinedSvg} {...props} />
}
