// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import UserSwitchOutlinedSvg from '@ant-design/icons-svg/es/asn/UserSwitchOutlined'
import { Icon, type IconProps } from '../components/icon'

export function UserSwitchOutlined(props: IconProps) {
  return <Icon icon={UserSwitchOutlinedSvg} {...props} />
}
