// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import VerifiedOutlinedSvg from '@ant-design/icons-svg/es/asn/VerifiedOutlined'
import { Icon, type IconProps } from '../components/icon'

export function VerifiedOutlined(props: IconProps) {
  return <Icon icon={VerifiedOutlinedSvg} {...props} />
}
