// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import VerticalLeftOutlinedSvg from '@ant-design/icons-svg/es/asn/VerticalLeftOutlined'
import { Icon, type IconProps } from '../components/icon'

export function VerticalLeftOutlined(props: IconProps) {
  return <Icon icon={VerticalLeftOutlinedSvg} {...props} />
}
