// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import VerticalAlignMiddleOutlinedSvg from '@ant-design/icons-svg/es/asn/VerticalAlignMiddleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function VerticalAlignMiddleOutlined(props: IconProps) {
  return <Icon icon={VerticalAlignMiddleOutlinedSvg} {...props} />
}
