// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import VerticalAlignTopOutlinedSvg from '@ant-design/icons-svg/es/asn/VerticalAlignTopOutlined'
import { Icon, type IconProps } from '../components/icon'

export function VerticalAlignTopOutlined(props: IconProps) {
  return <Icon icon={VerticalAlignTopOutlinedSvg} {...props} />
}
