// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import VerticalAlignBottomOutlinedSvg from '@ant-design/icons-svg/es/asn/VerticalAlignBottomOutlined'
import { Icon, type IconProps } from '../components/icon'

export function VerticalAlignBottomOutlined(props: IconProps) {
  return <Icon icon={VerticalAlignBottomOutlinedSvg} {...props} />
}
