// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import VerticalRightOutlinedSvg from '@ant-design/icons-svg/es/asn/VerticalRightOutlined'
import { Icon, type IconProps } from '../components/icon'

export function VerticalRightOutlined(props: IconProps) {
  return <Icon icon={VerticalRightOutlinedSvg} {...props} />
}
