// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import VideoCameraAddOutlinedSvg from '@ant-design/icons-svg/es/asn/VideoCameraAddOutlined'
import { Icon, type IconProps } from '../components/icon'

export function VideoCameraAddOutlined(props: IconProps) {
  return <Icon icon={VideoCameraAddOutlinedSvg} {...props} />
}
