// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import VideoCameraOutlinedSvg from '@ant-design/icons-svg/es/asn/VideoCameraOutlined'
import { Icon, type IconProps } from '../components/icon'

export function VideoCameraOutlined(props: IconProps) {
  return <Icon icon={VideoCameraOutlinedSvg} {...props} />
}
