// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import VideoCameraTwoToneSvg from '@ant-design/icons-svg/es/asn/VideoCameraTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function VideoCameraTwoTone(props: IconProps) {
  return <Icon icon={VideoCameraTwoToneSvg} {...props} />
}
