// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import VideoCameraFilledSvg from '@ant-design/icons-svg/es/asn/VideoCameraFilled'
import { Icon, type IconProps } from '../components/icon'

export function VideoCameraFilled(props: IconProps) {
  return <Icon icon={VideoCameraFilledSvg} {...props} />
}
