// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WalletOutlinedSvg from '@ant-design/icons-svg/es/asn/WalletOutlined'
import { Icon, type IconProps } from '../components/icon'

export function WalletOutlined(props: IconProps) {
  return <Icon icon={WalletOutlinedSvg} {...props} />
}
