// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WalletFilledSvg from '@ant-design/icons-svg/es/asn/WalletFilled'
import { Icon, type IconProps } from '../components/icon'

export function WalletFilled(props: IconProps) {
  return <Icon icon={WalletFilledSvg} {...props} />
}
