// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WalletTwoToneSvg from '@ant-design/icons-svg/es/asn/WalletTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function WalletTwoTone(props: IconProps) {
  return <Icon icon={WalletTwoToneSvg} {...props} />
}
