// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WarningOutlinedSvg from '@ant-design/icons-svg/es/asn/WarningOutlined'
import { Icon, type IconProps } from '../components/icon'

export function WarningOutlined(props: IconProps) {
  return <Icon icon={WarningOutlinedSvg} {...props} />
}
