// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WarningTwoToneSvg from '@ant-design/icons-svg/es/asn/WarningTwoTone'
import { Icon, type IconProps } from '../components/icon'

export function WarningTwoTone(props: IconProps) {
  return <Icon icon={WarningTwoToneSvg} {...props} />
}
