// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WarningFilledSvg from '@ant-design/icons-svg/es/asn/WarningFilled'
import { Icon, type IconProps } from '../components/icon'

export function WarningFilled(props: IconProps) {
  return <Icon icon={WarningFilledSvg} {...props} />
}
