// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WechatOutlinedSvg from '@ant-design/icons-svg/es/asn/WechatOutlined'
import { Icon, type IconProps } from '../components/icon'

export function WechatOutlined(props: IconProps) {
  return <Icon icon={WechatOutlinedSvg} {...props} />
}
