// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WechatFilledSvg from '@ant-design/icons-svg/es/asn/WechatFilled'
import { Icon, type IconProps } from '../components/icon'

export function WechatFilled(props: IconProps) {
  return <Icon icon={WechatFilledSvg} {...props} />
}
