// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WechatWorkOutlinedSvg from '@ant-design/icons-svg/es/asn/WechatWorkOutlined'
import { Icon, type IconProps } from '../components/icon'

export function WechatWorkOutlined(props: IconProps) {
  return <Icon icon={WechatWorkOutlinedSvg} {...props} />
}
