// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WechatWorkFilledSvg from '@ant-design/icons-svg/es/asn/WechatWorkFilled'
import { Icon, type IconProps } from '../components/icon'

export function WechatWorkFilled(props: IconProps) {
  return <Icon icon={WechatWorkFilledSvg} {...props} />
}
