// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WeiboSquareOutlinedSvg from '@ant-design/icons-svg/es/asn/WeiboSquareOutlined'
import { Icon, type IconProps } from '../components/icon'

export function WeiboSquareOutlined(props: IconProps) {
  return <Icon icon={WeiboSquareOutlinedSvg} {...props} />
}
