// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WeiboCircleOutlinedSvg from '@ant-design/icons-svg/es/asn/WeiboCircleOutlined'
import { Icon, type IconProps } from '../components/icon'

export function WeiboCircleOutlined(props: IconProps) {
  return <Icon icon={WeiboCircleOutlinedSvg} {...props} />
}
