// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WeiboOutlinedSvg from '@ant-design/icons-svg/es/asn/WeiboOutlined'
import { Icon, type IconProps } from '../components/icon'

export function WeiboOutlined(props: IconProps) {
  return <Icon icon={WeiboOutlinedSvg} {...props} />
}
