// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WeiboSquareFilledSvg from '@ant-design/icons-svg/es/asn/WeiboSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function WeiboSquareFilled(props: IconProps) {
  return <Icon icon={WeiboSquareFilledSvg} {...props} />
}
