// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WeiboCircleFilledSvg from '@ant-design/icons-svg/es/asn/WeiboCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function WeiboCircleFilled(props: IconProps) {
  return <Icon icon={WeiboCircleFilledSvg} {...props} />
}
