// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WhatsAppOutlinedSvg from '@ant-design/icons-svg/es/asn/WhatsAppOutlined'
import { Icon, type IconProps } from '../components/icon'

export function WhatsAppOutlined(props: IconProps) {
  return <Icon icon={WhatsAppOutlinedSvg} {...props} />
}
