// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WifiOutlinedSvg from '@ant-design/icons-svg/es/asn/WifiOutlined'
import { Icon, type IconProps } from '../components/icon'

export function WifiOutlined(props: IconProps) {
  return <Icon icon={WifiOutlinedSvg} {...props} />
}
