// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WindowsOutlinedSvg from '@ant-design/icons-svg/es/asn/WindowsOutlined'
import { Icon, type IconProps } from '../components/icon'

export function WindowsOutlined(props: IconProps) {
  return <Icon icon={WindowsOutlinedSvg} {...props} />
}
