// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WindowsFilledSvg from '@ant-design/icons-svg/es/asn/WindowsFilled'
import { Icon, type IconProps } from '../components/icon'

export function WindowsFilled(props: IconProps) {
  return <Icon icon={WindowsFilledSvg} {...props} />
}
