// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import WomanOutlinedSvg from '@ant-design/icons-svg/es/asn/WomanOutlined'
import { Icon, type IconProps } from '../components/icon'

export function WomanOutlined(props: IconProps) {
  return <Icon icon={WomanOutlinedSvg} {...props} />
}
