// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import XFilledSvg from '@ant-design/icons-svg/es/asn/XFilled'
import { Icon, type IconProps } from '../components/icon'

export function XFilled(props: IconProps) {
  return <Icon icon={XFilledSvg} {...props} />
}
