// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import XOutlinedSvg from '@ant-design/icons-svg/es/asn/XOutlined'
import { Icon, type IconProps } from '../components/icon'

export function XOutlined(props: IconProps) {
  return <Icon icon={XOutlinedSvg} {...props} />
}
