// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import YahooFilledSvg from '@ant-design/icons-svg/es/asn/YahooFilled'
import { Icon, type IconProps } from '../components/icon'

export function YahooFilled(props: IconProps) {
  return <Icon icon={YahooFilledSvg} {...props} />
}
