// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import YahooOutlinedSvg from '@ant-design/icons-svg/es/asn/YahooOutlined'
import { Icon, type IconProps } from '../components/icon'

export function YahooOutlined(props: IconProps) {
  return <Icon icon={YahooOutlinedSvg} {...props} />
}
