// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import YoutubeOutlinedSvg from '@ant-design/icons-svg/es/asn/YoutubeOutlined'
import { Icon, type IconProps } from '../components/icon'

export function YoutubeOutlined(props: IconProps) {
  return <Icon icon={YoutubeOutlinedSvg} {...props} />
}
