// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import YoutubeFilledSvg from '@ant-design/icons-svg/es/asn/YoutubeFilled'
import { Icon, type IconProps } from '../components/icon'

export function YoutubeFilled(props: IconProps) {
  return <Icon icon={YoutubeFilledSvg} {...props} />
}
