// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import YuqueFilledSvg from '@ant-design/icons-svg/es/asn/YuqueFilled'
import { Icon, type IconProps } from '../components/icon'

export function YuqueFilled(props: IconProps) {
  return <Icon icon={YuqueFilledSvg} {...props} />
}
