// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import YuqueOutlinedSvg from '@ant-design/icons-svg/es/asn/YuqueOutlined'
import { Icon, type IconProps } from '../components/icon'

export function YuqueOutlined(props: IconProps) {
  return <Icon icon={YuqueOutlinedSvg} {...props} />
}
