// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ZhihuSquareFilledSvg from '@ant-design/icons-svg/es/asn/ZhihuSquareFilled'
import { Icon, type IconProps } from '../components/icon'

export function ZhihuSquareFilled(props: IconProps) {
  return <Icon icon={ZhihuSquareFilledSvg} {...props} />
}
