// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ZhihuOutlinedSvg from '@ant-design/icons-svg/es/asn/ZhihuOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ZhihuOutlined(props: IconProps) {
  return <Icon icon={ZhihuOutlinedSvg} {...props} />
}
