// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ZhihuCircleFilledSvg from '@ant-design/icons-svg/es/asn/ZhihuCircleFilled'
import { Icon, type IconProps } from '../components/icon'

export function ZhihuCircleFilled(props: IconProps) {
  return <Icon icon={ZhihuCircleFilledSvg} {...props} />
}
