// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ZoomOutOutlinedSvg from '@ant-design/icons-svg/es/asn/ZoomOutOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ZoomOutOutlined(props: IconProps) {
  return <Icon icon={ZoomOutOutlinedSvg} {...props} />
}
