// This file is generated by scripts/generate-icons.mjs. Do not edit manually.
import ZoomInOutlinedSvg from '@ant-design/icons-svg/es/asn/ZoomInOutlined'
import { Icon, type IconProps } from '../components/icon'

export function ZoomInOutlined(props: IconProps) {
  return <Icon icon={ZoomInOutlinedSvg} {...props} />
}
